### ISSUE TITLE
Docker Desktop couple of (newbie) questions (issues, for me)

### ISSUE THREAD

**Issue by ljubacanoa** [kubeapps/kubeapps#1001]
Thanks for nice installation guide, as I get it easy to work on my MacOS Docker Desktop. However, I have couple of issues / questions:

1) How to change localhost to some other URL (to avoid issues with other apps)? I know that first I should to assign URL in my etc/hosts file, but where to set that URL? I guess in Deployment variables, but... Thanks in advance (p.s. - Load Balancer is used).

2)What should to be (local) path of my (ie) WordPress?

3) How to run Bitnami commands to switch WordPress to multisite?

**Comment by andresmgot** [comment]
> How to change localhost to some other URL (to avoid issues with other apps)? I know that first I should to assign URL in my etc/hosts file, but where to set that URL?

To change the host you need to use an Ingress rule in the chart. Note that for that to work you will need an Ingress Controller in your cluster. See:
https://github.com/bitnami/charts/blob/master/upstreamed/wordpress/values.yaml#L205

> What should to be (local) path of my (ie) WordPress?

Since wordpress will be running now in Kubernetes and containers, there is not a local path that you can access. You need to work with volumes instead. Wordpress has persistence enabled by default so you should be able to see the persistent volume in your cluster.

> How to run Bitnami commands to switch WordPress to multisite?

Bitnami commands that are usually available for VM are not available for containers. In particular, it's not possible to use WordPress multisite. If you have more questions about the WordPress chart, the Bitnami support team can help you in its [community site](https://community.bitnami.com/).

Hope that helps,

**Comment by ljubacanoa** [comment]
Thanks for brief and precise answers. Unfortunately, your answers rise additional question:
- Is it mean that when I'm offline, I will not be able to use it?

**Comment by andresmgot** [comment]
> Is it mean that when I'm offline, I will not be able to use it?

That's mostly true, see https://github.com/kubeapps/kubeapps/issues/1002 for more details.

**Comment by ljubacanoa** [comment]
Thanks again. Yes, that mainly answered to all my questions. However, I guess how you can help me with another question too.

If I'm not wrong, I can install Bitnami Wordpress also directly on Kubernetes (as well on Docker), but I will have same question (I guess that you know answers - despite that it is not anymore Kubeaaps related):

- Can it (Bitnami Wordpress) working offline on Kubernetes (and/or Docker)?

**Comment by andresmgot** [comment]
I would say that you will need to at least set a reverse proxy for certain resources but I don't know for sure. You can post that question in the Bitnami community: https://community.bitnami.com/

There you will find experts in Wordpress that will know better than me.

**Comment by arapulido** [comment]
@prydonius

**Comment by prydonius** [comment]
@ljubacanoa you can certainly install the WordPress chart in an offline Docker for Desktop cluster, you can then access it using the NodePort or setup the nginx Ingress Controller (https://kubernetes.github.io/ingress-nginx/deploy/) to access it over localhost.

If you have more specific questions about running the WordPress chart, you might be better off filing an issue in the community site @andresmgot linked to, or in https://github.com/bitnami/bitnami-docker-wordpress.
