### ISSUE TITLE
Pagination for Catalog page

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#1010]
The chartsvc supports pagination as of https://github.com/helm/monocular/releases/tag/v1.5.0, so we should implement this on the UI side of the Catalog page

**Comment by absoludity** [comment]
Let's consider auto-loading on scroll too.

**Comment by absoludity** [comment]
The key thing that relates this task and #2174 is, IMO, that we should be moving towards an interaction-based catalog where some initial (small) subset is presented but items are found by (backend) search and/or filtering. There's already great progress towards this in the UI, but yes, it's about time we did this in the backend :) Moving in this direction will give us a consistent way to display content from hubs in the catalog (which don't have a concept of a list of all the available charts due to the volume).

Thanks for picking it up @antgamdia .

**Comment by antgamdia** [comment]
Here is an update on my initial work on that:

![Peek 2020-12-09 08-44](https://user-images.githubusercontent.com/11535726/101600868-304fa580-39fc-11eb-9400-04f9b20e232f.gif)

My goal was just to get used to the kubeapps frontend development and finish the server-side pagination logic. We should decide which UX is the best for our use case.

> Endless scrolling loads content continuously as the user scrolls down the page, eliminating the need for pagination. 
It is recommended for info with a flat structure, where each unit belongs at the same level of hierarchy and has similar chances of being interesting to users.

> This approach is not recommended for finding tasks, in which people just want to locate specific content. Also, locating a previously found item on an extremely long page is inefficient. It's much easier for people to remember that the item is on page 3 than it is to guess where the item is positioned.


I personally do think that having the endless scrolling is good for Kubeapps, since it's a good option for users just interested in discovering the catalog. On the other hand, we should still support other use cases; wherefore the server-side filtering should be improved. I think the combination of good filters (category, catalog, etc. and free text) could improve the overall UX of the Kubeapps catalog.

**Comment by andresmgot** [comment]
> I personally do think that having the endless scrolling is good for Kubeapps, since it's a good option for users just interested in discovering the catalog. On the other hand, we should still support other use cases; wherefore the server-side filtering should be improved. I think the combination of good filters (category, catalog, etc. and free text) could improve the overall UX of the Kubeapps catalog.

I do agree :+1: So, you are thinking on doing server-side filtering for the left-side filters (provider, category...) and the name and also have auto-loading in the front-end right?

Also, a minor thing regarding the GIF, I see that you are using both a loading spinner and some placeholders for the cards. I would use just one of those things since both reflect a loading status (and I would choose the loading spinner, since the placeholder cards are smaller than the real cards).

**Comment by antgamdia** [comment]
Thanks for your comments. Honestly, I don't know which approach could be totally the best. I've prepared a document with some thoughts on this topic with some ideas for each filter. As soon as I can access back to it (google drive migration :-1: ...) I'll share for having a discussion.
(I'd rather remain unchanged the operators part, since it does not depend on the assetsvc.)

Regarding the left-side filters:

- text search: I'd implement an autosuggestion input, so that charts can be easily retrieved (c.f., [1]). But then, when the users enter the actual query, I'd look it up on the server-side. 

- categories: I'd retrieve first the list of categories so that a user can explore (with endless scrolling) each category

- repo: I'd call the existing repo endpoint instead of retrieving all and filtering in client-side

- type: unchanged

Another idea:  when a user has reached the end (ie, they have explored the whole catalog and it is available on the client-side), some filters can still be performed in the browser. Perhaps we can have a flag in the state so that we invoke the desired logic.

In the GIF, the spinner and the placeholders were used together just the demo. I just wanted to present both loading alternatives so that we can discuss which is better.
From a UX perspective, the spinner reminds "generic loading", that is, a time you'll have to wait in order to continue doing things. The point is that, here, it is not just "loading things", but "loading new charts to discover!", it's like an _exciting_ user interaction.
Perhaps, if we place there the spinner, users won't sroll down so much because they associate it with a negative loading event.
However, I don't know, I'm not a UX expert at all... they are just brainstorm thoughts on it.

[1]
![autocompletion](https://user-images.githubusercontent.com/11535726/102071870-6082b400-3e01-11eb-8a7a-a968422477fc.gif)

**Comment by andresmgot** [comment]
> * text search: I'd implement an autosuggestion input, so that charts can be easily retrieved (c.f., [1]). But then, when the users enter the actual query, I'd look it up on the server-side.

Once you switch to the server-side for doing the search, the text is not only used to compare the chart ID but for check things like the description. For example, in the kubeapps-hub we are using this kind of server-side search and you can look up for things like "blog": https://hub.kubeapps.com/charts?q=blog. If we do the same, we don't need the suggestions.

> * categories: I'd retrieve first the list of categories so that a user can explore (with endless scrolling) each category

+1 

> * repo: I'd call the existing repo endpoint instead of retrieving all and filtering in client-side

+1



> In the GIF, the spinner and the placeholders were used together just the demo. I just wanted to present both loading alternatives so that we can discuss which is better.
> From a UX perspective, the spinner reminds "generic loading", that is, a time you'll have to wait in order to continue doing things. The point is that, here, it is not just "loading things", but "loading new charts to discover!", it's like an _exciting_ user interaction.
> Perhaps, if we place there the spinner, users won't sroll down so much because they associate it with a negative loading event.
> However, I don't know, I'm not a UX expert at all... they are just brainstorm thoughts on it.

I am not sure why you are associating the loading spinner with a negative loading event :stuck_out_tongue:. IMO, as far as there is something that says "loading", it's pretty clear that we are loading new elements for the catalog.

**Comment by antgamdia** [comment]
> I am not sure why you are associating the loading spinner with a negative loading event. IMO, as far as there is something that says "loading", it's pretty clear that we are loading new elements for the catalog.

I agree both things would represent the same concept of "loading". And, honestly, for the Kubeapps' use case (where users are, indeed, technical people), I don't really think it matters.
However, in terms of UX, spinners and skeleton are not the same things, and users, in general, have different perceptions. Check out, for example, this link: https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a

**Comment by andresmgot** [comment]
> However, in terms of UX, spinners and skeleton are not the same things, and users, in general, have different perceptions. Check out, for example, this link: https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a

That's a good point so I am okay with a skeleton then (if you can configure the size, which should be possible).

**Comment by antgamdia** [comment]
Well, so finally I was able to access my documents back again after the migration, so, here we go; please find below the design proposal:

https://via.vmw.com/2020-kubeapps-ui-proposal
