### ISSUE TITLE
Something went wrong when config ingress.

### ISSUE THREAD

**Issue by ygqygq2** [kubeapps/kubeapps#1040]
![360截图-5275314](https://user-images.githubusercontent.com/17672440/58141289-6e983f00-7c75-11e9-8c24-bf3d1d0328ab.jpg)

kubeapps version 1.3.2 and 1.4.0

**Comment by andresmgot** [comment]
Hi @ygqygq2,

It seems that your application has an `Ingress` object with a `tls` section but the `hosts` key within `tls` is not defined. Can that be your issue?

This is the failing code from the trace:

https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/AppView/AccessURLTable/AccessURLItem/AccessURLIngressHelper.tsx#L26

In any case the application should not crash because of that. I am marking this as a bug and we will fix it in the next release.

**Comment by ygqygq2** [comment]
@andresmgot Yes, you are right. But this tls hosts have no setting is allowed, so hopefully this notice can be improved rather than an error.
```
  tls:
    - secretName: tls-secret
      hosts:
        - hosts-domain
```
