### ISSUE TITLE
Broken CSS for Secrets table

### ISSUE THREAD

**Issue by lindhe** [kubeapps/kubeapps#1109]
My Secrets table looks broken. It seems to be some trouble with the flex class, but I know little about HTML/CSS so I can't help much more than just reporting it... :) Can help to debug if you tell me how.

![Table formatting](https://user-images.githubusercontent.com/7773090/62372194-1d3ee280-b537-11e9-8098-9dabd43a18be.png)

Migrated from #848

**Comment by andresmgot** [comment]
Thanks for splitting the issue. @absoludity maybe you can take a look to this? In theory, it's should be  enough setting the `text-overflow: ellipsis;` property ([ref](https://www.w3schools.com/cssref/css3_pr_text-overflow.asp))

**Comment by absoludity** [comment]
Hi there. The issue occurs when the secret type does not have any normal word break characters, such as hyphens. For example, here is what it looks like when a hyphen is present:

![secret-type-with-hyphens-overflow-wrap-normal](https://user-images.githubusercontent.com/497518/62666710-d8e49400-b9c7-11e9-87e4-71116b9df18d.png)

while without hyphens it is as @lindhe found above:

![secret-type-without-hyphens-overflow-wrap-normal](https://user-images.githubusercontent.com/497518/62666723-ec8ffa80-b9c7-11e9-87f8-250f203b1e57.png)

Since the information is important, and we really want it to wrap as it does when hyphens are present, I've just updated it to use `overflow-wrap: anywhere` so that it can break the line anywhere:

![secret-type-without-hyphens-overflow-wrap-anywhere](https://user-images.githubusercontent.com/497518/62666793-3973d100-b9c8-11e9-86e0-6ac322d85859.png)
