### ISSUE TITLE
Improve kubeapps RBAC experience

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#1110]
I find this experience odd:
* charts are listed to user (basically we remove all the standard ones and run with our own internal as only chart repo
* user starts the deployment-process, and first when they hit install the error-message _"You don't have sufficient permissions to create aot-ccm-be-p1 in the aot-ccm-be-p1 namespace
Ask your administrator for the following RBAC roles:
get apprepositories (kubeapps.com) in the kubeapps namespace."_ is shown.

Why is this permission needed? After all they could list the charts. If the permission should be used to filter access to charts in repos, this should happen before they hit "deploy", e.g. in this case the chart-"menu" should look empty - either that or they should not need the permission.

Background in:
https://kubernetes.slack.com/archives/C9D3TSUG4/p1564747418022000
Related to https://github.com/kubeapps/kubeapps/pull/1100

**Comment by absoludity** [comment]
From the above thread (and unrelated to the general aim of improving the general experience:

> IIRC we need to get the repository the user is deploying from to check if there are any auth credentials we need to use to access the chart tarball

So related to the specific issue which David reported, I think that ideally, like David says, it'd be great if this was not required given that it's already not required to be able to list the charts for deploying. The user/admin who adds (and has permission to add) an `AppRepository` custom resource to the Kubeapps installation may not be (by design) the target user deploying the charts.

Checking the code with Adnan's pointer, I see that when creating/installing a new chart repo, if auth was provided Kubeapps records the reference to a k8s secret on the repo CRD and creates a corresponding k8s secret. When a chart is deployed Kubeapps:

1. requests the app repo resource to obtain the auth info (k8s secret reference)
2. sends the chart info to tiller-proxy, including any auth info from 1.
3. tiller proxy parses the request details and [calls out](https://github.com/kubeapps/kubeapps/blob/master/cmd/tiller-proxy/internal/handler/handler.go#L133) to the chart utils pkg's `GetChart()`
4. that helper [requests the content of the k8s secret](https://github.com/kubeapps/kubeapps/blob/master/pkg/chart/chart.go#L341) to include in the headers when getting the chart. 

So `tiller-proxy` already knows how to pull the secret data from the k8s API if the k8s secret reference is included in the request. We could avoid (1) by updating `tiller-proxy` to understand the `AppRepository` custom resource rather than simply the k8s secret reference - and then tiller-proxy can check if auth is required itself (the client doesn't need to). I understand this might go beyond simple proxying, but it seems to already do that by understanding k8s secrets to lookup - not sure. (or, related to some other work I've been thinking about, it could be a separate Kubeapps backend API which wraps the call to tiller-proxy in this case, determining the auth before calling tiller-proxy).

Alternately, we could just surface the issue earlier (I assume it's not surfaced when browsing the charts in the repo because the apprepository-controller handles this?), by ensuring READ on `AppRepository` CRDs is required, but as above, I think this is a little odd given that not all users should require access to `AppRepository` CRDs, rather just those setting up the Kubeapps installation, I think?

**Comment by andresmgot** [comment]
Ah, that was the reason, thanks for the details!

I'd go with adding the functionality to tiller-proxy to retrieve the registry auth if needed. I am not sure how difficult that may be though.

**Comment by prydonius** [comment]
> We could avoid (1) by updating tiller-proxy to understand the AppRepository custom resource rather than the repo url + k8s secret reference - and then tiller-proxy can check if auth is required itself (the client doesn't need to).

+1 I think this makes a lot more sense - thanks for the suggestion @absoludity!
