### ISSUE TITLE
[proposal] Replace AppRepository CRD

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1178]
Right now, the usage of an AppRepository CRD have several disadvantages:

 - It requires admin privileges to be installed. This requires intervention from a cluster admin to be used.
 - Installing a CRD and custom resources with Helm is not trivial. It requires either installing that using the `crd-hook` (gone in Helm 3) or move them to a different folder.
 - The user require special RBAC permissions to read/write these resources (that are not included in the default roles). This has been mitigated in the dashboard but it's still necessary for certain operations.
 - It can cause race conditions (like https://github.com/kubeapps/kubeapps/issues/819) where Helm tries to install custom resources when the CRD is not yet ready.
 - If someone accidentally deletes the CRD all the custom resources in different possible Kubeapps installations will be gone.

If we place that information as Kubernetes `secrets` instead we should be able to get rid of those issues.

 - Any user can install Kubeapps in their namespace without any special requirements.
 - Since we will be working with secrets, we don't need the complexity of managing helm hooks.
 - We get rid of race conditions like above and accidental deletions.

This is the same approach that Helm is using in Helm 3 to store the information about the existing releases (instead of using an AppCRD).

Apart than changing the chart and required roles, to achieve this, we would need to modify the apprepository controller to `watch` secrets in the Kubeapps namespace with certain label selector (e.g. `kubeapps=repository`).

**Comment by andresmgot** [comment]
cc/ @absoludity

**Comment by absoludity** [comment]
> Right now, the usage of an AppRepository CRD have several disadvantages:

Just looking one-by-one:
 
>     * It requires admin privileges to be installed. This requires intervention from a cluster admin to be used.

It requires a cluster admin to be installed, not so much used, but yep, -1
 
>     * Installing a CRD and custom resources with Helm is not trivial. It requires either installing that using the `crd-hook` (gone in Helm 3) or move them to a different folder.

I don't think this is still true - at least, the separate directory used with Helm 3 seems like a good solution to ensure those resources are installed (and ready?). 0

>     * The user require special RBAC permissions to read/write these resources (that are not included in the default roles). This has been mitigated in the dashboard but it's still necessary for certain operations.

But this isn't an issue right? It's just that because [we recommend using the default `edit` clusterrole and binding it to the one namespace](https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md#write-access-to-applications-within-a-namespace), which is for the core api group and a few extensions only? We could update to recommend that + another role for all resources in the namespace quite easily, I think (we already recommend a custom clusterrole for application read)? I really think this point is just that people need correct RBAC to read/write, which isn't an issue IMO?

> 
>     * It can cause race conditions (like #819) where Helm tries to install custom resources when the CRD is not yet ready.

I don't know if this is still an issue - do you?

> 
>     * If someone accidentally deletes the CRD all the custom resources in different possible Kubeapps installations will be gone.

so this is a cluster-wide action affecting all Kubeapps instances, but this is really an RBAC config issue, if you have someone other than an admin able to delete them. Similar issue to the first one - it requires cluster-admin.

So that's -1 for the CRD, but they also have advantages:

 * Defined schema (though we're not using this, it seems?)
 * easily readable from kubectl (though this would also be true for secret/config-map if the relevant data was in the metadata rather than b64 encoded data or similar.

The ["Should I use a configMap or a custom resource?"](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#should-i-use-a-configmap-or-a-custom-resource) is a good comparison, imo.

> If we place that information as Kubernetes `secrets` instead we should be able to get rid of those issues.
> 
>     * Any user can install Kubeapps in their namespace without any special requirements.

Yep, agreed.

> 
>     * Since we will be working with secrets, we don't need the complexity of managing helm hooks. 
>     * We get rid of race conditions like above and accidental deletions.

Not sure that these two apply, or are specific to CRD vs secret/configmap.
 
> This is the same approach that Helm is using in Helm 3 to store the information about the existing releases (instead of using an AppCRD).

Did they use secrets because they're just b64'ing the release data (including sensitive values?), or why were secrets chosen over configmaps?
 
> Apart than changing the chart and required roles, to achieve this, we would need to modify the apprepository controller to `watch` secrets in the Kubeapps namespace with certain label selector (e.g. `kubeapps=repository`).

Right now I'm not sure changing this would be worth the investment, but definitely something to keep in mind moving forward. Or do you think it's urgent-ish?

**Comment by andresmgot** [comment]
>>  Installing a CRD and custom resources with Helm is not trivial

> I don't think this is still true - at least, the separate directory used with Helm 3 seems like a good solution to ensure those resources are installed (and ready?).

In theory yes, but still is a procedure more prone to issues since the lifecycle is handled differently. They have had issues in the past and I assume they may keep happening. For example:

https://github.com/kubeapps/kubeapps/issues/1185

>>* The user require special RBAC permissions to read/write these resources (that are not included in the default roles). This has been mitigated in the dashboard but it's still necessary for certain operations.

> But this isn't an issue right? It's just that because we recommend using the default edit clusterrole and binding it to the one namespace, which is for the core api group and a few extensions only? We could update to recommend that + another role for all resources in the namespace quite easily, I think (we already recommend a custom clusterrole for application read)? I really think this point is just that people need correct RBAC to read/write, which isn't an issue IMO?

Default roles/clusterroles don't use wildcards for resources so even if it's not an issue, users need to create an additional role (on their own) to be able manage apprepositories. Is just a matter of having a bit better UX if they have to follow one step less.

> So that's -1 for the CRD, but they also have advantages:
> The "Should I use a configMap or a custom resource?" is a good comparison, imo.

Yes, the CRDs have several advantages like direct support with `kubectl` and lifecycle management like defining the `status`. The thing is that we are not really using those advantages so for the little that we gain we have to pay the price of the issues I list. 

>>* Since we will be working with secrets, we don't need the complexity of managing helm hooks. 
>>* We get rid of race conditions like above and accidental deletions.

> Not sure that these two apply, or are specific to CRD vs secret/configmap.

I am referring to the different issues that we have found in the past due the the CRDs hooks for installation.

> Did they use secrets because they're just b64'ing the release data (including sensitive values?), or why were secrets chosen over configmaps?

Yes, mostly because the release information includes sensitive values like passwords and certs. We could actually use configmaps because the information we hold in the AppRepository is not sensitive. In case we need credentials or certs we point to an external secret.

> Right now I'm not sure changing this would be worth the investment, but definitely something to keep in mind moving forward. Or do you think it's urgent-ish?

We keep receiving issues related to that but it's true that the changes are not trivial (and will likely introduce breaking changes). I don't think it's urgent but probably something I would include in case we plan to work in a new major version.

**Comment by prydonius** [comment]
Just my two cents - switching away from a CRD to a Secret or ConfigMaps seems like a bit of a step back. The community is pretty clear on recommending CRDs if the usecase is to build automation that acts on a CR. There are good reasons for this, as @absoludity mentions CRDs support schema, versioning, the status subresource (which we could use in the future to store information about recent syncs, last sync timestamp, etc.).

> The user require special RBAC permissions to read/write these resources (that are not included in the default roles). This has been mitigated in the dashboard but it's still necessary for certain operations.

Are there examples of users getting bitten by this? As @absoludity mentions, this could mostly be because of the recommendation to use the edit role. Anyway, the documentation is pretty clear about how to grant read/write access to these resources.

In fact, this is much better than requiring all users that need to read/write repositories to have read/write access to all ConfigMaps or Secrets in a namespace.

> If someone accidentally deletes the CRD all the custom resources in different possible Kubeapps installations will be gone.

Likewise, if someone accidentally deletes the Secrets in their namespace(s), then their repository info is lot. I don't know that deleting the CRD is any easier than accidentally deleting Secrets or other important resources related to a Kubeapps installation. Again, are there examples of users accidentally deleting the CRD, or is this speculative? There are many Operators out there using CRDs, and this doesn't appear to be a big concern for them.

If we are really concerned about these issues, I would consider moving AppRepository's to the database instead of using a ConfigMap or Secret.

**Comment by migmartri** [comment]
Hi there!

I think I understand the technical implications of using CRDS vs Secrets but is the motivation for this change merely technical? Is this driven by a product request, user request, bug report?

**Comment by andresmgot** [comment]
Sorry, I missed the comments here @absoludity @migmartri, let me reply.

> There are good reasons for this, as @absoludity mentions CRDs support schema, versioning, the status subresource (which we could use in the future to store information about recent syncs, last sync timestamp, etc.).

Correct, the thing is that we are not using any of those benefits. At the end we are just using the AppRepository CRD to store data. We are not using the schema nor the versioning or the status (and I don't foresee that we will). Another great benefit of using CRD is to be able to edit/create/view them with kubectl (like `kubectl get apprepositories`) but we are not extensively using that either. I think a CRD is more useful when it's representing something in the cluster (not data in an application) like a CronJob, an Application or a serverless function. Those CRDs are later translated to other Kubernetes entities, so it makes sense that you can do versioning or check the status.

> Are there examples of users getting bitten by this? As @absoludity mentions, this could mostly be because of the recommendation to use the edit role. Anyway, the documentation is pretty clear about how to grant read/write access to these resources.

I found this myself the other day when working with the end-to-end tests:

https://github.com/kubeapps/kubeapps/pull/1261/files#r340173506

I added the user to the `admin` cluster role but it doesn't have permissions to write/read the `apprepositories`.

There has been a lot of related issues to that: https://github.com/kubeapps/kubeapps/search?p=2&q=apprepository-rbac&type=Issues but we have been fixing those as they appear.

> In fact, this is much better than requiring all users that need to read/write repositories to have read/write access to all ConfigMaps or Secrets in a namespace.

Correct but if a user is able to deploy charts in a namespace, it's usually necessary to have permissions to access those.

> Likewise, if someone accidentally deletes the Secrets in their namespace(s), then their repository info is lot. I don't know that deleting the CRD is any easier than accidentally deleting Secrets or other important resources related to a Kubeapps installation. Again, are there examples of users accidentally deleting the CRD, or is this speculative? There are many Operators out there using CRDs, and this doesn't appear to be a big concern for them.

It has happened, mostly as a result of an upgrade:

https://github.com/kubeapps/kubeapps/issues/625
https://github.com/kubeapps/kubeapps/issues/800

> If we are really concerned about these issues, I would consider moving AppRepository's to the database instead of using a ConfigMap or Secret.

That's also a valid option but I don't think we want to increase the dependency of mongodb. It's also useful if users can list the repositories or check the info within them using `kubectl`.

> I think I understand the technical implications of using CRDS vs Secrets but is the motivation for this change merely technical? Is this driven by a product request, user request, bug report?

Both. This came from the experience I have had finding issues with the CRDs. For me, the biggest point is that users **cannot** use Kubeapps if they are not admins of the cluster. I think that's an important barrier in the adoption of the product.

**Comment by prydonius** [comment]
> We are not using the schema nor the versioning or the status (and I don't foresee that we will).

Why not? I can definitely see places where we can use status (e.g. to report failures, last run times, etc.). As for versioning, even if we switch to Secrets, we will probably need to handle versioning (Tiller did this with a VERSION label) in case we want to change the schema in the future.

> I think a CRD is more useful when it's representing something in the cluster (not data in an application) like a CronJob, an Application or a serverless function. Those CRDs are later translated to other Kubernetes entities, so it makes sense that you can do versioning or check the status.

That's a fair point, but actually the reason for this design is because the App Repositories are translated to CronJobs and Jobs, so IMO it fits the usecase well.

> In fact, this is much better than requiring all users that need to read/write repositories to have read/write access to all ConfigMaps or Secrets in a namespace.

Currently, all AppRepositories are in the kubeapps namespace, how would this change if we switched to Secrets in the users namespace? In order to list all the AppRepositories, you'd have to have access to list Secrets cluster-wide, which is definitely going to be a security concern. If we keep all the Secrets in the kubeapps namespace, users will need permissions for their namespace and the ability to list/create Secrets in the kubeapps namespace. So two roles need to be assigned, which is no better than what we currently have with the AppRepository admin role.

> That's also a valid option but I don't think we want to increase the dependency of mongodb. It's also useful if users can list the repositories or check the info within them using kubectl.

To be clear, my point is to store this in the database and not using Secrets/ConfigMaps. Whether that's MongoDB or something else we move to is an implementation detail. I think we will still need a database for Kubeapps.

> Both. This came from the experience I have had finding issues with the CRDs. For me, the biggest point is that users cannot use Kubeapps if they are not admins of the cluster. I think that's an important barrier in the adoption of the product.

Do you mean users cannot install Kubeapps without being an admin? Once installed, a user can use Kubeapps and not be a cluster-admin, right? In fact, a user doesn't necessarily even need to be an admin to install Kubeapps, since Tiller is cluster-admin.

**Comment by andresmgot** [comment]
> Why not? I can definitely see places where we can use status (e.g. to report failures, last run times, etc.). As for versioning, even if we switch to Secrets, we will probably need to handle versioning (Tiller did this with a VERSION label) in case we want to change the schema in the future.

I agree but we haven't had the need to do so so far, that's why I don't think this will become a priority.

> Currently, all AppRepositories are in the kubeapps namespace, how would this change if we switched to Secrets in the users namespace? In order to list all the AppRepositories, you'd have to have access to list Secrets cluster-wide, which is definitely going to be a security concern. If we keep all the Secrets in the kubeapps namespace, users will need permissions for their namespace and the ability to list/create Secrets in the kubeapps namespace. So two roles need to be assigned, which is no better than what we currently have with the AppRepository admin role.

So we would have two possibilities here: either we have the secrets in the `kubeapps` namespace (so yes, the user will need RBAC permissions to see those) or we move to an approach of having repositories per namespace (which is convenient for multi-tenancy). In any case, that was not my point here, I just wanted to highlight that for example the default cluster role `admin` doesn't have permissions to modify these new resource types so you need an additional role (I am not sure about the `cluster-admin` role).

> To be clear, my point is to store this in the database and not using Secrets/ConfigMaps. Whether that's MongoDB or something else we move to is an implementation detail. I think we will still need a database for Kubeapps.

Yes, agree about the need of a database, it's just that right now that is MongoDB. Anyway, I would still not do so to be able manage these repositories with a CLI (`kubectl`)

> Do you mean users cannot install Kubeapps without being an admin? Once installed, a user can use Kubeapps and not be a cluster-admin, right? In fact, a user doesn't necessarily even need to be an admin to install Kubeapps, since Tiller is cluster-admin.

Right, I mean that installing Kubeapps require admin permissions (at least the first time). This happens in environments like Openshift (AFAIK). Note that we are talking about implementing this after migrating to Helm v3 (so no tiller is involved).

**Comment by prydonius** [comment]
> In any case, that was not my point here, I just wanted to highlight that for example the default cluster role admin doesn't have permissions to modify these new resource types so you need an additional role (I am not sure about the cluster-admin role).

`cluster-admin` would have the permission. In the first approach, you'd have to apply admin/or secrets admin permission in the `kubeapps` NS and the user's namespace. In which case, users might as well just apply the `apprepositories-admin` role instead of admin or secret role.

The multi-tenant case would be very interesting, and we could look at extending chartsvc to only return charts from repos in the current namespace (we would need to check against the k8s API to verify that a request has access to requested repos). This is obviously a much bigger task and re-architecture of Kubeapps.

> Right, I mean that installing Kubeapps require admin permissions (at least the first time). This happens in environments like Openshift (AFAIK). Note that we are talking about implementing this after migrating to Helm v3 (so no tiller is involved).

Understood, thanks for that context.

Going back to the multi-tenant case, I think the AppRepository is still a valuable CRD. Users will likely have full access (e.g. cluster-admin) to the namespace, and should be able to create/delete them as they need. If an org wants more restriction with a namespace, then the `apprepositories-admin` Role still applies and can be used. What if I wanted a user to access and create Secrets in the namespace, but not mess with the Kubeapps install and not add any new repos? If we use Secrets, that's not possible. If the concern is having to apply more RBAC roles, IMO it's not a strong concern. We can recommend applying `cluster-admin` in our docs and suggest more specific roles where necessary.

**Comment by andresmgot** [comment]
> What if I wanted a user to access and create Secrets in the namespace, but not mess with the Kubeapps install and not add any new repos? If we use Secrets, that's not possible.

Right, that will require some extra thinking. It would be weird to give someone admin privileges in a namespace but not giving them permissions to modify their Kubeapps instance though.

In any case, the only "unsolvable" issue is that the first user installing kubeapps in a cluster should be an admin. That's okay for the moment but we may receive a specific request to support the non-admin scenario in the future. Let's wait until getting more feedback on that front.

**Comment by absoludity** [comment]
During a conversation with @zehuaiWANG (who was also asking why we need a CR, in the context of multi-cluster where it would mean each cluster requires the CR), I realised that moving the sync cronjob to the users namespace (#1647) will perhaps be one less reason to require a CRD, as we won't want Kubeapps (specifically, the CRD controller) to create a cronjob in the users namespace (or require RBAC to do so), instead creating the cronjob with the app repository model (whether a CR or ConfigMap) using the users account.
