### ISSUE TITLE
kube/   401 Unauthorized 

### ISSUE THREAD

**Issue by nevido** [kubeapps/kubeapps#1189]
hello there.

i have some question
how can  gatekeeper find token ?
if i have some sa and secret and etc in default namesapce and kubeapps namespace 

and try to login via proxy(gatekeeper) 
i guess it has token but.. i'am wondering how can keeper find it? or choose it 

after login via proxy

i get the  kube/    401 Unauthorized

[There was an error connectiing to the Kubernets API. Plase check that your token is valid.]

so want to change other token to login [token] via proxy

p/s i'm using keycloak n keeper on aks

**Comment by andresmgot** [comment]
Hi @nevido,

In order to use keycloak-gatekeeper to login you need to enable it as explained in:

https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md

If using the auth proxy fails, then you see the traditional login page in Kubeapps.

If you are using AKS, you also need to enable it when creating the cluster. You can find a very good guide from azure here: https://docs.microsoft.com/en-us/azure/aks/azure-ad-integration

Hope that helps.

**Comment by andresmgot** [comment]
hi @nevido, any news here? Are you still finding issues?
