### ISSUE TITLE
Unable to add valid chart repository via the wizard

### ISSUE THREAD

**Issue by david-streamlio** [kubeapps/kubeapps#121]
I have downloaded and installed the latest version of Kubeapps (0.0.2), and when I attempt to add the following URL as a Repository, none of the charts are visible / searchable from the UI:  

https://storage.googleapis.com/streamlio/charts/

There is a valid index.yaml file at that location....
![screen shot 2018-02-01 at 4 10 03 pm](https://user-images.githubusercontent.com/35466513/35710107-85af11f4-076a-11e8-88db-599909538e31.png)
![screen shot 2018-02-01 at 4 09 46 pm](https://user-images.githubusercontent.com/35466513/35710110-8885e9b6-076a-11e8-9716-c1b33c104770.png)
![screen shot 2018-02-01 at 4 11 31 pm](https://user-images.githubusercontent.com/35466513/35710120-9669776e-076a-11e8-9b68-a79fce79bce4.png)

**Comment by arapulido** [comment]
Thanks for your bug report!

There are 2 issues here:

* First of all, you need to put the URL without the trailing "/", so you need to put ```https://storage.googleapis.com/streamlio/charts``` instead of ```https://storage.googleapis.com/streamlio/charts/```

This is bad UX and it needs to be fixed for sure.

* Also, even if you don't add the trailing "/", the chart that you are using doesn't have a README.md, and currently, kubeapps fail to load charts without a README.md file. This will be fixed in 0.3.0.

In the mean time you can workaround this by adding a README.md file to your chart.

(cc @prydonius )

**Comment by prydonius** [comment]
Indeed, the other issue is that currently you'll have to wait up to 15m for Kubeapps to sync chart repositories (it does it on a schedule every 15m). 0.3.0 will update this to sync immediately after adding a new repository.

**Comment by kramasamy** [comment]
@arapulido @prydonius - Should the README.md part of the helm chart or it should be outside the chart?

**Comment by prydonius** [comment]
@kramasamy part of the chart at the root, see https://github.com/kubernetes/charts/tree/master/stable/wordpress as an example

**Comment by david-streamlio** [comment]
@kramasamy  has added the README.md file, and I have entered the proper URL, i.e https://storage.googleapis.com/streamlio/charts and I am able to find the desired Charts.
![screen shot 2018-02-05 at 2 18 49 pm](https://user-images.githubusercontent.com/35466513/35831731-9bfbcfe8-0a7f-11e8-9ac7-4b340ac98ce6.png)

Thanks for your help, and please close this issue as RESOLVED
