### ISSUE TITLE
Add support to "complex conditions" for hidden items on basic forms

### ISSUE THREAD

**Issue by juan131** [kubeapps/kubeapps#1336]
**Description**

According to [the documentation](https://github.com/kubeapps/kubeapps/blob/master/docs/developer/basic-form-support.md#subsections):

> The tag hidden can be a string pointing to the parameter that needs to be true to hide the element or an object to also set the value that the pointed value needs to match.

This doesn't give us much space to create "hidden rules" when two or more parameters need to be true, or to use other conditions such as "matchString".

E.g. check: https://github.com/helm/charts/pull/19300

**Version of Helm, Kubeapps and Kubernetes**:

- Output of `helm list <kubeapps-release-name>`:

```console
$ helm list kubeapps
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Thu Nov 28 12:23:42 2019	DEPLOYED	kubeapps-3.1.0	v1.7.1     	kubeapps
```

**Comment by andresmgot** [comment]
Thanks @juan131 for filling the issue. From the description I see two different requests:

 1. Allow to set an array of conditions instead of just one. Then the parameter can be hidden if all or any of the conditions match.
 2. Allow other type of comparisons. Right now it's only possible to match exact values.

I believe that for adding the schema for redmine you only need the first, right?

**Comment by juan131** [comment]
Yes @andresmgot 
For the Remine case, I only need the 1st one.
