### ISSUE TITLE
Error while launching kubeapps dashboard with GKE Kubernetes 1.9V

### ISSUE THREAD

**Issue by ymallipe** [kubeapps/kubeapps#138]
Hello,

I have my K8's cluster running V1.9.2-gke.1

yesudasm89@ymallipeddi189:~$ kubeapps up
ERRO[0001] can't get active gke user: can't read file active_config: open /home/yesudasm89/.config/gcloud/active_config: no such file or directory 

What could be this error..?
![kubeapps_error](https://user-images.githubusercontent.com/5363603/36669298-5db4aa38-1b1a-11e8-8873-d43294bc2aa0.PNG)

**Comment by arapulido** [comment]
This is a valid bug. Currently, we hardcode the path to the glcoud config, and we shouldn't be doing that: https://github.com/kubeapps/kubeapps/blob/master/pkg/gke/gke.go#L99

We should allow passing the configuration path as an optional argument.

Where do you have your gcloud configuration folder? Can you try installing it in the default path to see if it fixes it?

Thanks for your report

**Comment by ymallipe** [comment]
Below are the steps followed
1) Spin up new Instance
2) Installed [Gcloud SDK](https://cloud.google.com/sdk/downloads#yum)
3) Setup Account
4) Setup Kubectl
5) Kubeapp up 

Below is the error while using kubeapps up.
![kubeaps_errorrr](https://user-images.githubusercontent.com/5363603/36687989-1c6fff14-1b51-11e8-9c0d-63996c7e4f4e.PNG)

**Comment by arapulido** [comment]
What role do you have in the project that hosts your GKE cluster? Kubeapps requires to either be Owner or Container Engine Admin

**Comment by ymallipe** [comment]
Owner for GKE Cluster

**Comment by arapulido** [comment]
The role I am asking about, is the role in your GCP project.
You can check the role you have on this URL: https://console.cloud.google.com/iam-admin/iam

Then you should grant your user (or ask your administrator) the "Kubernetes Engine Admin" or "Owner" roles

**Comment by prydonius** [comment]
@ymallipe can you paste the output of `gcloud auth list`, I'm guessing you don't have an active account in your gcloud config.

**Comment by ymallipe** [comment]
@arapulido  Myself owner for GKE Cluster with full permission(s)
@prydonius  : Attached
![gcloudauthlist](https://user-images.githubusercontent.com/5363603/36726665-99837a3c-1be0-11e8-85e8-f99329158e63.PNG)

**Comment by ymallipe** [comment]
Attached
![image](https://user-images.githubusercontent.com/5363603/36728901-59dde4dc-1be8-11e8-8b47-f72336d398a0.png)

**Comment by arapulido** [comment]
It says "Multiple" which unfortunately means that there are several roles, and I cannot know which ones. Can you tell me what roles are selected if you click on the arrow next to "Multiple" (on the row with your email address)

**Comment by ngtuna** [comment]
@arapulido Yes I agree we should provide flag to specify custom gcloud configuration path. I am just concerning what the UX looks like. That flag will only valid for GKE. So I suggest `kubeapps up --provider GKE --config-path /path/to/gcloud/config` to make it clearer. Probably in future kubeapps need some more provider-specified configurations so we might have `--provider AWS | minikube | openshift` . Alternatively we might have `kubeapps.yaml` as configuration file (like [serverless.yml](https://serverless.com/learn/quick-start/))

@ymallipe If you can set your account with role that @arapulido mentioned it will work I believe.

**Comment by ymallipe** [comment]
@arapulido Attached 
![gcp permisions](https://user-images.githubusercontent.com/5363603/36936713-dd4c3da2-1f2e-11e8-8c74-328160fe7941.jpeg)

**Comment by prydonius** [comment]
I ran into this whilst trying to run kubeapps in Google's cloud shell. They use an env var (`CLOUDSDK_CONFIG=/tmp/tmp.n8D7sDBqQs`) to configure the config location, we can read this env var when looking for the config.

**Comment by gidihup** [comment]
@arapulido, I am also getting this error on trying to use kubeapps on GCP.
Is there any ongoing effort to correct this?

**Comment by prydonius** [comment]
After some more investigation in #310, I've found that it's not possible to get the account email the same way we do on a local gcloud configuration in the Google Cloud Shell. This is because we read the configuration file (e.g. `~/.config/gcloud/configurations/config_default`) to get the account email. On a local gcloud installation, this works, but in the Cloud Shell the configuration file doesn't contain the email.

The `gcloud` CLI seems to use a socket connection to get credential information from a service when running in the Cloud Shell (https://github.com/google-cloud-sdk/google-cloud-sdk/blob/master/lib/googlecloudsdk/core/credentials/devshell.py).

To make this work in Cloud Shell and locally, we have 2 options:

1. Run `gcloud config get-value core/account` as an external command
2. Replicate the way the `gcloud` CLI connects to the credential service, and build in a special case when running in the Cloud Shell

The first option will be much easier to implement and maintain going forward (e.g. in case the way `gcloud` stores the configuration locally or the API for the Cloud Shell credential service changes). It will require having `gcloud` in the user's path, but I don't think this will be an issue (given you'll need it in your path to login and configure in the first place).

The other option here is to not support the Cloud Shell at all, we can detect the `DEVSHELL_GCLOUD_CONFIG` env var and return an error stating that Kubeapps needs to be run locally. However, I think it will be better to go with option 1.

**Comment by arapulido** [comment]
@prydonius I would go with 1 as well
