### ISSUE TITLE
Namespace selector should display namespaces to which the user has access

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1471]
### Description:
Kubeapps should present the user with the namespaces to which they have access.

Currently if you use Kubeapps without the cluster-wide RBAC to get namespaces, you can only select from "All Namespaces" and "default", even though you may not have access to the default namespace (you can with Helm 2 + Kubeapps actually create namespaces, but that leads to issues like #1364).

Conversely if you use Kubeapps with the cluster-wide RBAC to get namespaces, you can select from the complete list of namespaces, even if you are not able to use certain namespaces (ie. cannot read secrets in that namespace).

### Steps to reproduce the issue:

1. Authenticate as a non cluster-admin with access to a personal namespace "my-namespace"
2. Check the Namespace selector dropdown

Expected Result:

- All Namespaces (though see #598)
- my-namespace
- (any other namespaces to which I have access)

Actual Result:
- All Namespaces
- default

### Additional information you deem important:

~~This would be useful not only in the UI, but I expect for also (later) verifying the AppRepositories to which a user has access (and from which should see charts etc.). More to come on that separately.~~

**Comment by absoludity** [comment]
The main benefit of [OpenShift's Project resource](https://docs.openshift.com/container-platform/4.2/authentication/using-rbac.html#rbac-projects-namespaces_using-rbac), from Kubeapps point of view, is that “The project list is a special endpoint that determines what projects you should be able to see. This is not possible to express via RBAC (i.e. list namespaces means you can see all namespaces).” (from a [comment from an OpenShift dev on reddit](https://www.reddit.com/r/openshift/comments/78jcpk/namespaces_vs_projects/douq0xo/)):

There have been a couple of requests for only listing namespaces to which the requestor has access in Kubernetes itself ([48537](https://github.com/kubernetes/kubernetes/issues/48537), community [1486](https://github.com/kubernetes/community/issues/1486)) both of which are answered by the same person with the same response: Kubernetes APIs do not support ACL-filtered lists (though further discussion on [40403](https://github.com/kubernetes/kubernetes/issues/40403)), and linking to the [OpenShift add-on API](https://github.com/openshift/kube-projects) for ACL-filtered namespaces/projects.

We could potentially add a much simplified version of this endpoint via Kubeapps (via the backend/kubeops). We don’t need this to be a watchable k8s resource or similar, but rather an internal helper so that we can return only the namespaces to which the requester has access.

Exactly what "has access" means may be tricky, but I'd recommend keeping it minimal: If you can read secrets from a namespace (ie. a read-only user who can see apps in the UI for a namespace), then you can access that namespace from Kubeapps. This allows us to determine not only that the (current) default helm release info will be visible to the user, but also later that they can access AppRepository credentials etc.

We can handle missing RBAC for anything else (create/delete) as we do now, ie. nicely presenting to the user the RBAC required to fulfil that action.

Thoughts?

**Comment by andresmgot** [comment]
so we are talking about two different things here:
 - [bug] A user without access to the default namespace gets it listed (and selected) in the namespace selector. I don't fully understand why this is happening: is the serviceaccount of the token created for the `default` namespace or is this because the token doesn't contain information about the default namespace (OIDC scenario)? We should be able to fix this without implementing the next point.
 - [feature] Have an API endpoint to return the list of namespaces that the user has access to. It's a nice feature and we can implement it as you mention (although it may be difficult to implement the logic to check the namespaces with permissions for a user). This can be address separately.

There is also a third point, to reevaluate the namespace selector behavior: #598 . We never started working on that because we don't have a clear desired UX.

So maybe we should let this issue to address the bug fix (if possible) and open a new one for the feature? WDYT?

**Comment by absoludity** [comment]
> so we are talking about two different things here:
> 
>     * [bug] A user without access to the default namespace gets it listed (and selected) in the namespace selector. I don't fully understand why this is happening: is the serviceaccount of the token created for the `default` namespace or is this because the token doesn't contain information about the default namespace (OIDC scenario)? We should be able to fix this without implementing the next point.

I didn't think of this as a bug at all, because yes, it's the OIDC case that I'm using in my dev env, so there is nothing in the token to indicate the namespace. Not sure how we can fix this for the OIDC case, but nor do I see it as too much of an issue given that with the second point, people will always be seeing the namespaces to which they have access.

> 
>     * [feature] Have an API endpoint to return the list of namespaces that the user has access to. It's a nice feature and we can implement it as you mention (although it may be difficult to implement the logic to check the namespaces with permissions for a user). This can be address separately.

Great.

> 
> 
> There is also a third point, to reevaluate the namespace selector behavior: #598 . We never started working on that because we don't have a clear desired UX.

That seemed to be more about the "All namespaces" option in the drop down (ie. whether that should be there)

> 
> So maybe we should let this issue to address the bug fix (if possible) and open a new one for the feature? WDYT?

Don't mind, happy to leave this issue for the feature, given the title, but don't mind either way :)

**Comment by andresmgot** [comment]
> Don't mind, happy to leave this issue for the feature, given the title, but don't mind either way :)

For me it would depend if there is an easy way of fixing the issue without the need of the feature. If the proper way of fixing that issue is implementing the API endpoint then we can just use this issue for both.

**Comment by absoludity** [comment]
> For me it would depend if there is an easy way of fixing the issue without the need of the feature. If the proper way of fixing that issue is implementing the API endpoint then we can just use this issue for both.

Yes, IMO it is the latter - by adding the API endpoint and only presenting namespaces to which a user has access, a user will never be presented with namespaces to which they do not have access.

**Comment by absoludity** [comment]
Note: though the new endpoint may default to checking which namespaces the requester can read secrets, it will be useful to allow arguments so that, for example, we can request all namespaces to which the user can write Secrets and AppRepositories.

**Comment by andresmgot** [comment]
I foresee RBAC errors for AppRepositories...

**Comment by absoludity** [comment]
> I foresee RBAC errors for AppRepositories...

We already have them? If I authenticate currently as a normal user (ie. unable to read app repos in the kubeapps namespace) I see:

![app-repo-rbac](https://user-images.githubusercontent.com/497518/72841705-03fb3f80-3ceb-11ea-9998-b005aa52e8f7.png)

...as we would currently expect?

**Comment by andresmgot** [comment]
> We already have them? If I authenticate currently as a normal user (ie. unable to read app repos in the kubeapps namespace) I see:

Yes (and I am not a fan of them) but I thought you mean to only return namespaces to people with permissions to write apprepositories there. Today, it's not necessary for a person to have those permissions to use kubeapps.

> But my note above was just that any endpoint for checking specific user access to namespaces would be doubly useful if you could optionally specify the resources you wanted to check. So for a different example, if we later switched to use the ConfigMap helm driver instead of the secret driver, the change would be trivial.

That's fine then :+1:

**Comment by andresmgot** [comment]
so the implementation would be:

 - The dashboard makes an initial request (when loading the header): `GET /apis/namespaces/v1/`
 - Tiller-proxy/kubeops list all namespaces (we need to add RBAC permissions for that, note that this 
 is a cluster-wide permission)
 - For each one of the existing namespaces, check if the user has permissions to read secrets.
 - Return the list of namespaces.

Note that this doesn't cover https://github.com/kubeapps/kubeapps/issues/1364 since we won't reload the list of namespaces (but we can do so if we re-do the steps if the user submits a new namespace).

I am not sure if this could be a scalability issue for clusters with a big number of namespaces but it probably wont.

**Comment by andresmgot** [comment]
I am doing some testing about this, the biggest problem is that we would need to create a ClusterRole and a ClusterRoleBinding for the backend service so it can list namespaces. This would raise the installation barrier because only admins would be able to install kubeapps (before, it was only necessary to install the CRD beforehand).

Another possibility would be to use the user token to try to list namespaces. Then we can filter those namespaces with the ones that they can access to. The problem with that would be that if a user doesn't have permissions to list namespaces we would need to default to one. I would say to default to the serviceaccount namespace or `kubeapps` namespace and check if the user has permissions to write there. In any case, in the OIDC scenario we would have no way of auto-discovering the default namespace if both checks fails. We could prompt the user to introduce a namespace to use in that case though.

None of the approaches are ideal but I would go for the second since it avoids having to install cluster-wide resources.

**Comment by absoludity** [comment]
> * Tiller-proxy/kubeops list all namespaces (we need to add RBAC permissions for that, note that this
>   is a cluster-wide permission)

That would be the easiest, but as you say, not necessarily something we want. Let's brainstorm other options too: 

1. Kubeapps run with a config of namespaces it should know about by default: not great if it can't be dynamic as people try to use other namespaces.
2. Kubeapps could collect namespaces as users use them, using our new non-single-point-of-failure backend :-) (Security-wise, only danger I can think of is that user with access to the actual kubeapps backend store (postgres) may be able to see more namespaces listed than they have access to, which I do not see as an issue) 
3. Combination of the above - runs with ["kube-system", "default", "kubeapps"] initially, but adds to this list

Any endpoint should only ever reveal namespaces to which the requester can read secrets (? as a minimum check, to be able to browse installed applications, for which they'd obviously need access to other resources too)

> 
> * For each one of the existing namespaces, check if the user has permissions to read secrets.
> ...
> I am not sure if this could be a scalability issue for clusters with a big number of namespaces but it probably wont.

That's unfortunate - I'd assumed we could send multiple checks as part of the [SelfSubjectAccessReview](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#selfsubjectaccessreviewspec-v1-authorization-k8s-io), but it appears not. As you say, it shouldn't be an issue, especially if we are (1) not checking all namespaces on the cluster, but just those configured or used by users, and (2) we only evaluate this approx. once per user session.


> Another possibility would be to use the user token to try to list namespaces. Then we can filter those namespaces with the ones that they can access to.

And, depending what you think of the above, actually learning from it for other users (but only ever returning those namespaces to which they have access)?

> The problem with that would be that if a user doesn't have permissions to list namespaces we would need to default to one.

They can still benefit from Kubeapps knowledge of other namespaces, from other users (depending what you think) or at least, from the configured default namespaces ("kube-system", "kubeapps", "default" or whatever) given that we'll actually be *verifying* that they have access rather than just presenting them.

See what you think - looks like there's a bit of design work in this. Might be worth re-evaluating if it's worthwhile, but for the time I've been on Kubeapps it's been a recurring issue for me. Should be simple to split into smaller tasks (ie. do without storage first or whatever).

**Comment by andresmgot** [comment]
I would be worried about storing those namespaces and Kubeapps "learning" new namespaces because it would lead to an inconsistent behavior. The user A would see different namespaces in different sessions just because the user B has interacted with Kubeapps in between. Also we would need to persist that information somewhere and keep it up to date (again, prone to sync errors).

Because of that, I would rather go with explicit requests. Considering the different cases:

 - The user A has admin permissions. It can list namespaces so we can list all of them (just as we do today) and return the ones with write permissions.
 - The user B has permissions in the namespace `ns-b`. The token for this user is coming from a serviceaccount in that namespace. Since we can extract that information from the token, use it as the default (just as we do today).
 - The user C only have permissions in the namespace `default` (or `kubeapps`). We cannot list namespaces with its token so we fallback to the well-known list of namespaces: `default` and the kubeapps installation namespace (`kubeapps` by default). Since it has permission for a well known namespace, return that in the backend.
 - The user D (logged using OIDC) only have permissions for the namespace `ns-d`. Since it's logged with an OIDC account we are not able to automatically discover the namespace nor it has permissions for the default namespaces. In this case, the dashboard prompt to introduce a default namespace. After checking that the user has permissions in that namespace, the choice is stored in the browser.

That way we mimic the Kubernetes behavior, if the user don't have permission to list namespaces, they will never see that list (even if they have permissions to write in several ones).

**Comment by absoludity** [comment]
> I would be worried about storing those namespaces and Kubeapps "learning" new namespaces because it would lead to an inconsistent behavior. The user A would see different namespaces in different sessions just because the user B has interacted with Kubeapps in between. Also we would need to persist that information somewhere and keep it up to date (again, prone to sync errors).

Correct, and I agree, but it's worth brainstorming possibilities that don't require kubeapps to have a ClusterRole to get namespaces. It'd be pretty crazy to implement the above learning behaviour mainly because it is intentionally breaking established security policies by abusing user privileges, but we need to think of possibilities. In fact, maybe we can do this more explicitly (more below).

> 
> Because of that, I would rather go with explicit requests. Considering the different cases:
> 
>     * The user A has admin permissions. It can list namespaces so we can list all of them (just as we do today) and return the ones with write permissions.

Yes, this one was never an issue. Although this scenario is often the one we use in our dev envs, we can't expect Kubeapps to be useful if all users require this for a good experience.
 
>     * The user B has permissions in the namespace `ns-b`. The token for this user is coming from a serviceaccount in that namespace. Since we can extract that information from the token, use it as the default (just as we do today).

I don't think this addresses the issue, in that it's displaying *one* namespace to which the user has access, but not the (plural) namespaces to which the user has access. I want to select between the namespaces to which I have access, not have to manually type them in, or add them


> 
>     * The user C only have permissions in the namespace `default` (or `kubeapps`). We cannot list namespaces with its token so we fallback to the well-known list of namespaces: `default` and the kubeapps installation namespace (`kubeapps` by default). Since it has permission for a well known namespace, return that in the backend.

This is similar - it still does not show me the namespaces to which I have access (other than the defaults).

> 
>     * The user D (logged using OIDC) only have permissions for the namespace `ns-d`. Since it's logged with an OIDC account we are not able to automatically discover the namespace nor it has permissions for the default namespaces. In this case, the dashboard prompt to introduce a default namespace. After checking that the user has permissions in that namespace, the choice is stored in the browser.

Ditto.

I think these are great suggestions if we're accepting that we can't provide a better experience of showing the user the namespaces which they can access, but don't know that we should give this up so easily.

> 
> 
> That way we mimic the Kubernetes behavior, if the user don't have permission to list namespaces, they will never see that list (even if they have permissions to write in several ones).

Yes, I'm just not yet convinced we should limit Kubeapps at that point. This is the main reason that OpenShift has the project resource / controller - to improve this exact situation so that users can see the list of namespaces to which they have access. Rancher solves it in a different way by having a project management API which groups namespaces into projects, so if you belong to a project, you can see the namespaces it allows you to access. It seems quite important and expected as part of the user experience (it was for me, and Rancher and OpenShift do have this).

Personally, I have no problem adding a ClusterRole limited to listing namespaces so that we can provide this functionality (as OpenShift and Rancher do). We could even do this behind a chart flag `enableGetNamespaces` which defaults to false and does not add the clusterrole, maintaining the current RBAC. We could add the endpoint which just does what you've suggested above if it cannot list namespaces, but otherwise provides the user with the list.

My bigger worry is that we apparently we'd need to then iterate and query the k8s API for each namespace to determine which namespaces a user can access - that may be a blocker (but may not - needs more thought).

**Comment by andresmgot** [comment]
> Personally, I have no problem adding a ClusterRole limited to listing namespaces so that we can provide this functionality (as OpenShift and Rancher do).

That may raise admin eyebrows. I am not sure I would add a clusterrole just for that...

> We could even do this behind a chart flag `enableGetNamespaces` which defaults to false and does not add the clusterrole, maintaining the current RBAC.

We could do so but in that case I think very few people would use it (because it's difficult to discover).

> My bigger worry is that we apparently we'd need to then iterate and query the k8s API for each namespace to determine which namespaces a user can access - that may be a blocker (but may not - needs more thought).

That wouldn't be a blocker IMO. It's just one request per user per load so unless there is a really big amount of namespaces it would be a problem (nothing to worry for the moment).

> This is the main reason that OpenShift has the project resource / controller - to improve this exact situation so that users can see the list of namespaces to which they have access. Rancher solves it in a different way by having a project management API which groups namespaces into projects, so if you belong to a project, you can see the namespaces it allows you to access.

We should be careful comparing ourselves to those projects because the scope is different. Even though you can deploy application in those, OpenShift and Rancher allows you to manage clusters with them. We are not in the cluster-management space (yet) so it's tricky.

In any case, as far as I understood, the association to namespaces is something made explicit. Another option would be for us to make it explicit as well. We can store the namespaces that a user can access (probably in the database?). That way we can list the namespaces that the user has already visited and store new ones if they explicitly type them in the selector box (and if they have access).

This wouldn't be a discovery tool though but I still doubt we need to be that discovery tool for namespaces. We would be bypassing the RBAC configuration if the user doesn't have explicit permissions to discover them.

**Comment by absoludity** [comment]
> > We could even do this behind a chart flag `enableGetNamespaces` which defaults to false and does not add the clusterrole, maintaining the current RBAC.
> 
> We could do so but in that case I think very few people would use it (because it's difficult to discover).

I don't see this as an issue, because we can test it and make sure it does indeed lead to a much better experience (being able to choose from the list of namespaces to which you have access), and then are in a much better position to decide about making it the default (to add a ClusterRole *only* for getting namespaces without no reading any resources in any namespaces), while still allowing people to install without that if they want.

> That wouldn't be a blocker IMO. It's just one request per user per load so unless there is a really big amount of namespaces it would be a problem (nothing to worry for the moment).

Great :)

> We should be careful comparing ourselves to those projects because the scope is different.

I'm not comparing Kubeapps to Openshift or Rancher because we're similar in scope (totally agree we're not), but simply because the ability for a user to see which namespaces they can access (ie. the namespace selector) is *also* a requirement (IMO) to install apps from a simple application catalog like Kubeapps. It also becomes more necessary as we consider enabling private credentials in specific sets of namespaces.


> In any case, as far as I understood, the association to namespaces is something made explicit. Another option would be for us to make it explicit as well. We can store the namespaces that a user can access (probably in the database?). That way we can list the namespaces that the user has already visited and store new ones if they explicitly type them in the selector box (and if they have access).

Yep, this is an option worth brainstorming. Let's talk more about the pros and cons of this on a call.

> 
> This wouldn't be a discovery tool though but I still doubt we need to be that discovery tool for namespaces. We would be bypassing the RBAC configuration if the user doesn't have explicit permissions to discover them.

I don't think we are. If we were listing all namespaces to users, I'd agree, but that's not what we're talking about. We're only talking about listing the namespaces to which a user has acces (can read/write secret or whatever), which they are required to know to be able to use those anyway. Asking users to instead add them manually and keep them up to date when things change manually doesn't seem like a good option, but let's talk about it.

**Comment by andresmgot** [comment]
> I don't see this as an issue, because we can test it and make sure it does indeed lead to a much better experience (being able to choose from the list of namespaces to which you have access), and then are in a much better position to decide about making it the default (to add a ClusterRole _only_ for getting namespaces without no reading any resources in any namespaces), while still allowing people to install without that if they want.

This seems like the option that both of us dislike the less so let's go for it :)
