### ISSUE TITLE
Kubeapps Dashboard does not detect Authorization Header

### ISSUE THREAD

**Issue by DasWolke** [kubeapps/kubeapps#1557]
### Description:

I'm using kubeapps with a keycloak-gatekeeper in front which adds a valid Authorization Header with a JWT to each request towards kubeapps. Unfortunately the dashboard component does not register the header and asks me to provide a token. I've checked the incoming traffic for correctness by using mitm-proxy to log the authorization header.

### Steps to reproduce the issue:

1. Setup kubeapps without an ingress
2. Setup keycloak-gatekeeper as the ingress for kubeapps
3. Try to access kubeapps
4. Notice the login screen

### Describe the results you received:

I am unable to login, but can login if I paste in the token value from the header into the token input field

### Describe the results you expected:

I should be directly logged in

### Version of Helm, Kubeapps and Kubernetes:
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        ksat            24              2020-03-02 13:44:40.091296725 +0000 UTC deployed        kubeapps-3.3.1  v1.8.1     
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
We officially support oauth2-proxy rather than keycloak-gatekeeper. You can find instructions about how to set it here:

https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md

Would you be able to switch to oauth2-proxy?

**Comment by DasWolke** [comment]
Unfortunately not, it causes even more issues for me. The thing is that the proxy works great with kubeapps v1.5.0, the current kubernetes dashboard and a couple other apps. Only kubeapps 1.8.x is causing problems for me.

**Comment by absoludity** [comment]
I haven't retried keycloak-gatekeeper since we switched (and we switched because gatekeeper makes assumptions about the format of the access token which I documented for them at https://issues.redhat.com/browse/KEYCLOAK-11581 ), but when we switched I also updated to use an http-only cookie (ie. js cannot access the cookie, so more secure). This is probably what is causing the change in behaviour you're seeing, as older Kubeapps (1.5) knew about the cookie and read the JWT to explicitly set the Authorization header when sending with requests (insecure), where as with 1.8 kubeapps can no longer even see the cookie so does not set any Authorization header itself.

Instead, Kubeapps relies on the proxy to set an encrypted http-only cookie when authenticating, and the browser will automatically include that cookie when it queries kubeapps from that point on - kubeapps doesn't know about it - and so it relies on the proxy decrypting and converting the cookie to the correct JWT token as a bearer token and setting the Authorization header when passing through to the upstream k8s API server.

So, in practise, when you finish authenticating, kubeapps just checks to see if it can access `/api/kube`, which you can see with the highlighted request here:
![kubeapps-auth-cookie](https://user-images.githubusercontent.com/497518/75945286-e1656480-5eed-11ea-9f09-0fd4c7666ef0.png)
Note that the request header includes the cookie set by the proxy (the name of the cookie is irrelevant as kubeapps doesn't even see it).

I'm guessing that request is failing for you? Can you verify that:

1. the same request to `/api/kube` is failing as we expect and that it is including whatever cookie gatekeeper is setting, and
2. gatekeeper is configured to convert that to a jwt when passing requests with the cookie through to the backend? For oauth2_proxy it's the `-pass-authorization-header` which ensures the OIDC IDToken is passed upstream via Authorization Bearer header (see [docs](https://pusher.github.io/oauth2_proxy/configuration#command-line-options)). For gatekeeper, it looks like the `--enable-authorization-header` is true by default and so should be doing this already ([docs](https://www.keycloak.org/docs/latest/securing_apps/index.html#upstream-headers)), but perhaps you can use MITM to verify that the token being sent upstream to kubeapps is not the correct one.

Hope that helps!

**Comment by DasWolke** [comment]
Hey there,
thanks for your help so far!

Accessing the API directly via my-kubeapps-host.com/api/kube works fine and I get no error messages whatsoever, when copying the jwt token from the authorization header and pasting it into the token field of kubeapps, that works too, so the header value should be fine right ? Could it be an issue for Kubeapps that the Value of the Auth Header is around 3700 characters long ? Or that kubeapps does not register it ? Anything config wise which has to be configured ?

The request you mentioned is not made by kubeapps without me pasting in a token before. So I basically can't make it past the inital login window, without pasting in a token.

**Comment by absoludity** [comment]
Thanks for the info. So yes, it sounds like you're getting a valid token, but a few things aren't clear.

> Accessing the API directly via my-kubeapps-host.com/api/kube works fine and I get no error messages whatsoever,

As in, you can see the cookie (whether it's http-only or not) being set, so that when you request /api/kube it gets included with the request?

> when copying the jwt token from the authorization header and pasting it into the token field of kubeapps, that works too, so the header value should be fine right ?

I'm a little confused at this point, because Kubeapps doesn't add the jwt token to an authorization header unless you're using the normal token authentication, so I wonder if something is being confused? For the oidc/oauth2 integration, Kubeapps just assumes whatever cookie is set by the auth proxy will be used for all requests to /api/kube and leaves the auth proxy to insert the jwt auth token in the header of the upstream request, as I mentioned above. Try deleting all browser storage (cookies and anything) for your domain, before trying the oidc login... I'm keen to know how you're seeing the authorization header. Ah - unless you mean when you use MITM to view the upstream request, in which case, OK, yes that would mean the header value is fine.


> Could it be an issue for Kubeapps that the Value of the Auth Header is around 3700 characters long ?

I don't think so, as Kubeapps doesn't set any auth header in this mode, unless it's still got the token in its storage from the non-oidc login and is sending that.

> Or that kubeapps does not register it ? Anything config wise which has to be configured ?

So if you are hitting /login, being redirected to gatekeeper, redirected back to /login, then the only thing which stops Kubeapps from checking a request to /api/kube is if the [`oauthLoginURI` config option isn't set](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/LoginForm/LoginForm.tsx#L26), but if that was not set, I don't think you'd be redirected to gatekeeper to login in the first place. But just to be sure, here's a screenshot showing the request you can look for which displays the config, including this option:

![oauthLoginURI-set](https://user-images.githubusercontent.com/497518/76037061-f1d31900-5f99-11ea-9688-987187bf1c37.png)

Either way, can you pls screenshot your browser after the following:
1. Remove any local storage for the domain (or open a new private tab)
2. open the dev console to show the network requests
3. Go to Kubeapps so it redirects you to Gatekeeper, login, and get redirected back to Kubeapps then screenshot your browser window showing the contents of both the normal pane and the requests? That'd help me further.

Otherwise I'll try to put some time aside to setup with gatekeeper, but that could be a while.



https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/LoginForm/LoginForm.tsx#L26

**Comment by plnordquist** [comment]
I ran into this issue as well when trying to run an oauth2-proxy outside of the kubeapps helm chart.  The dashboard configmap contains a authProxyEnabled flag inside the config.json that I had to enable so the dashboard would login properly without sending my browser to the login page and prompting for a token.

**Comment by absoludity** [comment]
Thanks @plnordquist - that's true, if the `authProxyEnabled` flag is not set, the [oauthLoginURI value is blanked out](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts#L17). @DasWolke Can you confirm if you update the configmap for the dashboard config, setting `authProxyEnabled` to true, whether the login then succeeds?

That indeed looks like an issue, that Kubeapps assumes if its own auth proxy is not enabled then it incorrectly assumes that the oauth Login URI should not be set (I have a memory there was a reason for it, but we need to work around that).

**Comment by DasWolke** [comment]
Hey there,

again thanks for the help so far, I've switched on the config setting for the authProxy to true again today, applied the configmap and it worked... Which was quite weird because I had the flag enabled in the past, but turned it off for testing..

Anyways thank you very much for the help, my problem is solved :-)
