### ISSUE TITLE
Upgrade button should have the same action as the Helm upgrade

### ISSUE THREAD

**Issue by geekyfox90** [kubeapps/kubeapps#1563]
### Description:

When upgrading a release, it doesn't pull the last docker image as it should do

### Steps to reproduce the issue:

1. Deploy a helm chart
2. Push a new docker image with tag latest
3. Upgrade

### Describe the results you received:

Nothing happens, the helm release is not updated with the new docker image

### Describe the results you expected:

The helm release should be updated with the new docker image pushed

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

```

- Output of `helm list <kubeapps-release-name>`:

```
NAME    	REVISION	UPDATED                 	STATUS  	CHART         	APP VERSION	NAMESPACE
kubeapps	1       	Thu Mar  5 14:32:53 2020	DEPLOYED	kubeapps-3.4.3	v1.8.2     	kubeapp
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hi @geekyfox90,

That's an expected behavior (it doesn't matter if you use Kubeapps or Helm directly). If you upgrade an application and the template of the Deployment that you want to re-pull doesn't change, nothing will change. Since the deployment is the same, Kubernetes won't create a new pod with the new image.

Two possibilities:
 - Don't use `latest`. Usage of `latest` in production is discouraged.
 - Add an annotation to your Deployment template with some content that vary, like the date or a random number. With this, every time you upgrade, this annotation will be different and a new pod will be created.

What confuses me is that you are seeing a different behavior with Helm. Is there any chart we can deploy to reproduce your issue?

**Comment by geekyfox90** [comment]
Yes that's correct, thanks for your answer
