### ISSUE TITLE
The port-forward port in getting-started.md should be 8080:8080

### ISSUE THREAD

**Issue by GodQ** [kubeapps/kubeapps#1585]
Current doc is:
`echo "Visit http://127.0.0.1:8080 in your browser to access the Kubeapps Dashboard"
kubectl port-forward -n kubeapps svc/kubeapps 8080:80`

But the port should be 8080:8080
`echo "Visit http://127.0.0.1:8080 in your browser to access the Kubeapps Dashboard"
kubectl port-forward -n kubeapps svc/kubeapps 8080:8080`

**Comment by absoludity** [comment]
Hi there @GodQ. It's not clear to me why you think the service port is `8080` rather than `80`? If you take a look at the service to which we're port-forwarding:

```
~$ kubectl -n kubeapps get services kubeapps
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
kubeapps   ClusterIP   10.63.249.167   <none>        80/TCP    116d
```
you see it's port 80. So it works if we port-forward the services port 80:
```
~$ kubectl port-forward -n kubeapps svc/kubeapps 8080:80
Forwarding from 127.0.0.1:8080 -> 3000
```

but not if we try to forward to the services port 8080 as the service doesn't expose that:
```
~$ kubectl port-forward -n kubeapps svc/kubeapps 8080:8080
error: Service kubeapps does not have a service port 8080
```

The pods for the related deployment do run on 8080, so it works if you port-forward that instead?
```
~$ kubectl port-forward -n kubeapps deployment/kubeapps 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
```

Maybe that's what you were doing instead?

**Comment by GodQ** [comment]
You are right. What I use is pod name. I will close this ticket
