### ISSUE TITLE
Fail to deploy gogs, getting error - unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by txconsole** [kubeapps/kubeapps#1653]
### Description:

Getting the error as stated below for gogs deployment on kubernetes cluster

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"`

### Steps to reproduce the issue:

run helm deploy command : 

`$ helm install incubator/gogs --generate-name`

### Describe the results you received:

deployment failed

### Describe the results you expected:

deployment to succeed.
### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+vmware.2", GitCommit:"ecfc861bf28fc0a7684f2341a5ca74b75c010b20", GitTreeState:"clean", BuildDate:"2020-04-01T04:34:44Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andresmgot** [comment]
Hello @txconsole,

This is an issue with the `gogs` chart, since Kubernetes 1.16, the API version `extensions/v1beta1` for Deployments has been removed, it should use `apps/v1` instead. You would need to contact charts maintainer (even though I see that the chart has not been updated for a while):

https://github.com/helm/charts/blob/master/incubator/gogs/OWNERS

Let me close this issue because it's not directly related to Kubeapps, please reopen it if you still think that there is something we should take a look into.
