### ISSUE TITLE
YAMLException: unknown tag !<tag:yaml.org,2002:string>

### ISSUE THREAD

**Issue by frankvollenweider** [kubeapps/kubeapps#1725]
### Description:

I deployed pgadmin4 (Repository: https://helm.runix.net) through kubeapps into my gke-cluster. The result of this was the message "Sorry! Something went wrong." But the deployment was successfull and I can use this application to access my postgres database. Now when I click on the installed application in the applications view of kubeapps, the same happens again: "Sorry! Something went wrong.".

I attached the output of the javascript console: [console-log.log](https://github.com/kubeapps/kubeapps/files/4603454/console-log.log
).

### Steps to reproduce the issue:

1. Install pgadmin4 from repository https://helm.runix.net
2. The error "Sorry! Something went wrong." is shown
3. Each time you click on the application the same error happens.

### Describe the results you received:

"Sorry! Something went wrong."

### Describe the results you expected:

Kubeapps shows the details of the deployed application.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `helm list <kubeapps-release-name>`:

```
kubeapps        kubeapps        1               2020-05-08 21:11:29.5751914 +0200 CEST  deployed        kubeapps-3.6.0 v1.10.0
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
I haven't tried to reproduce this, but it looks like it may be different from the general "something went wrong" issues with missing chart metadata in #1620

**Comment by andresmgot** [comment]
Yes, the issue is reproducible. The problem is that the manifest is using YAML type casting: https://github.com/yaml/YAML2/wiki/Type-casting

This is the conflicting piece:

```yaml
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: !!string False
```

This seems to be something that is not supported in `js-yaml` (at least I haven't found any reference to that in their repository). @frankvollenweider I would recommend the chart maintainers (if you have contact with them) to use Helm templating mechanism to convert that value to a string rather than using type casting if possible.

In any case, it seems that this is something that can be done with the other `yaml` library. It only throws a warning:

```
> const yaml = require("yaml");
undefined

> yaml.parse("foo: !!string false")
{ foo: 'false' }
> (node:4083) YAMLWarning: The tag tag:yaml.org,2002:string is unavailable, falling back to tag:yaml.org,2002:str

```

So we can use that library instead if we don't find any other issue.

**Comment by andresmgot** [comment]
@frankvollenweider FYI we have merged the fix so we don't require changes in the chart, it will be available in the next release! Thanks for reporting.
