### ISSUE TITLE
What is the meaning of chart.repo.namespace

### ISSUE THREAD

**Issue by shenyiling** [kubeapps/kubeapps#1732]
When i switched version of chart at route`/ns/:namespace/charts/:repo/:id`, `/ns/:namespace/apps/new/:repo/:id/versions/:version`, i always get `not found` error. 
![image](https://user-images.githubusercontent.com/25818722/81635553-09b89480-9444-11ea-98aa-8c1c8f4c9eec.png)

I looked at the chart collection data in MongoDB，found that every chart has `repo.namespace` field.But I do n’t know what it means, can anyone explain it to me?

**Comment by shenyiling** [comment]
help.I am new to k8s and helm.

**Comment by andresmgot** [comment]
Hello,

Since Kubeapps v1.10.0, app repositories are namespaced so people can share a Kubeapps instance but have their own private app repositories in their namespaces. App repositories in the namespace `foo` are not visible in the namespace `bar` and vice versa. The only special case is the `kubeapps` namespace, this namespace is treated as global and app repositories stored there will be available for everyone. You can read more about this here: https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md#per-namespace-app-repositories

Having said that, you should not see "not found" errors if you have upgraded your application. Maybe it's in an inconsistent state? It seems that your database is properly populated, maybe you are using an old image of the dashboard? Or you are using old routes somewhere?

**Comment by shenyiling** [comment]
@andresmgot Thx for your reply!I cloned your project a few days ago, and did some code-fix for my question(I'm not sure if it's right).For example.i have fixed the [line](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx#L155) to `/ns/${this.props.namespace}/apps/${isGlobal ? "new-from-global" : "new"}/${ this.props.chartID }/versions/${e.currentTarget.value}` to get right version of chart.Is it right？And I am now wondering whether kubeapps-namesapce and k8s-namespace are related？ (My english is a bit bad)

**Comment by shenyiling** [comment]
I also modified this [line](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/ChartView/ChartVersionsList.tsx#L30).Before modification, it was page not found.After fixed, it also nav to ChartView(just switched over a certain version of readme).

**Comment by andresmgot** [comment]
Hi @shenyiling, I am not sure what you are trying to achieve but you don't need to modify the application routes. Those routes are used to extract the parameters needed to request the different charts and applications through the API.
