### ISSUE TITLE
Support to use an existing Kubeconfig to authenticate

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1736]
### Description:

The current two methods to authenticate are:

 - Using a serviceaccount token
 - Using OIDC

In other environments like the Kubernetes Dashboard, it's also possible to authenticate using the user Kubeconfig:

![Screenshot from 2020-05-13 12-16-14](https://user-images.githubusercontent.com/4025665/81800779-ad24aa80-9513-11ea-959d-9eaad6c584dd.png)

This approach may be more convenient for people that are not given a serviceaccount and for clusters that are not configured to use OIDC. 

In any case, for security reasons, it's not possible to authenticate using the private key and certificate data (which is a common authentication mechanism) so I am not sure if it's something that would really help or confuse people (see this related issue: https://github.com/kubernetes/dashboard/issues/2474)

Thoughts? cc/ @absoludity @danoo

**Comment by absoludity** [comment]
> so I am not sure if it's something that would really help or confuse people (see this related issue: [kubernetes/dashboard#2474](https://github.com/kubernetes/dashboard/issues/2474))

+1 . If you follow the discussion on that kubernetes dashboard issue, it is repeated many times that the reason it does not work using the private key and certificate data is explicitly so that people won't upload secret data which should never be leaving their computer.

I'm very keen, wherever possible, to encourage people to use the Kubernetes support for single-signon options, so that people can login using their company's SSO service (which generates short-lived tokens for use, which is much safer), rather than using permanent security credentials mean for either other secure services (a service token) or a user's CLI (the kubeconfig file).

Yes, we could similarly only support kubeconfig files which have renewable tokens or similar, but it could be confusing. Perhaps, one option would be to enable this as a plugin which is off by default but people can switch on at their own risk?

**Comment by absoludity** [comment]
Closing in favour of sticking to SSO setups.
