### ISSUE TITLE
Charts with slashes (/) in the name cannot be rendered

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1811]
### Description:

We noticed that if a chart contains a slash in the name (e.g. `library/kubeapps`), the chart fails to be rendered, giving a 404:

![Screenshot from 2020-06-22 12-07-33](https://user-images.githubusercontent.com/4025665/85275961-6070af80-b481-11ea-9be9-cba7c08e6c9e.png)
![Screenshot from 2020-06-22 12-07-57](https://user-images.githubusercontent.com/4025665/85275960-5fd81900-b481-11ea-93a0-1b60e097473b.png)

This is because `library/` gets interpreted as a subpath.

### Steps to reproduce the issue:

1. Create Harbor instance
2. Upload a chart to the default repo (`library`)
3. Import the default repo to Kubeapps.

### Describe the results you expected:

To properly show the catalog, escaping the slash.

**Comment by Vizzard** [comment]
I think this is the reason why https://chartcenter.io public repo cannot be used in Kubeapps.
Same 404 error for every helm chart in `https://repo.chartcenter.io/` repository. 
Great that it is in the next milestone!

**Comment by antgamdia** [comment]
This issue IMO, unfortunately, not only applies to the UI, but the entire Kubeapps services:

- [x] asset-syncer should handle the tarball unpacking when the chart name contains a `/` character.
- [ ] dashboard should properly encode the `/` character in a chart name as `%2F` so that the router is able to understand it's a path param.
- [ ] assetsvc router should NOT prematurely decode the`%2F` so that it can be passed directly to the corresponding methods.
- [ ] nginx shoud NOT decode `%2F`when proxy_pass. Note that decoding it's the default behavior and some changes have to be made ([more info](https://stackoverflow.com/questions/28684300/nginx-pass-proxy-subdirectory-without-url-decoding/37584637#37584637))

Perhaps there are more components or parts affected by this issue, but, as for now, this is all I could get.
I'm working on solving each item.
