### ISSUE TITLE
REST/RPC API documentation

### ISSUE THREAD

**Issue by rarick** [kubeapps/kubeapps#1860]
I was hoping to put a webhook on Harbor which would refresh the apprepositories when a chart was added/updated/deleted, but I was unable to locate documentation on what function calls were available.

Is there documentation anywhere?

**Comment by andresmgot** [comment]
Hi @rarick, so far, the API calls in Kubeapps have been internal-only and likely to change (that's why it's not documented). Once we have something more stable (for example now we are changing the paths again to add support for multiple clusters) we can document and expose it. 

For your use case, you may be able to use the K8s API. Note that the "Refresh" button in Kubeapps does that. If you want to do that, you can check the "Network" tab of the browser console and check the request made when clicking on Refresh, for v1.10.2 it's something like this:

```
curl 'https://kubeapps-url/api/clusters/default/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories/bitnami' \
  -X 'PUT' \
  -H 'content-type: application/json;charset=UTF-8' \
  --data-binary '{"apiVersion":"kubeapps.com/v1alpha1","kind":"AppRepository","metadata":{"annotations":{"helm.sh/hook":"post-install","helm.sh/hook-weight":"10"},"creationTimestamp":"2020-05-06T13:40:22Z","generation":4,"labels":{"app":"kubeapps-internal-apprepository-controller","chart":"kubeapps-3.6.0","heritage":"Helm","release":"kubeapps"},"name":"bitnami","namespace":"kubeapps","resourceVersion":"23122945","selfLink":"/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories/bitnami","uid":"0fda4e20-76e8-4dee-a0dc-8d08724e12e2"},"spec":{"resyncRequests":4,"type":"helm","url":"https://charts.bitnami.com/bitnami"}}' \
```

Note that the `resyncRequest` field needs to change between calls since that's what trigger the update.

**Comment by rarick** [comment]
@andresmgot Good to know, thanks for your help
