### ISSUE TITLE
Namespace administrators cannnot deploy their own release because chartmuseum is no longer shared

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubeapps/kubeapps#1871]
### Description:

When deploying helm chart, cannot see catalog, error with "Unable to fetch catalog, There was an error fetching the catalog. Please choose a namespace above to which you have access."
In my scene, people in company share one chartmuseum, but kubeapps now only support Per Namespace App Repositories, I can't add repositories in all namespace(500), and namespace administrators don't have privileges to fetch catalog from other namespace's app repositories.
So they cannot deploy new helm chart after upgradeing.

### Steps to reproduce the issue:

1. Deploy the latest version kubeapps with helm3
2. add app Repositories in a namespace called "All Namespaces"
3. use a namespace administrator's kubernetes token to login
4. try to deploy a app and error with "Unable to fetch catalog, There was an error fetching the catalog. Please choose a namespace above to which you have access" or "Manage your Helm chart repositories in Kubeapps by visiting the App repositories configuration page"

### Describe the results you received:

"Unable to fetch catalog, There was an error fetching the catalog. Please choose a namespace above to which you have access" or "Manage your Helm chart repositories in Kubeapps by visiting the App repositories configuration page"

### Describe the results you expected:

Just let namespace administrators can refresh the global chartmuseum and deploy/upgrade their own chart successfully. 

### Additional information you deem important (e.g. issue happens only occasionally):

Maybe I need to add some rbac privileges to namespace administrators, in order they can see "All Namespaces"'s catalog?
Or If there have a version which both support helm3 and global app repositories like before? Please give my some suggestion, thanks.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
helm3 version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list <kubeapps-release-name>`:

```
helm3 ls
NAME         	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART         	APP VERSION
kubeapps-test	ci-cd    	5       	2020-07-17 14:13:26.99276512 +0800 CST	deployed	kubeapps-3.8.0	v1.10.2
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Hi there @ZhangSIming-blyq . I don't think you are missing any RBAC, but perhaps have simply not selected the appropriate namespace? That is, you have correctly added the global repositories, and your namespace administrator should be able to view that catalog after selecting their namespace (Kubeapps shows the catalog of charts that the current user can deploy to the current namespace, which could be both global charts and namespace-specific ones).

I can only reproduce your issue if I leave the namespace selector on "All namespaces" and try to view the catalog as a "namespace administrator".

So, please try:
 1. Follow your first 3 steps as above, and then,
 2. After logging in as a particular namespace administrator, select the namespace which that user administers,
 3. Click on "Catalog"

This should then display all charts from the global app repository that you've added (ie. all the charts available for install by the current user in the currently selected namespace).

Longer term, I would like to remove the "All Namespaces" option unless a user has global privileges, which may avoid this confusion.

Let me know if that does not solve your problem.

**Comment by ZhangSIming-blyq** [comment]
Thanks for your reply, but still see nothing(just because the namespace don't config any app repo). 
![image](https://user-images.githubusercontent.com/58658883/87905051-49c67400-ca92-11ea-978f-6e5544ab6ecc.png)
![image](https://user-images.githubusercontent.com/58658883/87905105-5f3b9e00-ca92-11ea-8830-07f82d15becd.png)
![image](https://user-images.githubusercontent.com/58658883/87905188-8db97900-ca92-11ea-9261-6761cb8d1965.png)

1.Maybe the way I create global namespace is wrong? I noticed it show ci-cd(The namespace I deployed kubeapps) in global app repository?
2.And I can you give some best practise for per namespace per chartmuseum?(It's that designed for deploy chartmuseum in every namespace? That's terrify me)

**Comment by absoludity** [comment]
> Thanks for your reply, but still see nothing(just because the namespace don't config any app repo).

It's not because the namespace doesn't have a specific app repo - global app repositories are visible in the catalog of any namespace. I think the issue is somewhere else....

> 1.Maybe the way I create global namespace is wrong? I noticed it show ci-cd(The namespace I deployed kubeapps) in "global app repository"?

You have created it correctly - a global app repository is actually just one which is added to the kubeapps installation namespace, but this might give us more info about the issue. I tried again to reproduce your issue, this time by installing Kubeapps into a "ci-cd" namespace. When viewing app repositories for all namespaces (as a kubeapps admin), I see a similar view to you:

![1871-admin-view](https://user-images.githubusercontent.com/497518/87908127-438fc200-caa9-11ea-8233-c0101511f0a8.png)

If I then login as a non-kubeapps-admin, I can reproduce your original issue if I try to view the catalog while "All namespaces" is selected:

![1871-user-cant-see-catalog-when-all-namespaces-selected](https://user-images.githubusercontent.com/497518/87908198-5d310980-caa9-11ea-82d4-7f3950a56d65.png)

But if I choose a namespace to which my user has access, the charts from the global repos are all presented as expected:
![1871-3-user-can-see-catalog-when-specific-namespace-selected](https://user-images.githubusercontent.com/497518/87908258-71750680-caa9-11ea-94d0-5b84a1ba42c1.png)

So I suspect that for some reason, your charts have not been imported correctly (but I am not certain). To test, can you show the tail of the logs for one of the `apprepo-ci-cd-sync-*` jobs in your `ci-cd` namespace.  For example, in my case, I ca see:
```
kubectl -n ci-cd logs --tail 10 apprepo-ci-cd-sync-bitnami-94dnf-rxnff
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=1.0.2
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.8
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.7
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.9
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.5
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.6
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.4
time="2020-07-20T06:50:51Z" level=info msg="values.schema.json not found" name=parse version=0.3.3
time="2020-07-20T06:50:51Z" level=info msg="Stored repository update in cache" url="https://charts.bitnami.com/bitnami"
time="2020-07-20T06:50:51Z" level=info msg="Successfully added the chart repository bitnami to database"
```


Another way to test is to verify whether you see the charts when logged in as your kubeapps administrator, viewing the catalog for any namespace (or even the ci-cd namespace).

> 2.And I can you give some best practise for per namespace per chartmuseum?(Is that designed for deploy chartmuseum in every namespace? That's terrify me)

Heh, no... you don't need to install chartmuseum for each namespace. The way you are doing it (ie. a single chart museum, and a single global AppRepository definition for kubeapps) is correct, there is just something stopping the catalog from being populated. Hopefully the above logs will tell us more.

**Comment by ZhangSIming-blyq** [comment]
Here is the log of apprepo-ci-cd-sync-* jobs in my ci-cd namespace:(please ignore icon error)
```shell
time="2020-07-20T15:18:11+08:00" level=error msg="failed to import icon" error="404 https://docs.traefik.io/img/traefik.logo.png" name=traefik-prod-aws-nx
time="2020-07-20T15:18:11+08:00" level=info msg="icon not found" name=policy-brain-search-gate
time="2020-07-20T15:18:11+08:00" level=info msg="icon not found" name=prophet-risk-aggregation
time="2020-07-20T15:18:12+08:00" level=error msg="failed to import icon" error="404 https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-2.0.334.png" name=phpmyadmin-pbsql
time="2020-07-20T15:18:13+08:00" level=error msg="failed to import icon" error="404 https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-2.0.334.png" name=phpmyadmin-policy-brain
time="2020-07-20T15:18:22+08:00" level=info msg="Stored repository update in cache" url="https://chartmuseum.shannonai.com/"
time="2020-07-20T15:18:22+08:00" level=info msg="Successfully added the chart repository shannonai to database"
```

And kubernetes administrator can see catalog and deploy successfully:
![image](https://user-images.githubusercontent.com/58658883/87910513-b9416100-ca9c-11ea-9bb1-202b5f18a0d4.png)

But when I switch back to namespace "inf-test" administrator, when don't choose correctly namespace it shows:
![image](https://user-images.githubusercontent.com/58658883/87910746-189f7100-ca9d-11ea-8d61-5a96ad0b734d.png)
Change namespace to "inf-test", it shows:
![image](https://user-images.githubusercontent.com/58658883/87910815-37056c80-ca9d-11ea-9ad9-e5ce34f92745.png)
The result is different to yours. That confused me.

1.Can I have a look have your namespace administrator's rbac(In helm2 kubeapps version, my rbac works for about 1years or more).
2.By the way, If I only have one app repo in "All Namespaces", is that mean namespace administrator must first click "All Namespaces" for refreshing chart, and then back to their own namespace to deploy the service?
Please let me know if I miss something, thanks.

**Comment by absoludity** [comment]
> The result is different to yours. That confused me.

Me too :) I am keen to understand why. Can you please also paste a screenshot of the request to `/api/assetsvc/v1/ns/inf-test/charts` including its response or any other relevant info, from the browser debugger? Thanks! Based on the UI you show, I expect it'll just be an empty result and not tell us much, rather than an error code, but worth checking.

So the backend database is being populated, the catalog is also visible for your admin user (though, can you verify when you choose other namespaces, such as `inf-test` when still logged in as your kubeapps admin, that you see the catalog too?). 

> 
> 1.Can I have a look have your namespace administrator's rbac(In helm2 kubeapps version, my rbac works for about 1years or more).

Yes, there have been rbac changes recently. I am setting up my development environment using the scripts in master, so you can see the [RBAC added to my test cluster](https://github.com/kubeapps/kubeapps/blob/master/script/cluster-kind.mk#L16) as well as the [config used to deploy kubeapps](https://github.com/kubeapps/kubeapps/blob/master/script/deploy-dev.mk#L20) (or even try them locally yourself). It may be an RBAC difference as you suggest, I'll look more closely tomorrow.

> 2.By the way, If I only have one global app repo in "All Namespaces", is that mean namespace administrator must first click "All Namespaces" for refreshing chart, and then back to their own namespace to deploy the service?

No - charts are refreshed automatically every 10mins by default (you will see a cronjob in your `ci-cd` namespace for each repository). So nothing should be required for refreshing.

> Please let me know if I miss something, thanks.

I can't see anything that you're doing wrong - I think there's a bug there somewhere that I just can't yet reproduce :)

**Comment by ZhangSIming-blyq** [comment]
Response of assetsvc:
```shell
curl 172.60.172.54:8080/api/assetsvc/v1/ns/inf-test/charts
404 page not found
``` 
> So the backend database is being populated, the catalog is also visible for your admin user (though, can you verify when you choose other namespaces, such as inf-test when still logged in as your kubeapps admin, that you see the catalog too?

Ok, kubernetes admin token can see catalog when selecting inf-test:
![image](https://user-images.githubusercontent.com/58658883/87914585-6cad5400-caa3-11ea-8346-63a7575eb568.png)

I'll try your rbac, and come back later, thanks.

**Comment by ZhangSIming-blyq** [comment]
Finally I found the point, it is at rbac:
```shell
$ sed -n '15,22p' clusterrole.yaml
......
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
......
```
When doing a rbac for namespace administrator, **MUST give them "get secret" and "watch secret" privilege at cluser scope**, or they will not be able to see catalog synced by global app repo.(In my situation, I only gave the ability to "list secret") 
![image](https://user-images.githubusercontent.com/58658883/87921770-9e2b1d00-caad-11ea-9f4d-1ef1e810c501.png)

Now it's all right, this error caused by rbac authorization never found in old version(namespace shared app repo), put it here for those who may need it.
Sincerely thank @absoludity for your help.

**Comment by absoludity** [comment]
Great, thanks for your investigation! Yes, we add a rolebinding in the namespace for the global k8s edit role, so that secrets can be read in the namespace. I'm still a little confused in that I would have expected the response back from the asset service request to be a 401 rather than 404, but glad you've got it working.
