### ISSUE TITLE
Support running Kubeapps on a TKG Management Cluster

### ISSUE THREAD

**Issue by vrabbi** [kubeapps/kubeapps#1942]
### Description:

After discussing at length the multi cluster support and adapting it to TKG with @absoludity i believe there is still one key functionality that should be added in the multi cluster area to fully support TKG.

In TKG, the management Cluster is not OIDC enabled, however the Workload Clusters are.
Within the TKG Management Cluster it is suggested to run shared services that provide a unified service toolkit for the workload clusters. this currently is scoped OOTB to include Dex and Harbor (if using TKG+ licensing).

Adding support for running in a non OIDC enabled cluster would be a huge advantage as that would allow kubeapps to follow the TKG methodology and architecture.

### Additional information you deem important (e.g. issue happens only occasionally):

possible solutions i have thought of are:
#### option 1 ####
add 2 additional variables to the helm chart:
1. disableLocalCluster - a boolean that defaults to false and can be set in conjunction with configuring additional Clusters and adding the defaultCluster variable.
2. defaultCluster - the name of the cluster from the additional clusters that should be used as the default cluster when logging in.

#### option 2 ####
add 1 additonal variable to the helm chart:
1. disableLocalCluster - a boolean disabling the local cluster.
in this option there would be no defaultCluster rather there would be a homepage indicating the user must select a cluster. from the context list.

#### Pros and Cons ####
option 1 is probably easier to implement but has 2 main drawbacks:
1. As workload clusters are dynamic and come up and down in certain environments, having a default cluster may prove challenging for some customers.
2. overall in a multi cluster solution you run the risk of customers provisioning charts to the wrong cluster

option 2 is probaly harder to implement but has a few key benefits:
1. makes the user select the cluster which provides an extra security guard around users provisioning charts in the wrong cluster
2. allows kubeapps to be deployed in the management cluster before any additional clusters are deployed and allows them to be more dynamic without making many changes to the kubeapps deployment. (only need to add the scopes and the cluster details in the additional clusters array)

**Comment by absoludity** [comment]
So a couple of thoughts on this:

I've left a bit of room to update the configuration semantics, in particular, I don't know that we need a `disableLocalCluster` option at all if we instead update the `clusters` option to be definitive, that is, if we assume that it defines all the clusters available as targets for installations - including the cluster on which Kubeapps is installed.

Including the cluster on which Kubeapps is installed is just a cluster without an `apiServiceURL`, so for example:
```
clusters:
  - name: default
  - name: additional-1
    apiServiceURL: https://additinoal-1.example.com/
```

ensures Kubeapps can target the cluster on which Kubeapps is installed, using the name `default`, as well as the `additional-1` cluster. This also solves two other issues:

- you can name the cluster on which Kubeapps is installed whatever you like (#1943)
- Kubeapps can assume that the first cluster in the list of clusters (since it is definitive) should be the cluster to which people target by default after the initial login.

We could still choose to have a user select their default cluster on login if we wanted, but it can be additional.

Also, we can transition to this quite easily with the following rules:

- If clusters is an empty list, we assume a single target cluster (the one on which Kubeapps is installed)  named `default`
- If at least one cluster is defined, then the list of clusters is definitive
- If a cluster does not define an `apiServiceURL` then we assume the cluster on which Kubeapps is deployed. Defining more than one cluster without an `apiServiceURL` is a config error (chart will fail).

Thoughts?

**Comment by vrabbi** [comment]
Sounds good to me. Making the list definitive is definitely a good idea. 
I think the one question that will need to be checked with a multi cluster env where we define a default cluster (whichever cluster is first in the list) is:
What will happen if a user does not have a role binding in that specific cluster but does in other clusters? Will the user be thrown out back to the login screen or will it just not allow him to deploy?
