### ISSUE TITLE
Apps installed from a global repository cannot be upgraded

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#1980]
### Description:

When trying to upgrade an app installed from a global repository, this error comes up:

![image](https://user-images.githubusercontent.com/4025665/91588015-d6990300-e957-11ea-97b3-cee67ed695fd.png)

### Steps to reproduce the issue:

1. Install kubeapps, by default
2. Install Apache in the `default` namespace
3. Try to upgrade

### Additional information you deem important (e.g. issue happens only occasionally):

There are two issues here:

 - The dashboard is not able to auto-discover the update info. This is because we are only asking for charts in the app namespace.
 - The form that allows to select the source of the application (SelectRepoForm) is no longer working (since we are only requesting app repos within the app namespace).

**Comment by absoludity** [comment]
So there are a few questions that I had when I read this, I'll include the answers I've found as well :)

1) Why did CI not pick this up, given that we have an explicit test for upgrading apache (both for a normal repo and a private app repo)

The reason is our integration tests didn't find this issues was that they were testing the upgrade in the `kubeapps` namespace. We use service accounts for authn/authz which are created in the kubeapps namespace. The integration test for the [`upgrade.js` test starts at /#/login](https://github.com/kubeapps/kubeapps/blob/v1.11.2/integration/use-cases/upgrade.js#L2) and so, since a specific namespace is not included in the initial route, Kubeapps defaults to the namespace of the service account, ie., `kubeapps`. So the `upgrade.js` test does not trigger the issue in the first place, since the request for charts in the `kubeapps` namespace includes the required data.

2) Why did no one report this earlier?

It turns out they did. One user, @lingsamuel,  who happened to be using the development images had reported this exact issue in #1845 before it was released. Not only did they report it, but they pointed out the actual cause and solution (that `getPaginatedChartList` had been updated to include global charts, but `getChartsWithFilters` had not, though it should have been).

> There are two issues here:
> 
>     * The dashboard is not able to auto-discover the update info. This is because we are only asking for charts in the app namespace.
> 
>     * The form that allows to select the source of the application (SelectRepoForm) is no longer working (since we are only requesting app repos within the app namespace).

With the change suggested above (updating `getChartsWithFilters()` to also include global namespaces) the dashboard just works, since data for charts specific to the namespace, as well as global charts, are returned. See #1983 for details (currently only pg driver fixed).
