### ISSUE TITLE
apprepository-jobs-postupgrade needing high privileges to successfully complete

### ISSUE THREAD

**Issue by f-guichard** [kubeapps/kubeapps#2008]
This is more a question than a feature request for the time being (as we think, after digging, we may have misunderstood #1053 #1255 #1505 which were closed but not exactly related to our issue)

### Description:

apprepository-jobs-postupgrade pod seems to need a specific psp for complete execution.

### Steps to reproduce the issue:

1. Activate privilege drops in values.yaml :
```
vi values.yaml
643 ## Pod Security Context
644 ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
645 ##
646 securityContext:
647   enabled: true
648   runAsUser: 1001
649   fsGroup: 1001
```
2. Install Kubeapps
``helm upgrade --install kubeapps --namespace kubeapps . --set useHelm3=true``  

Wait 1-2 min.

3. Check apprepository-job-postupgrade pod status
``kubectl get po | grep upgrade; kubectl get events | grep upgrade``

### Describe the results you received:

Got "classic" **CreateContainerConfigError** for _kubeapps-internal-apprepository-job-postupgrade-l5dnn_
  -> ``container has runAsNonRoot and image will run as root``

and a `kubectl get po kubeapps-internal-apprepository-job-postupgrade-l5dnn -o yaml | grep -i securityContext` returned a {}.

### Describe the results you expected:

**Completed** pod status.

### Additional information you deem important :

So what we did was to update _templates/apprepository-jobs-postupgrade-rbac.yaml_ to add the privileged psp : 
```
[...]
16     verbs:
 17       - get
 18       - create
 19  - apiGroups:
 20      - policy
 21    resources:
 22      - podsecuritypolicies
 23    verbs:
 24      - use
 25    resourceNames:
 26      - privileged
 27 ---
 28 apiVersion: rbac.authorization.k8s.io/v1
 29 kind: RoleBinding
[...]
```
Now, we need to maintain a little patch, we're not 100% upstream and last but no least so we broke our philosophy.

We're maintaing very restricted cluster policies, and privileged psp is "a must not have" for running our clusters.

We really hope we misunderstood something, it'll be the easiest to deal with.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2020-09-04 19:51:43.204927002 +0200 CEST        deployed        kubeapps-3.9.0  DEVEL
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by absoludity** [comment]
Thanks @f-guichard for the report. Yes, we definitely don't want that job requiring a privileged root container so you should not need to work around this. That said, I'm struggling to reproduce. I'm running my local environment with:

```
diff --git a/chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml b/chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
index 62d060e2..dfd48596 100644
--- a/chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
+++ b/chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
@@ -7,7 +7,7 @@ metadata:
   annotations:
     helm.sh/hook: post-upgrade
     helm.sh/hook-weight: "0"
-    helm.sh/hook-delete-policy: hook-succeeded
+    helm.sh/hook-delete-policy: never
   labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
     app: {{ template "kubeapps.apprepository-job-postupgrade.fullname" . }}
 spec:
diff --git a/docs/user/manifests/kubeapps-local-dev-values.yaml b/docs/user/manifests/kubeapps-local-dev-values.yaml
index d6de7388..3bf89be3 100644
--- a/docs/user/manifests/kubeapps-local-dev-values.yaml
+++ b/docs/user/manifests/kubeapps-local-dev-values.yaml
@@ -18,4 +18,7 @@ ingress:
   enabled: true
   hostname: localhost
   tls: true
-
+securityContext:
+  enabled: true
+  runAsUser: 1001
+  fsGroup: 1001
```

so that both the securityContext is set *and* the upgrade job isn't deleted on success, and what I see is a pod with the expected `securityContext`:

```
k -n kubeapps get po -o yaml kubeapps-internal-apprepository-job-postupgrade-qlkjb | grep securityContext -A 3
        f:securityContext:
          .: {}
          f:fsGroup: {}
          f:runAsUser: {}
--
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount: kubeapps-internal-apprepository-job-postupgrade
```

This is from the template which explicitly sets the securityContext if it's enabled: https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml#L32

It's not clear to me why you would get an empty result for your `kubectl get po kubeapps-internal-apprepository-job-postupgrade-l5dnn -o yaml | grep -i securityContext ` test that you mentioned above.

Furthermore, if I test the other container which is being run as part of that pod, it appears to be not running as uid 1001:

```
docker run --entrypoint=/usr/bin/id bitnami/kubectl:1.16.14-debian-10-r0
uid=1001 gid=0(root) groups=0(root)
```

The gid is 0, but that's the same for the other images which aren't causing you this issue:
```
docker run --entrypoint=/usr/bin/id bitnami/kubeapps-dashboard:1.11.3
uid=1001 gid=0(root) groups=0(root)
```

Am I missing something obvious that is causing your pod to be rendered without the `securityContext`?

**Comment by f-guichard** [comment]
thx @absoludity.

So if it works as expected for you, we will focus on doing again everything. Closing for the time being, and i will reopen it if we're truly sure that we're not the problem :)

**Comment by absoludity** [comment]
OK, though I'm keen to understand what might have triggered your job being created without the `securityContext`. The only way I can see currently (could be more) to reproduce the end-scenario which you found would be:

1. initially deploy with `securityContext.enabled=false` (the default value) and so the pod had failed due to the cluster-level PSP being enforced. Because it failed, the job/pod was not deleted.
2. upgrade kubeapps with `securityContext.enabled=true` and the upgrade succeeds. Importantly, because the job succeded, it is deleted (as the `helm.sh/hook-deletion-policy` is set to `hook-succeded` )
3. check the pods in the namespace and see the existing failed job from step 1?

Not sure if that's a possible sequence you may have done? Anyway, let us know if you're able to reproduce otherwise.

**Comment by f-guichard** [comment]
Damn (sorry), that's exactly that !

Many thx.
