### ISSUE TITLE
Add chart support for auth-proxy session store

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2042]
### Description:

As more people are using the OIDC support, especially with MS active directory, we're seeing issues related to the size of the headers and cookies. In particular, if the encrypted `id_token` is larger than 4k (due to a large number of groups or other meta data returned in the token), oauth2-proxy, when using cookie storage, is forced to split the cookie into two parts which [can cause issues](https://oauth2-proxy.github.io/oauth2-proxy/configuration#configuring-for-use-with-the-nginx-auth_request-directive).

As per that link, the simplest solution is to use the `redis` storage for oauth2-proxy rather than the `cookie` storage, though this may have other security implications, depending on the setup.

### Steps to reproduce the issue:

(Still need to verify, but)

1. [Configure LDAP with many groups and ensure a particular user is a member of all](https://github.com/kubeapps/kubeapps/blob/master/docs/user/manifests/kubeapps-local-dev-openldap-values.yaml)
2. Log in using that user (both through the nginx ingress, and via proxying to the auth proxy pod to check for differences)

### Describe the results you received:

Not sure, @lindhe can perhaps provide more info, if this is the issue being experienced.

### Describe the results you expected:

Should be able to log in even when the `id_token` is large.

**Comment by lindhe** [comment]
Interesting to hear! @kristinnardal2 let's look into this!

**Comment by kristinnardal2** [comment]
I like the idea of adding the session storage to the chart so that you could enable it by setting `authProxy.sessionStorage=enabled`. We would only need to add the `redis` subchart to dependencies and add a few flags to the auth proxy deployment.

I've already tried manually deploying a redis instance and using it for the session storage for the auth proxy and it seems to have worked fine.

We've (me and @lindhe) have run into a different problem which we think is related to Azure and their [AKS-managed Azure AD](https://docs.microsoft.com/en-us/azure/aks/managed-aad). I believe this change broke Kubeapps as we are now unable to login using the AD. We get a 401 response from the api server during the call to /api/clusters/default

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

The reason we suspect this to be the issue is that we had [trouble with authentication](https://github.com/MicrosoftDocs/azure-docs/issues/61959) with `kubectl` versions below 1.18 after enabling it. I'm going to create a new cluster without AKS-managed Azure AD and see if the problem is still there. This will allow me to find out if the AKS-managed Azure AD is the problem and if it is whether using redis fixes the issue of large headers and cookies.
