### ISSUE TITLE
Feature request: command line verbose output during deployment

### ISSUE THREAD

**Issue by spacecat** [kubeapps/kubeapps#207]
After clicking the "Deploy using Helm" button I would like to see actual output in a terminal window instead the blinking yellow "Deploying" button. (or a combination)

I've installed Drupal, Wordpress and other apps and some of them take a very long time. You don't know if they encountered errors or if they are still indeed deploying.

**Comment by prydonius** [comment]
+1 thanks for filing.

It's a little bit difficult to do since we rely on the Helm CRD Controller (https://github.com/bitnami-labs/helm-crd) and the controller does the `helm install` asynchronously. However, we should be able to update the controller to set any errors or the `helm install` output in the `status` spec, which we could then surface in the UI.

**Comment by arapulido** [comment]
@prydonius shall we close this one in favour of #439?
