### ISSUE TITLE
Error if user cannot read AppRepositories in Kubeapps' namespace

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2098]
### Description:

For a default installation, a user who views app repositories will see the error:

![image](https://user-images.githubusercontent.com/497518/95164996-d4e41a00-07f6-11eb-953c-241673b04ef7.png)

With the old UI, users saw only the app repositories in their own namespace:

![image (1)](https://user-images.githubusercontent.com/497518/95165577-01e4fc80-07f8-11eb-9b47-0571b11b78a4.png)

### Steps to reproduce the issue:

1. Install Kubeapps without any rolebindings for app repository reading
2. Login as a normal user
3. Access configuration for AppRepositories

### Describe the results you received:

As above

### Describe the results you expected:

Display local app repositories only, perhaps with a msg about missing RBAC for the global ones (though that'd not be pretty for cases where people aren't to have access).

Or another option is that Kubeapps users always see the global repos (ie. we use a service account to fetch them, but not keen on escalated privs like that. My preference is to not display them if they're not available via RBAC.

### Additional information you deem important (e.g. issue happens only occasionally):

Reported by Graham Dumpleton.

**Comment by GrahamDumpleton** [comment]
Maybe you should follow what some other packages do, which is to have a separate ClusterAppRepositories (non namespaced) to setup globally available repositories. Then also have a ClusterRole for KubeappsUser which has read only access to ClusterAppRepositories CR instances. Then a service account can have local RoleBinding in namespace it operates (or ClusterRoleBinding if have privileges to do it and necessary), which references KubeappsUser ClusterRole. That way don't need to do things in kubeapps namespace for it.

**Comment by andresmgot** [comment]
It was part of the design that even if a user don't have permissions to read or access apprepositories CR in the `kubeapps` namespace, these apprepositories should be shown to them since they are actually able to use them in the catalog. The backend service `kubeops` is already prepared to do so: 

https://github.com/kubeapps/kubeapps/blob/master/pkg/kube/kube_handler.go#L360

But neither the dashboard is using that endpoint at the moment nor the kubeops service has permissions to "list" apprepositories in the kubeapps namespace. I will address that in a PR.

**Comment by andresmgot** [comment]
> Maybe you should follow what some other packages do, which is to have a separate ClusterAppRepositories (non namespaced) to setup globally available repositories. Then also have a ClusterRole for KubeappsUser which has read only access to ClusterAppRepositories CR instances. Then a service account can have local RoleBinding in namespace it operates (or ClusterRoleBinding if have privileges to do it and necessary), which references KubeappsUser ClusterRole. That way don't need to do things in kubeapps namespace for it.

Discused in slack, but for the record:

yes, we discussed that possibility, at the end we decided not to do that (even though it would be more logic from a Kubernetes-native point of view) in favor of multitenancy. With the current approach, you can have two instances of Kubeapps in the same cluster, each of those with different "global" app repositories that don't conflict because at the end of the day, these resources are not cluster-wide.
