### ISSUE TITLE
Feature request: manage non-kubeapps helm charts

### ISSUE THREAD

**Issue by vietwow** [kubeapps/kubeapps#214]
Hi,

Kubeapps looks very promising and I think it would be useful that Kubeapps can manage helm charts which are not installed by kubeapps (for example, my CI/CD will use helm CLI to install the chart and then I can use kubeapps to manage it). Thanks.

Best Regards,
VietNC

**Comment by prydonius** [comment]
Hey @vietwow, thanks for filing the issue!

Instead of using the Helm CLI, do you think you could create and manage HelmRelease objects in your CI/CD setup (https://github.com/bitnami-labs/helm-crd)? If you use that, Kubeapps will be able to list the Helm Releases you create outside of Kubeapps.

There may also be a way to link Helm releases installed using the CLI, but it's a little trickier for us, and harder to manage.

**Comment by vietwow** [comment]
Hi @prydonius,

Ya, I think using helm-crd is possible. But, helm-crd is experimental CRD, so it's a risk for us if we switch my CI/CD to it in this time. Besides that, I think every company has its own CI/CD flows, so If you want to kubeapps become ubiquitous, you can't force them all using helm-crd to replace helm CLI which is very famous, I think we should have some way to work around this issue. Thanks

Best Regards,
VietNC

**Comment by prydonius** [comment]
@vietwow yeah, that makes sense. I'll have a think about how we can integrate with the Helm CLI. Just FYI, Kubeapps runs Tiller in the `kubeapps` namespace, so you would need to run `helm upgrade --tiler-namespace=kubeapps <release> <chart>`.

**Comment by prydonius** [comment]
This was implemented as part of #330 and is in the v1.0.0-alpha.4 release. More changes to come soon as we switch to using a Tiller proxy service instead of the Helm CRD controller.
