### ISSUE TITLE
Kubeapps UI should gracefully handle token expiration

### ISSUE THREAD

**Issue by doddatpivotal** [kubeapps/kubeapps#2143]
![Screen Shot 2020-11-04 at 11 15 03 AM](https://user-images.githubusercontent.com/37634387/98136506-018b6000-1e8f-11eb-9699-338fd921dc5b.png)

I choose not to use a service account to access kubeapps, but rather the token generated by the vsphere-login kubectl plugin.  This sets the context of my kubeconfig with a token that does have an expiration date.

I've used that token to login to kubeapps and am able to interact based upon my personal user account permissions.

However, if I come back to kubeapps after some time and my token has expired, I see this message.  If I click logout, the message remains and I am not brought to the login page.  If I refresh my browser, finally I am brought to the login page.

It is my expectation that kubeapps should handle the expired token condition, and redirect me directly to the login page (perhaps with an info message indicating that the token is expired).

I can not use OIDC authentication because at this point, vSphere 7u1 does not offer an OIDC auth provider.

**Comment by antgamdia** [comment]
I've just looked into the issue and the solution doesn't seem complicated. Perhaps if a redirect is forced after every logout the UX improves.

**Comment by doddatpivotal** [comment]
That would incrementally be better.  Would love to see a better error message than "minified react error".  And potentially an auto logout, redirect to login.

**Comment by andresmgot** [comment]
What we had in the past, was a modal saying "Your session has expired, please reload the page" and a button to reload (or simply redirect if the person refreshes the page. See the code at dashboard/src/components/PrivateRoute/PrivateRoute.tsx:28. What I don't know is if after the UI revamp that code is still been reached so we may need to refactor that a bit.

**Comment by antgamdia** [comment]
Mmm, looking into this issue a little bit more,  the error message is not just a 401/403 problem, but, indeed, there is something causing an endless redirection loop (see the error message: https://reactjs.org/docs/error-decoder.html/?invariant=185).

**Comment by antgamdia** [comment]
@doddatpivotal, would you mind to share more detailed information about how to reproduce this error? I'd need some docs or references so that I can set up the environment to investigate what's happening. 
(feel free to contact me in slack at [@]agamez)

**Comment by antgamdia** [comment]
This issue is also appearing when performing these steps:

1. Login with token
2. Edit the URL deleting namespace: https://clusterURL/#/c/default/ns/namespaceName/catalog to -> https://clusterURL/#/c/default/ns//catalog
3. Go to this URL (w/o namespace): https://clusterURL/#/c/default/ns//catalog
4. Go -again- to this URL (w/o namespace): https://clusterURL/#/c/default/ns//catalog (Note now the namespace in the right panel is disappearing)
6. Click Kubeapps logo (https://clusterURL/#/)
7. Error appears

I guess it is due to a wrong 403 handling when it is not just a 'normal' RBAC problem (e.g., "user X not having access to namespace Y"). 
This issue is closely related to #2018. in which we are currently working on.
