### ISSUE TITLE
How to change the time zone of kubeapps is not cst

### ISSUE THREAD

**Issue by NadamHL** [kubeapps/kubeapps#2205]
How to change the time zone of kubeapps to cst

**Comment by antgamdia** [comment]
In which part are you viewing a wrong timezone? Could you please attach a screenshot?

**Comment by andresmgot** [comment]
Hi @NadamHL, Kubeapps doesn't have configuration related to timezones (so I assume you should look for Kubernetes settings). I am going to close this issue but please reopen it if you still think this is an issue related to Kubeapps.

**Comment by flypiggy-stack** [comment]
![image](https://user-images.githubusercontent.com/41814781/106097769-d903c100-6172-11eb-9464-6b019e1e3f93.png)
The time zones of the first line and the second line are not consistent. In the first line, I directly use the command "helm upgrade" to update. In the second line, I operate on the dashboard of kubeapps. When I operate on the Web UI, the updated time zone will be UTC.So how do I operate on the dashboard of kubeapps to make the time zone CTS

**Comment by absoludity** [comment]
The screenshot you're showing is output from the helm CLI. You can actually specify a `--time-format` argument to `helm ls` to specify the format you want (see https://helm.sh/docs/helm/helm_list/#options ), but I can't say why helm would be using a different timezone offset unless that's what was stored in the actual secret (you can examine the kubernetes secret which helm is using to generate that data, check the `.metadata.managedFields.time`. Can you check or confirm whether the releases using UTC are deployed by Kubeapps while the releases in CST are deployed via the helm CLI?

If that's the case, then yes, it could be that Kubeapps's use of the Helm CLI is using the system time of the Kubeapps server when creating the helm release secret.

So: does the `--time-format` option to `helm ls` solve your problem? If not, it's not clear to me how Kubeapps can change this value since the [helm time api](https://github.com/helm/helm/blob/46d80f68c11d8107b688b9c8299fa02bccba312f/pkg/time/time.go#L38) which is used to generate the timestamp just calls `time.Now()` which returns the  [current local time](https://golang.org/pkg/time/#Now). The only way you could control this is by ensuring that the server/container on which Kubeapps is running has the locale set. Hopefully `--time-format` solves your problem :)
