### ISSUE TITLE
Bump up old image versions (nginx, oauth2proxy, etc)

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2228]
We already have this as part of our release instructions, it's just been skipped sometimes.

I've done the images in #2224 , but I've not done the frontend packages, they'll take a little more work.

**Comment by andresmgot** [comment]
Following up the conversation at #2224. I don't think that updating npm and golang dependencies are strictly necessary. That would add quite an overhead to the process (more if you think about client-go deps). The main point of doing this is for security reasons, so to avoid having to deal with unnecessary breaking changes, I would change the process to do `yarn audit` and fix high severity vulnerabilities (I think there is not a similar thing for go mod). WDYT? (cc/ @antgamdia)

**Comment by absoludity** [comment]
+1 for yarn audit for every release, but I still think we should ensure other deps (and go mods) are updated to the latest patch or minor release on some regular basis?

**Comment by andresmgot** [comment]
> I still think we should ensure other deps are updated to the latest patch or minor release on some regular basis?

The problem is that there is no guarantee that a patch or minor update won't break anything (people may get semver wrong). Upgrading a package, if we are not using the new features and if it doesn't include security fixes would not be that helpful.

>  (and go mods) 

It's even worse for go modules. There is no way (at least that I know) to update just minor/patch versions and we have a lot of deps pointing to a specific commit so there is no guarantee that an update would work.

**Comment by absoludity** [comment]
> > I still think we should ensure other deps are updated to the latest patch or minor release on some regular basis?
> 
> The problem is that there is no guarantee that a patch or minor update won't break anything (people may get semver wrong).

Right, but that's why we have CI isn't it? Or do you think it'd be more than an occasional breakage.

> Upgrading a package, if we are not using the new features and if it doesn't include security fixes would not be that helpful.
> 

We're currently running code that is no longer maintained, iirc (from memory, when trying an yarn upgrade). There may not be a security release, but if the code is no longer maintained it's also an issue, but it won't show up in the audit. This happens because we're on an old minor version. I'd be keen to hear what @Angelmmiguel does in these situations - maybe it's exactly what you say (security updates only).

> > (and go mods)
> 
> It's even worse for go modules. There is no way (at least that I know) to update just minor/patch versions

I thought that's the default behaviour: `The -u flag instructs get to update modules providing dependencies
of packages named on the command line to use newer minor or patch
releases when available` . Or am I missing something in your meaning?

> and we have a lot of deps pointing to a specific commit so there is no guarantee that an update would work.

The specific commits will mostly be for modules which didn't define a `go.mod` initially, I'd think, most of which should be able to be updated to a version.

**Comment by Angelmmiguel** [comment]
> > Upgrading a package, if we are not using the new features and if it doesn't include security fixes would not be that helpful.

> We're currently running code that is no longer maintained, iirc (from memory, when trying an yarn upgrade). There may not be a security release, but if the code is no longer maintained it's also an issue, but it won't show up in the audit. This happens because we're on an old minor version. I'd be keen to hear what @Angelmmiguel does in these situations - maybe it's exactly what you say (security updates only).

👋

This is a common issue in many javascript projects. Dependencies have new versions constantly and unfortunately, it's not easy to bump them. Agree with @absoludity that old code that it's no longer maintained may work now, but it's a stone that you may stumble in the future. For example, if you focus only on security fixes, a new security issue may affect an old version you have in project. If you need to bump a critical library several versions, it may require a lot of effort.

Other case to take into account is the build process. Node is also another piece where security issues may force you to upgrade. Some old libraries are not compatible with newer versions and new libraries may not be compatible with old Node versions. 

I totally agree this is a pain, but from my experience the longer you delay the upgrade, the more difficult it gets. Upgrading dependencies in the projects should be part of regular maintenance tasks. This is what we do in other projects. We still keep track of current and new versions and book some time every month to bump libraries. Also, having a good test suite + deployment process simplifies this a lot.

Hope it helps!

**Comment by antgamdia** [comment]
Totally agree with your comments, .absoludity and .Angelmmiguel. Just for adding more specific information regarding some outdated (frontend) deps in the project:

We also need to update the `@types` definitions:

- `warning @types/moxios > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410`

We have some unnecessary type definitions

- `warning @types/vfile@4.0.0 ...`
- `warning @types/vfile-message@2.0.0 ...`

Some deps are introducing deprecated transitive deps. Some of them will break on node v14+ (now we're using 12.20.0 but current LTS is Node 15, _Node 12 EoL is on April 2022_).
We cannot expect from this deps to continue having security patches.

- `diff2html` (adding `mkdirp@0.3.0`). For instance, it is vulnerable to a [prototype pollution](https://app.snyk.io/vuln/SNYK-JS-MERGE-1040469)
- `react-jsonschema-form` (adding `core-js@<3`)
- `enzyme` (adding `cheerio-select-tmp@0.1.1`)
- `jest-enzyme` (adding `left-pad@1.3.0`, `request-promise-native@1.0.9`, `request@2.88.2`, `har-validator@5.1.5`, `resolve-url@0.2.1`,  `urix@0.1.0`)
- `node-sass-chokidar` (adding `request@2.88.2`)
- `react-scripts` (adding `fsevents@2.1.2`, `eslint-loader@3.0.3`, `request@2.88.2`, `request-promise-native@1.0.9`, `chokidar@2.1.8`, `fsevents@1.2.1`, `urix@0.1.0`, `@hapi/joi@15.1.1`, `@hapi/address@2.1.4`, `@hapi/bourne@1.3.2`, `@hapi/hoek@8.5.1`, `@hapi/topo@3.1.6`, `core-js@<3`)

Regarding the go dependencies, I just use to exec `go get -u` in each project and it just updates patch and minor versions. However, we should check our current versions as there are a number of deps with security issues.
For instance, `k8s.io/kubernetes`, `k8s.io/apimachinery`, `github.com/go-openapi/spec`, `helm.sh/helm/v3` and many others (up to 56).


My recommendation is to update deps as a regular basis (once per month, for instance) as well as add a mature vulnerability scanner. I've been using [Snyk](https://snyk.io/) for my personal projects and it works really well (dependabot is missing many updates...). What do you think?

**Comment by absoludity** [comment]
> What do you think?

Sounds like a plan :) If Andres is in agreement, can you update the description of this issue with a checklist for the above (including updating the release docs to include the required steps). I doubt we'll get that done this week with everything else, but great if we can start and have a solid plan.

**Comment by andresmgot** [comment]
I am okay with this, lets just update patch versions for this issue and open a new one for reporting vulns
