### ISSUE TITLE
How to change the time zone of kubeapps is not cst 

### ISSUE THREAD

**Issue by flypiggy-stack** [kubeapps/kubeapps#2288]
The time zones of the first line and the second line are not consistent. In the first line, I directly use the command "helm upgrade" to update. In the second line, I operate on the dashboard of kubeapps. When I operate on the Web UI, the updated time zone will be UTC. So how do I operate on the dashboard of kubeapps to make the time zone CTS
![image](https://user-images.githubusercontent.com/41814781/106098637-57149780-6174-11eb-8dfc-c8376062e60b.png)

**Comment by andresmgot** [comment]
Hi @flypiggy-stack,

That's because on your environment, the timezone is configured while in Kubernetes Pods it's not so it's falling back to UTC. The timezone is configurable using the TZ environment variable (e.g. `TZ=America/Costa_Rica` for `-0600 CST`, the list of codes can be found [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). For a quick test, you can add that environment variable to the deployment `kubeapps-internal-kubeops` and deploy something. If that works for you, we can allow to modify those env vars from the chart.

**Comment by absoludity** [comment]
More info at https://github.com/kubeapps/kubeapps/issues/2205#issuecomment-769589819 (including `--time-format` option to `helm ls`. Great if the TZ env var works!

**Comment by flypiggy-stack** [comment]
Thank you for your reply. I tried to modify the environment variable of `kubeapps-internal-kubeops` and add the time zone I need, but the time zone display will still change to UTC. The figure below shows me executing "`kubectl describe - n kubeapps" deployments.apps kubeapps-internal-kubeops`"
![image](https://user-images.githubusercontent.com/41814781/106419873-66595500-6494-11eb-886c-3edae6573537.png)

**Comment by andresmgot** [comment]
Hi @flypiggy-stack, the `TZ` is an environment variable, not an argument. You will need to do something like:

```patch
  Environment:
    POD_NAMESPACE= (v1:metadata.namespace)
+   TZ: Asia/Shanghai
```

**Comment by flypiggy-stack** [comment]
Hi @andresmgot ,I have changed the environment variables I need based on your prompts, but deploying chart through Web UI still displays UTC's time zone. Do I need to add environment variables in other places?
![image](https://user-images.githubusercontent.com/41814781/106540839-b9d2ae00-653b-11eb-9561-f197d0b6ed47.png)

**Comment by andresmgot** [comment]
Hi @flypiggy-stack, I have checked this. Indeed changing only the `TZ` doesn't work because the `scratch` image does not contain the files needed to resolve it. We need to add it explicitly:

```patch
diff --git a/cmd/kubeops/Dockerfile b/cmd/kubeops/Dockerfile
index bfddea4a..1eda435e 100644
--- a/cmd/kubeops/Dockerfile
+++ b/cmd/kubeops/Dockerfile
@@ -15,6 +15,7 @@ RUN --mount=type=cache,target=/go/pkg/mod \
 FROM scratch
 COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 COPY --from=builder /go/src/github.com/kubeapps/kubeapps/kubeops /kubeops
+COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
 EXPOSE 8080
 USER 1001
 CMD ["/kubeops"]
```

You can try with that and build the image (if possible send a PR? :) If not I will send it once I have some slot free)

**Comment by flypiggy-stack** [comment]
Hi @andresmgot ,I can't build a mirror locally. I hope you can give me a mirror address directly, and let me pull it down. Thank you

**Comment by andresmgot** [comment]
Hi @flypiggy-stack, you can try with this image: `kubeapps/kubeops:dev-2021-02-04T16-07-54-CET`

**Comment by flypiggy-stack** [comment]
Hi @andresmgot ,replace it with the image you provided to solve my problem. Thank you very much.

**Comment by andresmgot** [comment]
Thanks for confirming @flypiggy-stack, let me keep this issue open until that is something that can be configured (so you can update the application in the future).
