### ISSUE TITLE
wss requests are 403 when using pinniped

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2328]
### Description:

It appears that they're not being routed (or there's some issue routing) the wss requests via pinniped. It's not a show-stopper since we fall back to the polls.

Example:
![wss-403s](https://user-images.githubusercontent.com/497518/106996084-57480f00-67d4-11eb-8d80-882848b8135b.png)

I'll need to investigate more, just noting for now.

**Comment by andresmgot** [comment]
why do you say it's not being routed? I guess you checked but being a 403 it may mean that you don't have permissions to `watch` resources.

**Comment by absoludity** [comment]
> why do you say it's not being routed? I guess you checked but being a 403 it may mean that you don't have permissions to `watch` resources.

From memory I didn't even see the requests even hitting pinniped-proxy, but I'll re-check when getting back to this.

**Comment by absoludity** [comment]
Great, thanks Antonio.

**Comment by antgamdia** [comment]
Well, I've been investigating this issue a little bit more, and I'm afraid I don't have a solution right now...

As far as I know, the HTTP connection to `...?watch=true` with requesting moving to websockets is properly being routed (hence the `101 switching protocols` response), however, our pinniped-proxy logic is not handling the messages that may come from the k8s API.

For each connection, we are doing  `make_service_fn(|_conn| { .... ` and `service_fn(move |req| { service::proxy(req, default_ca_data.clone().into_bytes()) }))`, which, after many certs/tls/create clients/etc stuff, it simply does:

https://github.com/kubeapps/kubeapps/blob/32976944d2074a1e1e319b2fb24e4aef12fcee65/cmd/pinniped-proxy/src/service.rs#L83-L89

That is, requesting data (pinniped-proxy -> k8s) with the proper credentials and then, returning back to the actual client (pinniped-proxy->nginx->user's browser).

This is being executed per connection. So, essentially, given each -one- connection it will return -one- response.
If we were to support websockets here, I guess (not sure) we should keep open as many connections as the client  opens (until a close event or timeout), as well as handling the responses from the server.

[This is server logic needed](https://github.com/1tgr/rust-websocket-lite/blob/master/hyper-websocket-lite/src/lib.rs) for accepting the change to websockets. However, this is not necessary at all, since the real k8s is accepting the change (we have the 101 status code)

What we do really need is the [actual handler for sending the message stream](https://github.com/1tgr/rust-websocket-lite/blob/master/hyper-websocket-lite/examples/autobahn-server.rs#L9-L37). It would require actually watching the k8s and forwarding the messages back through this connection.

At this point I have two main concerns: i) I still feel quite lost with Rust and don't feel comfortable with implementing a (k8s) websocket proxy in rust from scratch. Of course, I can give it a try, but definitively the issue won't be a size/S anymore :P; ii) does having ws support when using pinniped really worth it considering the required effort?

Conversely, my rationale might be completely wrong and the issue may be much simpler than I'm thinking of.
Let's hold this issue until I can get more feedback from @absoludity .

**Comment by absoludity** [comment]
> At this point I have two main concerns: i) I still feel quite lost with Rust and don't feel comfortable with implementing a (k8s) websocket proxy in rust from scratch. Of course, I can give it a try, but definitively the issue won't be a size/S anymore :P; ii) does having ws support when using pinniped really worth it considering the required effort?

I agree on both points. As mentioned in the description, this isn't something urgent, since we have a fall-back that works. We certainly don't need to be implementing a websocket proxy from scratch. I had thought it may be something as simple as not closing the connection if the response comes back as 101 (though note on my test on an actual cluster, I didn't even see that - got a 403).

> 
> Conversely, my rationale might be completely wrong and the issue may be much simpler than I'm thinking of.
> Let's hold this issue until I can get more feedback from @absoludity .

Let's hold it until it's more urgent - it's certainly not now. But the investigation you've done will be very useful when we do look at it. Thanks.

**Comment by andresmgot** [comment]
> this isn't something urgent, since we have a fall-back that works

I am not sure the fall-back mechanism is being triggered? That only happens when the websocket fails to be established, which is not clear to me it's what's happening here. Can you confirm that we are doing periodic requests in the App View so it get updates @antgamdia ?

**Comment by antgamdia** [comment]
Good point, you're right. We the fallback polling mechanism is not working indeed.  

It appears not to be falling because some initial API calls are being made: `.../deployments/my-release`, `.../services/my-release`. These calls are populating the UI, but there is no polling.
A couple of ideas here: 

- i) implementing a ping/pong ws mechanism: since we don't have control over the k8s API I think we cannot rely on a ping message (not sure if k8s will respond with a pong).
- ii) using a timeout: since we have long-running tasks, this fix could interfere with these tasks, triggering false-positive timeouts; 
- iii) since we do control PinnipedProxy, I'll opt for adding an explicit denial of 101 HTTP responses with a //TODO linking to this issue. It will make the ws to fail, hence triggering the fallback mechanism.

I'll  start implementing iii), but I'm open to further ideas or suggestions

**Comment by andresmgot** [comment]
I agree with the third option. If it doesn't work better to "disable" it.

**Comment by absoludity** [comment]
> > this isn't something urgent, since we have a fall-back that works
> 
> I am not sure the fall-back mechanism is being triggered? That only happens when the websocket fails to be established, which is not clear to me it's what's happening here. Can you confirm that we are doing periodic requests in the App View so it get updates @antgamdia ?

I was getting websocket failures (403s) as per the screenshot on the original issue. Not sure why the local setup is different or whether something else changed (my testing was on a TMC env).
