### ISSUE TITLE
Bump up Clarity version (v4->v5)? Analyze benefits

### ISSUE THREAD

**Issue by danoo** [kubeapps/kubeapps#2372]

**Comment by antgamdia** [comment]
Some thoughts here:

- AFAIK, the majority of our styles rely on `clr/ui` because it is like the static css style. Other components do rely con `cds/core`. So, for having the whole appearance, we need both styles.
  - Problem: `clr/ui` is not actively maintained now and there are missing features, such as the native support for themes. We have to conditionally load the light/dark mode.
    - In my PoC it is implemented with media queries to the browser native config, but a selector/toggle/whatever is also feasible.
 - Migrating v4->v5 is not that difficult, it is just a change in the priority of some selectors (eg. thenumber of pods deployed was misplaced)
 - There are a number of hardcoded css values (that is, not depending upon sass variables). Some effort on replacing these references by the ones from the clarity docs is required.
   - Once we have it, it becomes [really easy to change the color schema ](https://clarity.design/foundation/themes/usage/#custom-theme)without dealing with low-level css selectors.


There is an ongoing work in #2371 , but nothing PR-ready yet.

**Comment by absoludity** [comment]
> Some thoughts here:

Thanks. I don't have much context for the clarity integration as Andres worked on that, so a couple of questions:
 
>     * AFAIK, the majority of our styles rely on `clr/ui` because it is like the static css style. Other components do rely con `cds/core`. So, for having the whole appearance, we need both styles.

But should we be removing use of `clr/ui`? From the [website](https://clarity.design/get-started/developing/angular/) it looks like `clr/ui` is part of the angular-specific clarity? Or is there no issue to continue to use these?

>       * Problem: `clr/ui` is not actively maintained now and there are missing features, such as the native support for themes. We have to conditionally load the light/dark mode.

So if we were not using `clr/ui` the theming wouldn't require the conditional loading, but the impact isn't big? (ie. if this is a one-line change which does the conditional load for all our components that use `clr/ui`, great, but if not, perhaps it's more reason to invest in moving them to `cds/core`, unless there's other reasons not to?

>         
>         * In my PoC it is implemented with media queries to the browser native config, but a selector/toggle/whatever is also feasible.

Do other products using `cds` do the former? If so, switching from one of those to Kubeapps would just work - no extra decision necessary. If on the other hand they're setting a cookie or similar that we won't be able to read, it'll be necessary to switch. Guess we can default to the browser native but allow a switch in the settings (even behind a flag if we don't want to introduce extra clutter to the settings unnecessarily).

> 
>     * Migrating v4->v5 is not that difficult, it is just a change in the priority of some selectors (eg. thenumber of pods deployed was misplaced)
> 
>     * There are a number of hardcoded css values (that is, not depending upon sass variables). Some effort on replacing these references by the ones from the clarity docs is required.
>       
>       * Once we have it, it becomes [really easy to change the color schema ](https://clarity.design/foundation/themes/usage/#custom-theme)without dealing with low-level css selectors.
> 
> 
> There is an ongoing work in #2371 , but nothing PR-ready yet.

Excellent stuff Antonio!

**Comment by andresmgot** [comment]
yes, there is a lot of our code relying on `clr/ui` CSS clases (mostly because at the moment of migrating the app to Clarity, the `cds/core` was not mature enough). If we were to migrate everything to Clarity Core (if that were possible, which I'm not sure), it would require a fairly big effort to migrate everything.

**Comment by antgamdia** [comment]
> But should we be removing use of `clr/ui`? From the [website](https://clarity.design/get-started/developing/angular/) it looks like `clr/ui` is part of the angular-specific clarity? Or is there no issue to continue to use these?

I'm not able to have a strong opinion here. afaik, not every component we use is available in cds yet. Also, as Andres is pointing out, it's not an easy (it's tedious) task.

Besides, it introduces some attributes that, imo, will couple too much the component to the visualization. Example:
```
<div cds-layout="horizontal gap:sm">
```

> If on the other hand they're setting a cookie or similar that we won't be able to read, it'll be necessary to switch. Guess we can default to the browser native but allow a switch in the settings (even behind a flag if we don't want to introduce extra clutter to the settings unnecessarily).

No, it's really easy. It is just a matter to decide (react side) which css file we should import (using css native media queries). There some caveats during the initial load, but let's discuss it in PR #2450.
Other selection ways (eg. flag in values.yaml) can also be easily implemented.

**Comment by absoludity** [comment]
Yep, if there's a substantial amount of work to update, and no real gain right now (assuming we can do the theming/dark-mode easily without), great. Thanks both for the extra background.

**Comment by antgamdia** [comment]
So, finally, this issue can be closed. 
We have performed a migration to the latest clarity version, but we still use `clr` instead of `cds`. The required effort to migrate everything to `cds` is big and perhaps it is not worthwhile since some components are still in beta or are having issues.

For instance, i) the cds modal property `hidden` can't be used anymore to conditionally show/hide the modal and ii) the cdsButton are ignoring the type=button and they are submitting the form anyway (even if it's a cancel button).

So, let's hold the full migration to cds until the react version of clarity is more mature.


As a visual example: our modals are consistent with the 'official' clarity modals:

Before:
![image](https://user-images.githubusercontent.com/11535726/109964231-b161c480-7ced-11eb-9884-a70c9d6f033c.png)

After:
![image](https://user-images.githubusercontent.com/11535726/109964250-b9b9ff80-7ced-11eb-888f-54d0c19a31c1.png)
