### ISSUE TITLE
Unable to show the Catalog tab

### ISSUE THREAD

**Issue by jiad-vmware** [kubeapps/kubeapps#2484]
Just installed KubeApps on Tanzu Kubernetest cluster on vSphere with these steps:
1. helm repo add bitnami https://charts.bitnami.com/bitnami
2. kubectl create namespace kubeapps
3. helm install kubeapps --namespace kubeapps \
  --set assetsvc.service.port=9090 \
  --set frontend.service.type=LoadBalancer \
  --set useHelm3=true \
    bitnami/kubeapps
4. kubectl create --namespace default serviceaccount kubeapps-operator
5. kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
6. kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo
7. login to web UI and click Catalog tab.
8. See an error message "An error occurred while fetching the catalog:"
![kubeappserror](https://user-images.githubusercontent.com/68653329/109598633-7e8db580-7ace-11eb-872b-302f24430b1a.PNG)

**Comment by absoludity** [comment]
Unfortunately we don't have much experience with vSphere k8s clusters yet (but hoping to change that). Can you screenshot the network tab of your browser's developer console (if you can click on the actual request to see more info in the response, that'd be great too.

Can you also paste the output of `kubectl get pods --namespace kubeapps` right after you verify the error still happens? Thanks.

**Comment by jiad-vmware** [comment]
![kubeappserror3](https://user-images.githubusercontent.com/68653329/109601692-efd86300-7ae4-11eb-8d4b-b3408ff91e4e.PNG)
![kubeappserror4](https://user-images.githubusercontent.com/68653329/109601695-f070f980-7ae4-11eb-892d-78867d8b4292.PNG)
![kubeappserror2](https://user-images.githubusercontent.com/68653329/109601696-f1099000-7ae4-11eb-83ac-3b6f6c434017.PNG)


There are a lot of requests like this http://172.29.214.134/api/assetsvc/v1/clusters/default/namespaces/default/charts?page=14838&size=20 . The responses have error messages like : {"code":401,"message":"Authorization token missing"} .

BTW, what is the cluster name should be? I am not sure why it is default here. The name of my cluster should be app01-gc.

**Comment by absoludity** [comment]
"default" is just the name we use if you've not specified a name. It's not related to the problem you are seeing here, but if you want to change it you can [set the `clusters` option in your values](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/values.yaml#L29) with the name you want for the single cluster.

Regarding the screenshots, the first one looks like you've tried opening the API url directly which I would expect to complain about a missing authorization token (since pasting the api url the browser address bar will just trigger the browser to request it, without knowing about any authorization token). Or did I misread that screenshot?

The second screenshot shows that all the services and chart sync jobs are running fine.

The third is the interesting one... it seems to show that the requests that the frontend application makes to the assetsvc are never being serviced. As though setting the `assetsvc.service.port` as you've done is meaning that the frontend request is not getting to the correct port....

Confirmed, I just created a local deployment and tried setting the `assetsvc.service.port=9090` and get a very similar error (my setup is slightly different, using SSO). There are two issues:

1. The `assetsvc.service.port` option is currently not usable in the chart (can you avoid setting it until we fix this issue?)
2. The pagination seems to interpret the 502 response as a complete page and requests the next page infinitely:

![error-fetching-catalog](https://user-images.githubusercontent.com/497518/109608850-a2103900-7b7e-11eb-999a-c11e0b2eccc7.png)

**Comment by andresmgot** [comment]
Thanks @absoludity for the investigation, as he mentions @jiad-vmware, can you try again without setting the `assetsvc` port (I am not sure why you are doing so?):

```
helm install kubeapps --namespace kubeapps --set frontend.service.type=LoadBalancer bitnami/kubeapps
```

(the flag `useHelm3` is no longer needed)

**Comment by jiad-vmware** [comment]
@absoludity @andresmgot Thanks a lot for your help! Installation with command
helm install kubeapps --namespace kubeapps --set frontend.service.type=LoadBalancer bitnami/kubeapps worked great.
I got command from this page: https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps where assetsvc.service.port is set to 9090 (Under Parameters section).
