### ISSUE TITLE
Linking OIDC Provider user with Namespaces

### ISSUE THREAD

**Issue by jgato** [kubeapps/kubeapps#2569]
### Description:
I have configured Kuberntes to use an OIDC pointing to a Keycloak: it works, I can login with kubectl into kubernetes with my Keycloak users.

I have configured Kubeapsp to use the previous Keycloak: It works, I can login in kubeapps.

The problem is that the user, after login, he cannot see any namespace. I have manually created some roles to this user into their own namespace. I want each Keycloak user to have their own namespace.

ex: user jose@example.com will have a NS services-jose-example-com with enough perms, I have tested that.

But in the Kubeapps dashboard I cannot see my Namespaces, I can trick the dahsboard url to manually point to the Namespace 
and it works!! I can deploy apps, everything ok. But I cannot expect that from my users.

Before using Keycloak, my users were serviceaccounts that were linked to a Namespace. So it worked ok. 
I dont want to give Keycloak Users the role of listing namespaces. So how an external user (not a ServiceAccount) know which are their available Namespaces?

any idea how to solve that?

**Comment by andresmgot** [comment]
Hi @jgato,

For this scenario, what we do is using the internal `kubeops` service account to list namespaces in the cluster. Then check if the user has permissions to read namespaces in each of those:

https://github.com/kubeapps/kubeapps/blob/master/pkg/kube/kube_handler.go#L756

If that's not working for you, it can be because a couple of reasons:

 - You have disabled the property `allowNamespaceDiscovery` when installing the chart. If you do so, the internal serviceaccount with enough privileges to list namespaces won't be created.
 -  The user doesn't have permissions to access secrets in any namespace.

Can you check if any of those is your case?

**Comment by jgato** [comment]
it worked!! 
It is extrange, because I thought I tried to enable the NameSpaceDiscovery. My user had perms for accessing secrets (even I didnt knew "that trick"). Anyway it is working now!!
thanks @andresbono
