### ISSUE TITLE
Need to set up kubeapps to access multiple clusters and deploy applications on them

### ISSUE THREAD

**Issue by gkulkarni32** [kubeapps/kubeapps#2643]
### Description:

I need to set up kubeapps to be able to access multiple clusters and deploy applications on them. The documentation seems a bit confusing, need help with this. 

### Steps to reproduce the issue:

1. I've created the management cluster using calatrava.
2. Used this to create the guest clusters in TMC
3. I'm a VMware employee, but dont have access to download:  https://www.vmware.com/go/get-tkg extension plugin
4. Following steps from here:
https://liveandletlearn.net/post/tanzu-kubernetes-grid-tkg-first-experience/

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by antgamdia** [comment]
Closing this issue since we already discussed it offline. Thank you again for your interest in the Kubeapps multicluster environment. We will let you know once #2627 gets solved.

For the record, just a reminder that we also have a Slack channel for the community ([#kubeapps](https://kubernetes.slack.com/messages/kubeapps) on Kubernetes Slack).
