### ISSUE TITLE
Kubeapps apprepository as single worker pod

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2648]
Hello

I have a lot of apprepositories and hosting the cluster on the cloud GKE
theres a hard limit of GKE cluster to have at the same time 100 pods on each node
So when the app sync is occurs, he spawn lots of job pods
Another thing, is that the master nodes (something we dont have access directly), specifically kube-apiserver, have throughtput limit of http requests

Would be great if this can be as a single pod that make the sync of multiple repositories

Also, it will make the K8s cluster more cleaner

Thanks !

**Comment by andresmgot** [comment]
Hi @kfirfer,

This is an interesting scalability issue. It's true that having more than 100 cronjobs can be tricky.

As a workaround, I recommend to increase the interval in which the apprepos are synced. You can do so specifying the variable `--set apprepository.crontab='0 * * * *'` when installing the chart (that would set the schedule for every hour).

That doesn't fix your issue though, it just reduces the noise. To mitigate the problem we can:

 - As you say, use the same cronjob to sync several apprepos (as far as the repos are in the same namespace).
 - Remove the cronjobs and move the functionality to the controller sync loop so this one only spins up new jobs if there are updates in the repositories. 

WDYT @absoludity @antgamdia ? Any other option you can think of?

**Comment by absoludity** [comment]
I think this is also complicated by the amount of potentially unnecessary work that's done during a sync as well (from memory, I'd need to go and check, but this will be contributing to the http requests and cpu time). The constraints with this are, I think, that:

* Moving forward we want to ensure that the credentials for an app repository remain in that namespace, which is why Andres mentions above that we could use one cronjob for multiple repos in a namespace.

With this in mind, I'm not sure how the controller could check for an update in a repository without the credentials.

@kfirfer I would like us to look at improvements here, but I'm also interested to know more about your use-case. Do you have a lot of app repositories all with different content? Or can you otherwise tell us more about your scenario?
