### ISSUE TITLE
[kubeapps-apis] Add unit-tests for existing plugin functionality to easy adding further changes

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2849]
### Description:

The existing demo functionality was added and works with fluxv2 and kapp-controller without unit-tests, but as we build on this, we want to be able to do so using TDD and so need decent examples of doing so with the dynamic client (which will in turn force writing more testable code).

### Additional information you deem important (e.g. issue happens only occasionally):

This is important as more people start to work on the codebase, ensuring further changes are tested and that it is easy to follow existing examples to create new tests before changing/adding functionality, increasing velocity.

**Comment by absoludity** [comment]
Just adding all three of us as assignees since we'll all be adding unit tests as we go :)

**Comment by gfichtenholt** [comment]
I think in addition to unit-tests we should also have a end-2-end tests, where we stand up a cluster deploy carvel/flux on it test out our apis against that. I can open a separate issue for that  if you think its best

**Comment by antgamdia** [comment]
Yes, I agree. We already spin up a cluster as part of the usual CI process, as described in [1]. It's a good idea to continue working on improving our test suite. Let's file a new issue so that we can track the progress we make (eg. installing carvel and flux, etc).
However, I wouldn't start working/landing on those tests yet, since there are a few temporary things waiting to be defined.

Personally, currently, I'm working with a Postman collection where I track the (rest-ish) API calls
![image](https://user-images.githubusercontent.com/11535726/119469886-11459580-bd48-11eb-9a69-5f2f3b4cd93b.png)


[1] https://github.com/kubeapps/kubeapps/blob/master/docs/developer/end-to-end-tests.md#end-to-end-tests-in-the-project.

**Comment by gfichtenholt** [comment]
added https://github.com/kubeapps/kubeapps/issues/2881

**Comment by gfichtenholt** [comment]
I think ideally, everybody contributing to core api server and/or plug-ins, including me, should part-own it, but I can take it if no-one else will
