### ISSUE TITLE
[kubeapps-apis] coreServer and/or plugins should serve swagger 

### ISSUE THREAD

**Issue by gfichtenholt** [kubeapps/kubeapps#2859]
Exatly how to map gRPC calls to HTTP JSON API is pretty tricky
(described a bit here https://github.com/googleapis/googleapis/blob/master/google/api/http.proto). I think it would be very beneficial if our server and/or plugins would server openapi swagger on a well known endpoint so that can use standard tools like swagger.io and postman so people would not have to remember/know all the tricks to the translation. How to serve openapi swagger is described here https://github.com/grpc-ecosystem/grpc-gateway (it's a pretty long read)

**Comment by absoludity** [comment]
Definitely. I already had a form of this working in the POC (see the [openapiv2 directory](https://github.com/absoludity/kubeapps/tree/poc-kubeapps-api-service/cmd/kubeapps-api-service/openapiv2) which was being generated by [openapiv2 plugin configured with buf](https://github.com/absoludity/kubeapps/blob/poc-kubeapps-api-service/cmd/kubeapps-api-service/buf.gen.yaml#L16)), but as you'll see there, they're generated as separate files for each rather than a single file. I since saw some teams using https://github.com/maxdome/swagger-combine which looks like it could be perfect for the job.
