### ISSUE TITLE
[kubeapps-apis] Investigate provision of chart Readme and values

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2864]
### Description:

The fluxv2 backend that we'll be using for the plugin does cache the index.yaml for a chart repository nicely, but given its gitops use-case, does not extract or otherwise provide access to other metadata usually presented to users when viewing details of a chart for potential installation. We want to investigate possible options here, such as extracting and caching when a specific chart (version) details are requested, rather than having to extract all and store in a db like is currently done for the existing helm support.

@gfichtenholt Feel free to edit and fill in the details here, I'm just creating this so we can include it in the iteration plan (assuming it's going to be something you'll be working on).

**Comment by gfichtenholt** [comment]
yes, right on. I'll take it

**Comment by gfichtenholt** [comment]
Here is what I found out so far. Fluxv2 has two different CRDs: HelmChart and HelmRelease. One can create an instance of HelmChart in order to fetch (or pull) the chart contents locally to the cluster. E.g. having previously deployed 'bitnami' HelmRepository, I can create this object 
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: redis
  namespace: default
spec:
  chart: redis
  version: 10.5.x
  sourceRef:
    name: bitnami
    kind: HelmRepository
  interval: 10m
and I will end up with 
$ kubectl get helmchart
NAME    CHART   VERSION   SOURCE KIND      SOURCE NAME   READY   STATUS                      AGE
redis   redis   10.5.x    HelmRepository   bitnami       True    Fetched revision: 10.5.14   2m50s
and similarly to how the helmrepository object caches the index.yaml, the .tgz file for the chart will be cached (and updated at specified interval) locally in the cluster 
$ kubectl get helmchart/redis -o yaml
... skipping a lot of yaml
status:
  artifact:
    checksum: 440b4dd25710c3299bac0def9fd694ddfe684188
    lastUpdateTime: "2021-05-27T04:39:27Z"
    path: helmchart/default/redis/redis-10.5.14.tgz
    revision: 10.5.14
    url: http://source-controller.flux-system.svc.cluster.local./helmchart/default/redis/redis-10.5.14.tgz
  conditions:
  - lastTransitionTime: "2021-05-27T04:39:25Z"
    message: 'Fetched revision: 10.5.14'
    reason: ChartPullSucceeded
    status: "True"
    type: Ready
  observedGeneration: 2
  url: http://source-controller.flux-system.svc.cluster.local./helmchart/default/redis/redis-latest.tgz
  Notice the status.url field is pointing at locally cached file. 
  To actually install the redis chart I would need to create a HelmRelease object.

**Comment by gfichtenholt** [comment]
I think one question to ponder at this point is this: would it be acceptable UX flow-wise if when 
presented with a catalog of available packages and the user selects one then 

- - that results in a call to a back-end plugin which,
- - has to pull the specified chart via the mechanism I described above, 
-   which does take a second or two for flux to reconcile, then 
- - we process it (i.e. unzip/untar .tgz file) and only then 
- - return metadata which can be shown to the user. 
- 

 Meanwhile there is some sort of "Please wait while we are retrieving chart information..." 
 message shown on the page. That would only happen once per chart. The second time, 
 the chart has already been pulled down to the cluster, nothing for flux to do,
 so the wait is much shorter. 

Now as far as the actual API is concerned, it shouldn't really matter whether we 
retrieve the information on-the-fly or as part of some background sync task, the way 
asset-syncer works today. I don't see it changing what the API looks like. 
I have an idea for it written down, I just want to give some details some more thought and will 
propose something shortly.

**Comment by absoludity** [comment]
> and similarly to how the helmrepository object caches the index.yaml, the .tgz file for the chart will be cached (and updated at specified interval) locally in the cluster

That's quite neat (of fluxv2). It means we (well, the plugin) could also pre-populate helmcharts (using the latest minor version, as you've done) for a repository, if wanted?

> I think one question to ponder at this point is this: would it be acceptable UX flow-wise if when
> presented with a catalog of available packages and the user selects one then
> 
>     * that results in a call to a back-end plugin which,
> 
>     * has to pull the specified chart via the mechanism I described above, which does take a second or two for flux to reconcile, then
> 
>     * we process it (i.e. unzip/untar .tgz file) and only then
> 
>     * return metadata which can be shown to the user.
> 
> Meanwhile there is some sort of "Please wait while we are retrieving chart information..."
> message shown on the page. That would only happen once per chart. The second time,
> the chart has already been pulled down to the cluster, nothing for flux to do,
> so the wait is much shorter.

Yes, it sounds like that will be necessary. But this won't give us the available versions, right? I mean, if the catalog shows the latest version of redis (10.5.14), when selecting that package, we explicitly fetch with the version selector as 10.5.x (makes sense), but the result won't tell us the versions available, only the latest (which is usually what people will want to install, but they may also want the latest of a previous major/minor version)?

The current UX (not that it needs to be followed per se), enables people to choose any (maj.min.patch) version to install (which has its own problems - way too much info). The ideal IMO would be that a UX that presents the most recent major/minor by default (ie. 10.5.x), while ensuring that it's possible to select a previous major.minor version, with the ability to select patch versions too.

Anyway, I guess this will mean that we'll probably still need to be parsing the (cached) index.yaml to find the major/minor versions for presenting to the user? (ie. 10.4.x, 10.3.x, 9.8.x - just making these up).

> 
> Now as far as the actual API is concerned, it shouldn't really matter whether we
> retrieve the information on-the-fly or as part of some background sync task, the way
> asset-syncer works today. I don't see it changing what the API looks like.

:+1: 

> I have an idea for it written down, I just want to give some details some more thought and will propose something shortly.

Great.

**Comment by gfichtenholt** [comment]
I am currently writing code to prototype this. Its going slower than I'd hoped :-(
Lots of little issues to work through, but I'll get there

**Comment by gfichtenholt** [comment]
so I have a (sort of) working prototype now. The cost of a "worst" case scenario (described above) is  < 3s. See attached screenshot
<img width="1440" alt="Screen Shot 2021-06-01 at 7 50 11 PM" src="https://user-images.githubusercontent.com/74032303/120417105-2061b000-c313-11eb-8c81-b8cee933c138.png">

**Comment by gfichtenholt** [comment]
2nd and further calls (when flux HelmChart has already been pulled) is significantly faster
<img width="1154" alt="Screen Shot 2021-06-01 at 9 09 37 PM" src="https://user-images.githubusercontent.com/74032303/120422768-d6ca9280-c31d-11eb-9ab2-32d2833dcb71.png">

**Comment by absoludity** [comment]
Nice work! Wow, with the 27ms for the subsequent request... is that grabbing the local chart, extracting and getting the README? Or is the README somehow cached with flux?

**Comment by gfichtenholt** [comment]
nope, README is not cached, only .tgz file is. So 2nd time is just listing HelmChart CRD, finding one, getting the URL to .tgz file from it, extracting its contents and returning it to caller. All in 27 ms :-)

**Comment by gfichtenholt** [comment]
Apologies for long read. Feel free to quote and answer inline as there is a lot here :-)

Here are some thoughts I had about the API. I know you've also thought about the API and proposed something in google doc, these are just my thoughts to serve as fodder for further discussion
1. name: when you filed the issue, you've used both the term "metadata" and "details" to refer to
these package artifacts like (README, values.yaml, etc). I kind of liked the term _"metadata"_ at first
until I thought about it some more and realize the term _"metadata"_ probably would refer to things like
package size, create/modified date, user that created it, etc. All the kinds of things that you
might get with 'ls -l' command. Not the actual contents of the package. So I guess what I am saying
is now I would probably pick the term "details", which is what you have in the spec.

2. So the actual API is
```
   rpc GetAvailablePackageDetail(GetAvailablePackageDetailRequest) returns (GetAvailablePackageDetailResponse)
```
where GetAvailablePackageDetailRequest is as you have it defined in the doc. I don't really
understand a couple more fields in AvailablePackageReference, such as ```context``` and ```plugin```.
At this point I don't know enough about the gRPC plug-in machinery to argue whether or not these are needed, so I will take your word that they are :-). So I think we are on the same page when it comes to request. The response is where I see things can get more interesting so I split it off into separate item.

3. I see you currently have this
```
message AvailablePackageDetail {
  // A reference uniquely identifying the package.
  AvailablePackageReference package = 1

  // A url for an icon.
  string icon_url = 2;
  // A name as displayed to users
  String display_name = 3;
  // A short description of the app provided by the package
  String short_description = 4;
  // A long description of the package, such as a README formatted with Markdown.
  string long_description = 5;
  // A default configuration for the package, such as a values.yaml for a chart,
  // or an example
  string default_config = 6;

  // Maintainers for the package.
  message Maintainer {
    string name = 1;
    string email = 2;
  }
  repeated Maintainer maintainers = 7;

  // TODO: Define a summary of versions, but we'll need to be able to query
  // for more version details. Something like the following for the summary,
  // with example data of:
  // {
  //   "10.3": ["10.3.19", "10.3.18", "10.3.17"],
  //   "10.2": [...],
  //   "9.8": [...],
  // }
  // So it has some details of the last two minor versions as well as the
  // previous major version.
  message Versions {
    repeated string
  }
  map<string, Versions> version_summary = 8
}
```
Now let me point out that today, there are 3 or 4 pieces of information returned by such call:
in the same file (asset-syncer/utils.go):
 - chart.yaml
 - readme.md
 - values.yaml
 - values.schema.json
I am a little confused about chart.yaml because in one piece of code it is extracted from
the chart tarball and in another (within the same go file) it is not. (huh?)
Anyway, to get back to message definition, we could indeed define it the way you did,
I guess we would use:
  - longDescription for README
  - default_config for values.yaml
  - not sure where to hang values.schema.json and/or chart.yaml if needed. Please clarify.
Also, I have some confusion about why icon_url is present in both AvailablePackageSummary and AvailablePackageDetail message.
Also, why does AvailablePackageDetail have package versions information when you have a separate API for it GetAvailablePackageVersions?

To get back to the main message definition, this I would call "inflexible".
Inflexible because it assumes every plugin has these
same 3 or 4 pieces of information to deliver to caller and doesn't really leave room for
other things another plug in may want to deliver to the caller.

Something more flexible would be to allow each plugin to decide exactly what constitutes
the "details" and deliver that in some sort of
  - map<string, bytes> to be super flexible or
  - map<string, string> a little less so
form, where the string keys would be one of chart/readme/values/schema, at least for fluxv2 plugin.
Possibly we could use an enum type for the keys to provide some idea of what all is being returned.
That places the burden on the caller to figure out what to do with this information.

 Yet another option might be to have the caller explicitly ask for the piece(s) of metadata
 that it is interested in, i.e. GetAvailablePackageDetailRequest would have a string array
 argument (something like ["README.md", "values.yaml"]) in addition to the packageRef. Again, here
 the burden is on the caller to know what to ask for.

**Comment by absoludity** [comment]
> Apologies for long read. Feel free to quote and answer inline as there is a lot here :-)

No problem at alll :) When we chatted about where to put the info you had, I had misunderstood and thought you meant info related specifically to this investigation of the fluxv2 plugin, getting the chart details required and available packages, whether we might need to cache things etc.  If we're discussing the actual message formats etc., probably best to do that on the doc, but fine here too. Let me answer inline and we can move relevant bits to the doc?

> 
> Here are some thoughts I had about the API. I know you've also thought about the API and proposed something in google doc, these are just my thoughts to serve as fodder for further discussion

I'm currently just writing and adjusting while thinking things through in the doc, rather than proposing a final solution, so don't think of anything there as being what I think is a final solution... I just want to have enough that we can discuss it tomorrow. Please feel free to edit/suggest/comment as you like there.

[snip]
>  So I guess what I am saying is now I would probably pick the term "details", which is what you have in the spec.

Yep, great.

> 
>     2. So the actual API is
> 
> 
> ```
>    rpc GetAvailablePackageDetail(GetAvailablePackageDetailRequest) returns (GetAvailablePackageDetailResponse)
> ```
> 
> where GetAvailablePackageDetailRequest is as you have it defined in the doc. I don't really
> understand a couple more fields in AvailablePackageReference, such as `context` and `plugin`.

Let's chat tomorrow about why I think we need those... I don't mind changing if not.

> The response is where I see things can get more interesting so I split it off into separate item.
> 
>     1. I see you currently have this

[snip]

> Now let me point out that today, there are 3 or 4 pieces of information returned by such call:
> in the same file (asset-syncer/utils.go):
> 
>     * chart.yaml 
>     * readme.md
>     * values.yaml
>     * values.schema.json
>       I am a little confused about chart.yaml because in one piece of code it is extracted from
>       the chart tarball and in another (within the same go file) it is not. (huh?)

From a quick look, it seems that it's a difference between the `HelmRepo` and `OCIRegistry` implementations of the `Repo` interface. The `HelmRepo.FetchFiles` method does not extract the `Chart.yaml` as much of the info therein is actually already part of each entry in the helm repo's `index.yaml`, while the newer `OCIRegistry` implementation (and OCI registries of helm charts do not have any such `index.yaml`) has to extract `Chart.yaml` to populate many fields in the `models.Chart` struct, which for the `HelmRepo` case come directly from the `index.yaml`.

>       Anyway, to get back to message definition, we could indeed define it the way you did,
>       I guess we would use:
> 
>     * longDescription for README
> 
>     * default_config for values.yaml

Yes, I think so.

> 
>     * not sure where to hang values.schema.json and/or chart.yaml if needed. Please clarify.

Yes, I think it'd be worth adding a field for `config_schema` as it's an optional but generic concept which does make sense for different formats. Regarding the `Chart.yaml`, this is the chart metadata (you'll see it extracted as such in the existing code). If we later see a use for having `package_metadata` in the detail message, we can easily add it. I'm not yet sure that it does (especially unstructured). 

>       Also, I have some confusion about why icon_url is present in both AvailablePackageSummary and AvailablePackageDetail message.

Because it should be included in the response *somewhere* of both endpoints, as when viewing a list of package summaries (think catalog) the icon is important data for recognition, and when viewing the detail of a package, it's also important data for branding (I was wondering whether we might want/need an `icon_large_url` in the detail, some charts at least seem to use SVG, but we may not restrict the API to one).

That said, we could instead embed the `AvailablePackageSummary` within the `AvailablePackageDetail` so it's not defined twice, if you think. There are pro's and con's both ways, see this [Stackoverlfow question, first answer, and comments](https://stackoverflow.com/questions/63498495/how-to-reuse-fields-in-different-message-type) on the first answer for more context. I went for the simpler access (ie. `detail.icon_url` rather than `detail.summary.icon_url`) but don't care either way.

>       Also, why does AvailablePackageDetail have package versions information when you have a separate API for it GetAvailablePackageVersions?

If I ask "what details about an available package do I need decide and move forward with an install action", then I definitely want at least a summary of the version information to decide version or version range to which I want to restrict my install (ie. latest 10.x version, or latest 10.3.x patch version). But if the `AvailablePackageDetail` has only a summary of the version info, then we'll need another endpoint to query to get full information when required, I assume (maybe not, or maybe not initially), which is why I commented there that perhaps it'd be simpler initially just to present all versions but usefully formatted. I'm undecided personally - let's chat more about this on the doc or on our call.

> 
> 
> To get back to the main message definition, this I would call "inflexible".
> Inflexible because it assumes every plugin has these
> same 3 or 4 pieces of information to deliver to caller and doesn't really leave room for
> other things another plug in may want to deliver to the caller.

Right, where as we want to do something that is a mix of both, I think? That is, identify which data makes sense generally for any package format, even if not all formats use it (icon url, long description, default config starting point, possibly a schema to validate config?), while not limiting to that. So for example, the default config could be a `values.yaml` for a helm plugin, a `config.json` for another, and a `config.ini` for another - we're not restricting what that data is, just including it as it can be useful in a UX when installing a package. We may also need some free-form map as you have below, but:

> 
> Something more flexible would be to allow each plugin to decide exactly what constitutes
> the "details" and deliver that in some sort of
> 
>     * `map<string, bytes>` to be super flexible or
> 
>     * `map<string, string>` a little less so
>       form, where the string keys would be one of chart/readme/values/schema, at least for fluxv2 plugin.
>       Possibly we could use an enum type for the keys to provide some idea of what all is being returned.
>       That places the burden on the caller to figure out what to do with this information.

right, this is the key. I'm not against also including a map of sorts for extra non-generic details, but as much as possible, want to define the standard fields that make sense across all package formats (ie. long description rather than readme), so that a UX can treat the response generically as much as possible (ie. with the least burden on the caller). Does that sound reasonable?

> 
> Yet another option might be to have the caller explicitly ask for the piece(s) of metadata
> that it is interested in, i.e. GetAvailablePackageDetailRequest would have a string array
> argument (something like ["README.md", "values.yaml"]) in addition to the packageRef. Again, here
> the burden is on the caller to know what to ask for.

Possibly, though since this is a request for the detail of *one* and only one entity, it'd be a later optimisation when needed (as in, I think it's fine initially to just include all details for now). Also, same reasoning about wanting the least burden on the caller above.

Note: on a related point, things like long description (readme), or even icon, are actually stored per versioned artifact in a repository, at least for helm, (and can differ even across point versions, though usually don't). I'll try to update the request proposal to handle this for discussion tomorrow.

Looking forward to discussing more details tomorrow :)
