### ISSUE TITLE
Feature request: Provide custom values file for AppRepository

### ISSUE THREAD

**Issue by frank-bee** [kubeapps/kubeapps#2916]
It would be great to allow providing a custom values file for an AppRepository if the main values.yaml file of the underlying helm repo does not fit ones needs.

**Comment by antgamdia** [comment]
Hi, thank you for the suggestion!
Which kind of custom values are you thinking of?  Could you elaborate a little bit more on your use case?

For instance, some weeks ago, we got a PR adding the  `description` field: https://github.com/kubeapps/kubeapps/pull/2787/files
(it was a bit more difficult because it also changed the UI, since we wanted to print the description in the AppRepositories view)

We're open to any contributions if you want to step in :)

**Comment by absoludity** [comment]
> It would be great to allow providing a custom values file for an AppRepository if the main values.yaml file of the underlying helm repo does not fit ones needs.

Hmm... it sounds like you might be confusing the values.yaml associated with each *chart*, rather than a repo (I'm not aware of a values.yaml file associated with a repo). We do have an existing issue open for allowing multiple `values.yaml` files for a chart and exposing them in Kubeapps, in #859 , but as mentioned in the last comment, there's no standard for this in the charts themselves, and Bitnami had stopped supporting this in the chart publishing.

**Comment by frank-bee** [comment]
hi guys, thanks for you quick replies first of all!

@absoludity : You are right , my description was wrong and the issue #859 is similar to what we need. 
I close this issue here and comment on the other one.
