### ISSUE TITLE
Detect 401 errors and prompt to logout and login again

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#294]
Currently if your token becomes invalid you will start seeing the generic "Sorry! Something went wrong" errors. We should be able to detect 401 errors and show a different error message that explains that the token is no longer valid and the user should log out and log back in again.

**Comment by sameersbn** [comment]
This issue is mainly observed if the existing auth token is no longer valid. Instead of asking the user to logout/login we decided to instead automatically log out the user and present the login page.

**Comment by migmartri** [comment]
From my point of view there are two main orthogonal tasks

### 1 - Capture 401s for all API calls

This could be implemented by using an axios interceptor that on 401s will `delete value in localStorage, `store.dispatch(setAuthenticated(false))` and redirect to login`

### 2 - Create a high order component wrapping the authenticated bits

This high order component will:

* Check if there is a token stored, if it's not, redirect to login
* If there is a token, validate that is valid
  * If it is, store.dispatch(setAuthenticated(true)) and render the wrapped components.
  * If if is not valid, delete value in localStorage, `store.dispatch(setAuthenticated(false))` and redirect

### Why not just implementing 1?

Although it is true that implementing just 1 will solve our current issue (accepting as valid a stored token that's not), the creation of a high order component will prevent parts of the app to be rendered before the redirection happens. Improving both the user experience (we can show a message saying logging in) and the app simplicity since we will be able to know that an user is logged in regardless of being in a component that relies on a k8s API call. For example, implementing just 1, will redirect the user on apps/list but not in charts/list, which can be potentially confusing.

So my take would be to implement both approaches but starting with 1, as a standalone unit.

WDYT?

**Comment by prydonius** [comment]
I agree that a higher order component similar to the ConfigLoaderContainer will be useful, but we should tackle that in a separate issue (possibly still within this iteration). We should get 1 implemented and merged in sooner so we can cut a release with that fix for now.

**Comment by andresmgot** [comment]
I am okay with the approach as well.

> For example, implementing just 1, will redirect the user on apps/list but not in charts/list, which can be potentially confusing.

If that is true I think this issue cannot be considered solved until 2. is implemented. We cannot know in which view the user will be.

**Comment by prydonius** [comment]
Today we fetch the namespaces on the first page load and this call will 401 if you have an invalid token, so I think it is okay for a first fix (it's still better than what we have now).

**Comment by migmartri** [comment]
This change in any case does not make it less secure, it does not make it more secure either, just improves usability so it is a good thing to remember.

**Comment by andresmgot** [comment]
👍  thanks for the following-up issue
