### ISSUE TITLE
[kubeapps-apis] Update the messages in each operation 

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2945]
Update the existing kubeapps-apis demo code to use the messages from the design doc (ie. Context, AvailablePackageReference etc. etc.).

Note that the message definition is an ongoing task, so the updates in the code will appear after we reach an agreement on the design doc.

**Comment by absoludity** [comment]
@antgamdia We've just agreed on the naming of `AvailablePackage` and `InstalledPackage`, so feel free to start this. I'd suggest the following (so that no-one is blocked):

1. Update the existing messages and server in the core.packaging.v1alpha1 package and generate. Propose and land this even though it breaks the two existing plugins (they won't build)
2. Then kapp-controller and fluxv2 can be updated independently, whether you do both or whether greg updates fluxv2.

Just note that the kapp-controller plugin is still on a previous alpha version (so may be tricky to test IRL unless we've access to a demo repo from the same alpha version), but just updating the tests is fine for now, imo, until we later updated to something more stable (if it's worthwhile).

**Comment by antgamdia** [comment]
> Then kapp-controller and fluxv2 can be updated independently, whether you do both or whether greg updates fluxv2.

Initial draft at #2945

**Comment by antgamdia** [comment]
Moving to "committed" to continue working on that once we agree on the new names, but I'm also ok closing it and creating a new issue for each batch of renames

**Comment by antgamdia** [comment]
Closing as we already performed the changes in the already implemented logic. Remaining things in the design doc haven't been implemented yet.
