### ISSUE TITLE
Unable to retrieve API info: service unavailable

### ISSUE THREAD

**Issue by haolixu** [kubeapps/kubeapps#2963]
### when i installed kubeapp,Opened the system port，Login with browser，Encountered the following error：
![avatar](https://gitee.com/haolixu/test/raw/master/%E5%A4%A7%E6%96%87%E4%BB%B6/1.png)

**Comment by antgamdia** [comment]
Hi, @haolixu, thanks for using Kubeapps.

It seems Kubeapps is being unable to connect to the k8s API. I'd bet this is a problem caused by a lack of resources (cpu, mem) that is making a pod continuously reboot, and, sometimes you lost access. But, let's check it.

Could you share the output of  `kubectl get pods --namespace kubeapps` ? Also, please open your browser's network inspector tab and let us know which HTTP request is failing.

**Comment by haolixu** [comment]
> 嗨，@haolixu，感谢您使用 Kubeapps。
> 
> Kubeapps 似乎无法连接到 k8s API。我敢打赌，这是由于缺乏资源（cpu、mem）导致 pod 不断重启导致的问题，有时您会失去访问权限。但是，让我们检查一下。
> 
> 你能分享输出 `kubectl get pods --namespace kubeapps`吗？另外，请打开浏览器的网络检查器选项卡，让我们知道哪个 HTTP 请求失败。

### This is the information you need:
![avatar](https://gitee.com/haolixu/test/raw/master/%E5%A4%A7%E6%96%87%E4%BB%B6/2.png)
![avatar](https://gitee.com/haolixu/test/raw/master/%E5%A4%A7%E6%96%87%E4%BB%B6/3.png)
### I am using k3s, the following is my system version information：
![avatar](https://gitee.com/haolixu/test/raw/master/%E5%A4%A7%E6%96%87%E4%BB%B6/4.png)
