### ISSUE TITLE
Define default dashboard theme from helm

### ISSUE THREAD

**Issue by aanthonyrizzo** [kubeapps/kubeapps#3176]
## Ask
Instead of letting `window.matchMedia("(prefers-color-scheme: dark)")` determine the default theme on first load I was wondering if it would be possible to set a preferred default in the `values.yaml` file and pass it to the frontend in `config.json`. Behavior would be if `Values.dashboard.theme` is set, default to that, otherwise utilize `window.matchMedia`

## Implementation Question
I am willing to take ownership of this feature but looking through the codebase I haven't identified an ideal place to make this work. It appears that the theme is set before the request for the config is fired. Any help would be greatly appreciated

**Comment by absoludity** [comment]
Hi @aanthonyrizzo . Thanks for being willing to have a go at making this work.


> ## Ask
> 
> Instead of letting `window.matchMedia("(prefers-color-scheme: dark)")` determine the default theme on first load I was wondering if it would be possible to set a preferred default in the `values.yaml` file and pass it to the frontend in `config.json`. Behavior would be if `Values.dashboard.theme` is set, default to that, otherwise utilize `window.matchMedia`

Sounds reasonable :)

> ## Implementation Question
> 
> I am willing to take ownership of this feature but looking through the codebase I haven't identified an ideal place to make this work.

No doubt you've already seen the matchMedia being used in the [shared/config.ts](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/shared/Config.ts#L29) module? That stanza would be the place to instead use the config value if set, before defaulting to the matchMedia (which if not set, then defaults to light). The `IConfig` interface there would be updated to include the new config option too.

> It appears that the theme is set before the request for the config is fired.

Right, so this is the [HeaderManager](https://github.com/kubeapps/kubeapps/blob/master/dashboard/src/components/HeadManager/HeadManager.tsx#L31) which calls `actions.config.getTheme()` (which in turn calls `shared.getTheme()`), updating the redux state very early, before the config.js has even been loaded as you mention. This allows the dashboard to use the theme stored in the local storage (if the user has previously set the theme) or the matched theme from the browser without any visible flicker, I assume.

So with your addition, the when a user loads Kubeapps in their browser, if they have not previously explicitly set a theme themselves, it may switch from the browser detected theme used when the HeaderManager loads, to the one set from the config (if you update so that the theme gets set when the config loads).

I think this is OK and a good first step. You or we can later, if required, update the HeaderManager so that it displays something temporary until the config is loaded, but I'm not sure that will be necessary.

Let's see what Antonio thinks too, as he has lots of JS experience :)

> Any help would be greatly appreciated
