### ISSUE TITLE
Redirect to DeploymentForm when chart is missing README

### ISSUE THREAD

**Issue by aanthonyrizzo** [kubeapps/kubeapps#3226]
Hi guys, me again :)

### Proposal
When there are  helm charts w/out a README users a greeted w/ a blank page that doesnt seem to provide much value (just some 'no README' text and the version controller dropdown). 
![image](https://user-images.githubusercontent.com/36711320/127691656-0dbe48d3-e33c-4f05-9e7f-966386af1a44.png)
I was wondering how you guys would feel about just doing a direct link to the deployment form when there is no README for the associated chart.

As of right now I don't see any real drawbacks from making this the default behavior but feedback is greatly appreciated. As per all of my issues/feat requests, Im willing to take ownership of this feature.

**Comment by antgamdia** [comment]
Hi @aanthonyrizzo, thanks for your ideas and for jumping in with the PR. I personally see it as a UX improvement in that we get rid of a meaningless view if there is no info to show. Let's see what  @absoludity thinks. 
I'll eventually have a closer look at your PR, but at a glance, it seems OK (and you also added the proper unit tests :)  ).
However, please note that we probably will be off during the upcoming week so it may take a little bit longer.
Thanks for your contributions!

**Comment by absoludity** [comment]
Hmm. If I look at the Catalog, find a chart that could suite my needs, I click on it to find out more before I deploy. The issue here is that the chart in question doesn't have a readme so you don't actually find out more, right? But you still then make the decision to deploy or go back to the catalog, and the fact that the chart doesn't even have a readme is helpful info for making that decision IMO. I'm not sure that clicking on a chart tile in the catalog should go straight to the deploy page, but I'm not against it necessarily.

My main question is: why isn't the solution here to add a readme to the chart? Any chart that is in a public catalog will always have one. If this is a chart in a private catalog, then sure, you're not forced to have a readme, but without one it's hard for a user to make an install decision on only the name.  So, why not add a README to solve this, even if it has a single sentence? I'm just a bit hesitant to add support for something that lowers the user experience (as in, I'd be happier for users to have to see "oh, this chart doesn't even have a readme to tell me what it does" - that gives you some info for your install decision).

Thoughts? Or can you describe a bit more about your use-case for publishing charts without readmes? Thanks!

**Comment by aanthonyrizzo** [comment]
We heavily leverage custom Kubeapps components in our charts, and our charts are intended to only be deployed via Kubeapps. With the custom component, we can add helpful text together with the deployment values providing a more cohesive experience than first showing a bunch of information that we also might have to repeat on the Deploy page so the user doesn't have to go back/forth.

Another thing that this PR will allow us to do is directly link to the deployment form for a chart without having to know the latest chart release tag. At the current moment it is impossible to just link directly to the deployment form w/out having the version number in the query string.

**Comment by absoludity** [comment]
> We heavily leverage custom Kubeapps components in our charts,

Do you mean custom versions of components like the dashboard and/or kubeops service etc? If so, keen to hear more - must be hard to keep them in sync or are they only small changes? Note that we'll soon be landing significant  changes in the dashboard to start using some new, well-defined API endpoints.

> and our charts are intended to only be deployed via Kubeapps. With the custom component, we can add helpful text together with the deployment values providing a more cohesive experience than first showing a bunch of information that we also might have to repeat on the Deploy page so the user doesn't have to go back/forth.

That's really interesting... and possibly something worth considering more generally if you wanted to. I totally agree that the info presented when showing the details of a chart is relevant when actually installing. No problem if it's not something you want to share, but otherwise a screenshot would be really interesting.

> 
> Another thing that this PR will allow us to do is directly link to the deployment form for a chart without having to know the latest chart release tag. At the current moment it is impossible to just link directly to the deployment form w/out having the version number in the query string.

Yeah, makes sense: you mean that you can link to the chart details page and it'll automatically redirect to the deployment form with the latest version with your change? Yep, but it'd also be good to enable the deploy page to do this so we wouldn't need a redirect.

Thanks for providing the details. With those in mind, I think a more generic solution that doesn't depend on charts not having readmes would be:

1. Update the deploy form so that it can be linked to directly (and will just display with the most recent version by default), and then
2. Add a config option, `skipAvailablePackageDetails` which defaults to `false` to keep the current behaviour, but when true, the tiles presented in the catalog link directly to the deploy form.

WDYT?

**Comment by aanthonyrizzo** [comment]
![image](https://user-images.githubusercontent.com/36711320/128894827-e39e17b8-040b-4686-a330-8113e98660df.png)
So this is an early example of the custom components that we built. Its still missing some of the copy that we want to add but it allows us to add any subtext that could be required. As it evolves we'll add tooltips and help modals as well to help guide users through the deployment. (Im also in the kubeapps slack if you want to chat more about the custom form components that we've built).

> Update the deploy form so that it can be linked to directly (and will just display with the most recent version by default), and then

Sounds good to me 👍 . Would you like me to include this in #3227 or do you think this should be done in a different PR? 

> Add a config option, skipAvailablePackageDetails which defaults to false to keep the current behaviour, but when true, the tiles presented in the catalog link directly to the deploy form.

Perfect, I will update the #3227 to use a config var.

**Comment by absoludity** [comment]
Great, thanks for the extra info. Interesting to see what you're doing with Kubeapps :) Just coming back off some leave, so catching up with PRs but will get to it asap.

**Comment by absoludity** [comment]
> Sounds good to me +1 . Would you like me to include this in #3227 or do you think this should be done in a different PR?

So yes, I'm keen that we don't land #3227 as is (ie. don't depend on the README being present or not), but rather do:

> * Update the deploy form so that it can be linked to directly (and will just display with the most recent version by default), and then
> 
> * Add a config option, `skipAvailablePackageDetails` which defaults to `false` to keep the current behaviour, but when true, the tiles presented in the catalog link directly to the deploy form.

I don't mind whether you update #3227 to that, or just to the first point, then do a second PR with the second point (the second depends on the first though).

Thanks!
