### ISSUE TITLE
FEATURE REQUEST: Store values.yaml on Git

### ISSUE THREAD

**Issue by Ogguz** [kubeapps/kubeapps#3236]
### Description:

It is possible to rollback the last change on values.yaml, but it is not easy to track why that change is made and who made it especially in large teams. So it will be nice to have an option to store values.yml on git.

Something like this will be beneficial;
1- On kubeapps values.yaml "enable" store values.yaml on git and then provide the URL.
2- Provide access to that git repo
3- After first installation kubeapps will create the values.yaml file on the git repo.
4- Whenever a change is a made, kubeapps will commit those changes with user information in commit message.

What do you guys think?

**Comment by absoludity** [comment]
Hi there @Ogguz . I think the idea for auditing changes to the values is a good one, but I don't think Kubeapps should be pushing the values to git necessarily. People can do the reverse for a more gitops approach (ie. have the values in git, use flux to deploy whenever the git values change, we're planning flux support currently in Kubeapps too).

The full values.yaml is stored currently by Helm for each release (See https://helm.sh/docs/helm/helm_get_values/ ), but as you say, what's missing there is any auditing of *who* made the change. This isn't part of helm since helm is a CLI not designed for multi-tenancy per-se.

We do have a separate issue #2393 for improving auditability. Let me know if this separate auditing would fit your needs or not.
