### ISSUE TITLE
Create the "kubeappsapis" official component 

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#3246]
Create the oficial "kubeappsapis" component in the Bitnami chart pipeline.

**Comment by antgamdia** [comment]
Just for giving more context: 

- This new component is yet another golang piece of code, so nothing new here.

- The dockerfile is located at https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/Dockerfile, there is all the required tech information.
(question here, @absoludity , how Bitnami should address the plugin compilation? I guess they should package all the default ones we currently provide, (that is, no special logic on their side to selectively compile them) shouldn't they?)

- Note that we are using the go `plugin` buildmode, that is, we have a main binary that is dynamically linking the `xxxx-plugin.so` files. For that reason, we are using a `minideb` base image instead of `scratch`.

**Comment by absoludity** [comment]
> Just for giving more context:
...
>       (question here, @absoludity , how Bitnami should address the plugin compilation? I guess they should package all the default ones we currently provide, (that is, no special logic on their side to selectively compile them) shouldn't they?)

Correct. This will enable us to configure which plugins should run (and test out the ones that are not yet finished).
