### ISSUE TITLE
Make a Helm Chart for Kubeapps

### ISSUE THREAD

**Issue by desaintmartin** [kubeapps/kubeapps#325]
I think many people would actually want to manage their Kubeapps installation using... Helm itself.
Today, "kubeapps up" seems too intrusive to me and having a way to track/upgrade all (most?) resources installed by kubeapps would be a nice feature, or even easily changing the installed resources (ingress, etc). Fortunately, Helm has already all we need to write a Chart!

What do you think?

**Comment by arapulido** [comment]
Thanks for the suggestion, @desaintmartin ! Yes, this is something we have been discussing and plan to work on. Let's use this issue to track this. Thanks!

**Comment by prydonius** [comment]
One issue with this is that `kubeapps up` installs Helm CRD (https://github.com/bitnami-labs/helm-crd) which bundles it's own Tiller. We can modify this in the chart so that there's a value that lets you point to the existing Tiller installation.

**Comment by prydonius** [comment]
Started working on this and one issue I noticed with the AppRepository component is that Helm charts don't allow you to create the CustomResourceDefinition AND the resources themselves. The chart fails validation and complains that the CRD Kind doesn't exist (which makes sense because it hasn't been created yet). The issue is tracked in https://github.com/kubernetes/helm/issues/2994.

I have asked for guidance in #helm-users in slack, but in the meantime I will solve this by only creating the repos on `helm upgrade`.

**Comment by arapulido** [comment]
@prydonius let's not spend too many cycles on this just yet, until we figure out what we are going to do with HelmCRD, please.

**Comment by prydonius** [comment]
Just putting this here so we don't forget when we look into this again, Helm master (not yet released) add support for a `crd-install` hook that runs before validation - https://docs.helm.sh/developing_charts/#defining-a-crd-with-the-crd-install-hook.

**Comment by prydonius** [comment]
We should consider implementing some of the installations options described in #91 and #228 as part of this.
