### ISSUE TITLE
Unable to upgrade Helm release for chart without appVersion

### ISSUE THREAD

**Issue by dud225** [kubeapps/kubeapps#3253]
### Description:
I've successfully installed a Helm release from a chart stored on an OCI repository, however I'm not able to upgrade it from Kubeapps. I've also tested to store the chart on a Chartmuseum repository and the upgrade fails in the same way.
When clicking on upgrade, the page starts loading and then hangs, the loading wheel is spinning forever:
![kubeapps_keeps_spinning](https://user-images.githubusercontent.com/17550475/128905424-4d7f5ffb-2a9c-4855-a887-1a713cb737ec.png)

When looking at the browser console and the network requests, I don't notice any failure. The page just stops issuing requests at some point. Looking at the Kubeapps logs doesn't show any error: [kubeapps_logs.txt.gz](https://github.com/kubeapps/kubeapps/files/6963341/kubeapps_logs.txt.gz)

Upgrading the Helm release from the command line works fine.
Upgrading a release steming from another chart, Kubeapps which comes from the Bitnami repository, works fine from Kubeapps.

### Steps to reproduce the issue:

1. Set up a local OCI or Chartmuseum repository
2. Upload the `etcd-debug` chart attached: [etcd-debug.tar.gz](https://github.com/kubeapps/kubeapps/files/6963383/etcd-debug.tar.gz)
3. Install a new release from Kubeapps
4. Upgrade it from Kubeapps

### Additional information you deem important:

The following trivial chart didn't experience the issue: [trivial.tar.gz](https://github.com/kubeapps/kubeapps/files/6963389/trivial.tar.gz)

so it doesn't seem to be related to the repository type.

### Version of Helm, Kubeapps and Kubernetes:

 I'm been facing the issue on the latest version of Kubeapps:
* App Version: 2.3.3
* Chart Version: 7.1.8

I have also tested a previous version but it didn't help:
* App Version: 2.2.1
* Chart Version: 5.3.4

I'm using microk8s v1.21.3.

Output of `microk8s.helm3 version`:
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

- Output of `microk8s.helm3 list -n <kubeapps-namespace> <kubeapps-release-name>`:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        27              2021-08-06 09:14:32.276950409 +0000 UTC deployed        kubeapps-7.1.8  2.3.3
```

- Output of `microk8s.kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-3+90fd5f3d2aea0a", GitCommit:"90fd5f3d2aea0a5788b15a6f0a05e70381af7787", GitTreeState:"clean", BuildDate:"2021-07-16T22:06:06Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-3+90fd5f3d2aea0a", GitCommit:"90fd5f3d2aea0a5788b15a6f0a05e70381af7787", GitTreeState:"clean", BuildDate:"2021-07-16T22:01:05Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by antgamdia** [comment]
Thanks for the information! We recently got another issue also related to the upgrading process (https://github.com/kubeapps/kubeapps/issues/3213) (not sure if they're related). Will have a look at it once we have some bandwidth!

**Comment by absoludity** [comment]
> Thanks for the information! We recently got another issue also related to the upgrading process (#3213) (not sure if they're related). Will have a look at it once we have some bandwidth!

It's not related. Thanks for the demo files, I was able to reproduce. This is specifically a UX issue related to the chart in question which doesn't define an appVersion in the Chart.yaml. The `appVersion` field in the Chart.yaml is optional, but it appears that Kubeapps depends on it. We should not.

In particular, when clicking on `Upgrade`, Kubeapps queries the chart metadata to find the chart matching the chart name, chart version and app version used for the selected app, but in this case, because the app version is undefined, it's explicitly using `appVersion=undefined` in the query:

![appversion-undefined](https://user-images.githubusercontent.com/497518/129506415-6f48b6d2-a0e3-489b-8b6a-c895e196fbd5.png)

It should instead be querying without the app version, which returns the expected data, like this: (I edited the query removing the `appVersion=undefined` arg)

![appversion-not-specified](https://user-images.githubusercontent.com/497518/129506508-8cb9fe13-14c0-448e-b905-68c4d52ca8dd.png)

This is also the reason it worked fine with your trivial.tar.gz, since it does define the app version.

Can you confirm that this works fine if your etcd chart defines the appVersion in the Chart.yaml? Kubeapps still needs to handle this, but it's much lower priority then a general issue :)

Thanks!

**Comment by dud225** [comment]
I confirm that setting the field `appVersion` works around this issue. Thanks for the detailed explanation.
