### ISSUE TITLE
clusterrole: view does not work with kubeapps

### ISSUE THREAD

**Issue by AKU01** [kubeapps/kubeapps#3344]
clusterrole: view does not work with kubeapps
-------------------------------
    BUG REPORT INFORMATION
-------------------------------

### Description:

we created two role-bindings  kubeapp:ns-write and kubeapp:ns-read.
and two groups: Ns_Write and Ns_Read as described below

when logged-into kubeapps with  Group: Ns_Write, it works well, no issue.

but when logged-into kubeapps dashboard.with user in Group: Ns_Read gets message:
.. not have access to any namespace..

 kubeapp:ns-write.yaml
------------------------------
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps:ns-write
  namespace: ns
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: Ns_Write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
-----------------------------

 kubeapp:ns-read.yaml
------------------------------
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps:ns-read 
  namespace: ns
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: Ns_Read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

### Describe the results you received:
user in Group: Ns_Read logged-in but
User does not  have access to any namespace

### Describe the results you expected:
user in Group: Ns_Read should have view only access to the application deployed in the namespace.

**Comment by absoludity** [comment]
Hi there @AKU01 . The error message you are seeing: "The current account does not have access to any namespaces", is displayed when neither the logged-in user nor the service account with which the Kubeapps backend is running has the required RBAC to list namespaces.

Note that listing namespaces is a cluster-level request, so for your ns-write rolebinding, you bind `cluster-admin` which obviously can read namespaces, but because it's a rolebinding (not a clusterrolebinding), that specific role binding only allows reading namespaces in the `ns` namespace.

Note, you can test all this using impersonation with the `kubectl` CLI. For example, using a user and the default namespace:

```bash
$ cat <<EOF | kubectl apply -f -
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps:ns-write
  namespace: default
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: test-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
EOF
rolebinding.rbac.authorization.k8s.io/kubeapps:ns-write created

$ kubectl --as test-write get namespaces
Error from server (Forbidden): namespaces is forbidden: User "test-write" cannot list resource "namespaces" in API group "" at the cluster scope

$ kubectl --as test-write get namespace default 
NAME      STATUS   AGE
default   Active   5d

$ kubectl --as test-write get namespace kubeapps
Error from server (Forbidden): namespaces "kubeapps" is forbidden: User "test-write" cannot get resource "namespaces" in API group "" in the namespace "kubeapps"
```

Your ns-read rolebinding should allow the same (ie. reading just the one namespace, but not namespaces across the cluster):

```bash
$ cat <<EOF | kubectl apply -f -kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps:ns-read 
  namespace: default
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: test-read 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view         
EOF
rolebinding.rbac.authorization.k8s.io/kubeapps:ns-read created

$ kubectl --as test-read get namespace default
NAME      STATUS   AGE
default   Active   5d

$ kubectl --as test-read get namespace kubeapps
Error from server (Forbidden): namespaces "kubeapps" is forbidden: User "test-read" cannot get resource "namespaces" in API group "" in the namespace "kubeapps"
```

So, can you please test your RBAC permissions using the `kubectl` CLI. In your case, since you're using groups rather than users, you should be able to do something like `kubectl --as-group "kubeapps:ns-write" get namespaces`. I'm guessing you'll find that you've some other RBAC for that group which is allowing getting namespaces at the cluster scope.

Let us know :)

**Comment by absoludity** [comment]
And sorry, in case it wasn't clear above, if you create a `ClusterRoleBinding`, rather than a `RoleBinding` (which is just for a specific namespace), then you should find your reader can get namespaces at the cluster level. For example:

```bash
$ cat <<EOF | kubectl apply -f -kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps:ns-read
  namespace: default
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: test-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
EOF

$ kubectl --as test-read get namespaces
NAME                      STATUS   AGE
default                   Active   5d
dex                       Active   5d
ingress-nginx             Active   5d
kube-node-lease           Active   5d
kube-public               Active   5d
kube-system               Active   5d
kubeapps                  Active   5d
kubeapps-user-namespace   Active   5d
ldap                      Active   5d
local-path-storage        Active   5d
```

**Comment by absoludity** [comment]
I'm going to close this with that info, assuming that the `ClusterRoleBinding` will fix the behaviour you saw. But if not, please re-open with more detail. Thanks!
