### ISSUE TITLE
Helm CRD as optional item (Proposal)

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#337]
Right now Helm CRD is a hard requirement for Kubeapps. While this brings many benefits, it is a bit confusing for people coming from the Helm community (they are already using Helm and want Kubeapps to manage their releases).

We are improving the situation a bit working on ways for Kubeapps to see helm releases and import them, but once imported, people need to manage them with Helm CRD and/or Kubeapps.

Let's come up with a proposal we can discuss about Helm CRD being optional, and allow people to make the decision on whether to use it or not

**Comment by prydonius** [comment]
One way to make Option 1 more secure is to leverage [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) along with nonResourceURLs rules in a ClusterRole to configure RBAC access to the Swift API. See https://github.com/brancz/kube-rbac-proxy/tree/master/examples/non-resource-url for an example of how this works.

This might be a very good option, although we still need a way to find the chart repository in order to know what to upgrade to and what icon to show. I suggested a workaround in my previous comment for the upgrade form (allow the user to select the chart in that form). A workaround for the icon could be to find a chart with the same name in any repo and use the first icon we can find. I think this would be reasonable (e.g. WordPress will likely have the same logo in all repos).

The nonResourceURLs rules can only exist in ClusterRoles, so there's no way of making sure a user only creates a Helm release in namespaces they have been allowed to, or only see the Helm releases in the namespaces they have been allowed to. The rule will work cluster-wide and they will be able to see everything. However, given that this is essentially how the Helm CLI works, this might be okay. We may be able to solve this in the future by supporting namespaced Tillers.

This is how I think we can make Option 1 workable without opening a huge security hole and reusing some of the auth features we implemented, however I'm still not sure whether we should do it instead of Option 2.

**Comment by andresmgot** [comment]
I think the idea here is to have two options:

 - Use (external) tiller and remove helm CRD. We don't need to secure this option. This is just for people that want to see/upgrade/delete their tiller releases with Kubeapps.
 - Use kubeapps tiller and helm CRD to obtain security/multi-tenancy. This would be our recommended setup. Just like the way we have now and maybe some additional security measures.

Another option would be to make `helm-crd` transparent to the user so any change made with helm CLI is reflected in the `HelmRelease`. That would mean we need synchronization between those two.

> Monocular shows icons for Tiller releases by hot-linking to the icon listed in the Chart's Chart.yaml. I don't recommend we do this

Why you don't recommend this, because of performance?

**Comment by prydonius** [comment]
IMO we should think really hard before supporting two different ways to create/update/delete Chart releases.

> I agree with the concern of not being able to upgrade a chart if it is not through helm-crd

Well, we also cannot create or delete charts without implementing/using some sort of client for Helm.

> Another option would be to make helm-crd transparent to the user so any change made with helm CLI is reflected in the HelmRelease. We could do that synchronizing the status between both objects.

This is my option 2 above.

> Why you don't recommend this, because of performance? AFAIK we already obtain that information when listing the apps.

Specifically, I recommend not hot-linking to the icon URL listed in Chart.yaml. For listing the charts we show the processed icon (downloaded and stored in MongoDB during repo sync), and we _should_ do the same when listing the apps (the issue is we need to find the associated chart to get the icon URL).

**Comment by andresmgot** [comment]
That sounds right. I will gather a quick discussion document and share it with you.

**Comment by andresmgot** [comment]
The discussions have been taken over this document:

https://docs.google.com/document/d/1FPqs5o7vDjKi5icB9XStmXQLeBViljn89ovhtorR3cA

As a very brief summary, we will migrate from Helm CRD to a REST API working as a proxy to Tiller. We can implement the security features (right now present in helm-crd) in this proxy. The goal is to maintain the applications state in just one place (Tiller).

**Comment by prydonius** [comment]
I think since the design is being implemented we can close this out.
