### ISSUE TITLE
Add proper request logging middleware or similar for kubeapps-apis

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3385]
Currently nothing is written for each request itself.

_Originally posted by @ absoludity_

Edit:

This issue is rather wide, depending on what we focus on. I don't know what Michael's idea is, but as far as I see it:

- The error messages that are displayed to the client is not the best. We are just aggregating the error chain like: "there is an error: error while doing X: error calling Y: error whatever", instead of "error: the user is not allowed to perform the action X". This is not a matter of adding a logging interceptor, but just making the top-level error messages (those returned to the users) a little bit clearer.
- The plugins are defining, right now, their own login system (klog, logrus, etc), but, for the sake of standardizing these common aspects for the plugins, the main server should pass a pre-configured logger (as we are passing the k8s clients or the token), so the plugins only have to use it for printing mgs.
    - An idea is using this project: https://github.com/grpc-ecosystem/go-grpc-middleware  as it provides middleware for not only logging, but any other future thing we might want to tackle in the future (like rate limiting).

**Comment by absoludity** [comment]
@satya-dillikar

**Comment by satya-dillikar** [comment]
> Currently nothing is written for each request itself.
> 
> _Originally posted by @ absoludity_
> 
> Edit:
> 
> This issue is rather wide, depending on what we focus on. I don't know what Michael's idea is, but as far as I see it:
> 
> * The error messages that are displayed to the client is not the best. We are just aggregating the error chain like: "there is an error: error while doing X: error calling Y: error whatever", instead of "error: the user is not allowed to perform the action X". This is not a matter of adding a logging interceptor, but just making the top-level error messages (those returned to the users) a little bit clearer.

@antgamdia, Please share an example of the real error, so that I can recreate what you are saying here with X & Y. and evaluate if we can make it better.

> * The plugins are defining, right now, their own login system (klog, logrus, etc), but, for the sake of standardizing these common aspects for the plugins, the main server should pass a pre-configured logger (as we are passing the k8s clients or the token), so the plugins only have to use it for printing mgs.
@antgamdia, Please share the piece of code where we are passing the k8s clients or the token. I would like to see what you thinking here.

>   
>   * An idea is using this project: https://github.com/grpc-ecosystem/go-grpc-middleware  as it provides middleware for not only logging, but any other future thing we might want to tackle in the future (like rate limiting).

@absoludity,  do we really need any middleware or can we just have server-side and client-side gRPC Interceptors (UnaryClientInterceptor, UnaryServerInterceptor)  calls to log the activity or authorize the func?

**Comment by absoludity** [comment]
> > Currently nothing is written for each request itself.
> > _Originally posted by @ absoludity_
> > Edit:
> > This issue is rather wide, depending on what we focus on. I don't know what Michael's idea is, but as far as I see it:
> > 
> > * The error messages that are displayed to the client is not the best. We are just aggregating the error chain like: "there is an error: error while doing X: error calling Y: error whatever", instead of "error: the user is not allowed to perform the action X". This is not a matter of adding a logging interceptor, but just making the top-level error messages (those returned to the users) a little bit clearer.
> 
> @antgamdia, Please share an example of the real error, so that I can recreate what you are saying here with X & Y. and evaluate if we can make it better.

It's not about a specific error, but rather, whenever an error is occuring in the kubeapps-apis codebase, we are usually wrapping (or appending to the error) and returning the error up the chain, until that error is returned as the handler response. So they end up being very user-unfriendly messages. We're doing the correct thing by wrapping and passing up the chain, but in the actual handler, we should be returning a human-friendly error while logging the detailed one.

I think we should split this out from here and focus here on logging only. (Split the error issue out to #3723).

> 
> > * The plugins are defining, right now, their own login system (klog, logrus, etc), but, for the sake of standardizing these common aspects for the plugins, the main server should pass a pre-configured logger (as we are passing the k8s clients or the token), so the plugins only have to use it for printing mgs.
> 
> @antgamdia, Please share the piece of code where we are passing the k8s clients or the token. I would like to see what you thinking here.

If you look at the function called to register a plugin, `RegisterWithGRPCServer`, you'll see that the [signature of that function includes a `configGetter`](https://github.com/kubeapps/kubeapps/blob/v2.4.1/cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go#L45). This `configGetter` function itself [has the signature](https://github.com/kubeapps/kubeapps/blob/v2.4.1/cmd/kubeapps-apis/server/plugins.go#L50):
 
```
// KubernetesConfigGetter is a function type used by plugins to get a k8s config
type KubernetesConfigGetter func(ctx context.Context, cluster string) (*rest.Config, error)
```

This enables every plugin to be able to get a configured Kubernetes `rest.Config` by simply passing the request context. The plugin doesn't need to know how the authentication is done, it can just call the config getter with the request context and trust that the returned `rest.Config` will be configured correctly.

So I think Antonio means that we should do something similar for logging, passing a configured logger to each plugin, so they don't care how it's configured, but just use it. We then get consistent logs and plugins do less work.

> 
> > * An idea is using this project: https://github.com/grpc-ecosystem/go-grpc-middleware  as it provides middleware for not only logging, but any other future thing we might want to tackle in the future (like rate limiting).
> 
> @absoludity, do we really need any middleware or can we just have server-side and client-side gRPC Interceptors (UnaryClientInterceptor, UnaryServerInterceptor) calls to log the activity or authorize the func?

The interceptor is the grpc middleware. You don't necessarily need to use go-grpc-middleware right now, since we'd only have one interceptor (and it's purpose is to be able to chain interceptors, which we may want later), but we may benefit from simply not having to write the interceptor and using the [logrus one provided there](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/logging/logrus).

I assume there are two (separate) logging-related tasks here:

1. Use an interceptor to automatically log every rpc call to the server, with standard timestamp etc. This will mean we can remove some of the repeated code at the beginning of most methods which is logging that a function has been called.
2. pass a configured logger in to each plugin so that they can just call `log.Info` or `log.Debug` or whatever is relevant.

I think you'll need to investigate, try them out, then make a proposal here for what you think would be best :)

**Comment by satya-dillikar** [comment]
Addressed via PR#[3780](https://github.com/kubeapps/kubeapps/pull/3780) and PR#[3884](https://github.com/kubeapps/kubeapps/pull/3884)

Closing it for now.
