### ISSUE TITLE
catalog tips An error occurred: Chart kubeapps not found in the repository kubeoperator.

### ISSUE THREAD

**Issue by wanenjie** [kubeapps/kubeapps#3418]
我使用kubeopetarot打开KUBEAPPS，选择对应的命名空间和存储后，跳转到KUBEAPPS没有应用，具体显示如图1。而通过手动上传例如JENKINS安装包到MASTER上执行相关install脚本，完成后没有看到对应的PODS拉起，JENKINS也不知道如何访问，请各位帮忙看看。PS：KUBEAPPS的PODS日志没有错误信息。

I use kubeopetarot to open kubeapps. After selecting the corresponding namespace and storage, I jump to kubeapps. There is no application, as shown in Figure 1. For example, by manually uploading the Jenkins installation package to the master and executing the relevant install script, you don't see the corresponding pods pull up after completion, and Jenkins doesn't know how to access it. Please help. PS: there is no error message in the pods log of kubeapps.

**Comment by wanenjie** [comment]
By execution

kubectl create namespace kubeapps

helm install kubeapps --namespace kubeapps bitnami/kubeapps

In applications, you can see that the kubeapss version is 2.4. Click to update. You need to select the voucher of kubeoperator, but no matter how you choose, you will be prompted with an error occurred: chart kubeapps not found in the repository kubeoperator. A friend said that it may be because the internal container network of the three nodes of k8s is not connected. I don't know how to verify it

**Comment by wanenjie** [comment]
A friend said that it may be because the internal container network of the three nodes of k8s is not connected. I don't know how to verify it.

A friend said that it may be because the internal container network of the three nodes of k8s is not connected. I don't know how to verify it.

**Comment by antgamdia** [comment]
Hi,
thanks for using Kubeapps and reporting the issue. Unfortunately, it is a bit difficult to understand what is happening; perhaps using the [issue template](https://github.com/kubeapps/kubeapps/blob/master/.github/ISSUE_TEMPLATE.md) could help here.
However, I guess you are facing problems with an application that is not present in any of your repositories. We are fixing something related to this at https://github.com/kubeapps/kubeapps/pull/3377.

**Comment by absoludity** [comment]
Hi there @wanenjie 

> 通过执行
> kubectl create namespace kubeapps
> helm install kubeapps --namespace kubeapps bitnami/kubeapps
> 在Applications看到kubeapss版本为2.4，点击进行更新需要选择KUBEOPERATOR的凭证，但无论怎样选择都提示An error occurred: Chart kubeapps not found in the repository kubeoperator。有朋友说可能是因为K8S三个节点的内部容器网络不通导致，不知道怎样验证

I'm not familiar with kubeoperator - but it seems to be this project? https://kubeoperator.io/ . Given that your CLI command to install kubeapps via helm looks fine, I can only guess that kubeoperator has some plugin support for Helm and is expecting the kubeapps chart to be available in kubeoperator's own repository?

Checking kubeoperator, I see these instructions to [deploy kubeoperator (and kubeapps)](https://github.com/KubeOperator/charts/blob/master/applications/deploy.md), it appears to use the internal repository  http://172.16.10.64:8081/repository/kubeapps/ , so you could check the index.yaml at that address and verify whether it contains the Kubeapps chart?

Either way, I don't think this issue is related to Kubeapps itself. Let me know if I've misunderstood something :)
