### ISSUE TITLE
Dashboard shows multiple application for single operator

### ISSUE THREAD

**Issue by foal** [kubeapps/kubeapps#3574]
### Description:

I see multiple copies of the installed operator(s) in the application list:
![image](https://user-images.githubusercontent.com/458209/136825576-981a7123-40f5-4f82-ac63-aa656504435a.png)

### Steps to reproduce the issue:

1. install operator (I scale kiali, but the same was with cert-manager)
2. Not sure - apply several changes of CR (`kubectl apply -n istio-system -f kiali-install.yaml`)
3. Go to applications (any NS)
4. select "Show apps in all namespaces"

### Describe the results you received:

See multiple copies of plate "A configuration file for a Kiali installation."

### Describe the results you expected:

See only one plate per installed operator (or per CR instance of CRD?)

### Additional information you deem important (e.g. issue happens only occasionally):

N/A

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `helm list -n istio-system`:

```
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by absoludity** [comment]
> * 
> 
> * select "Show apps in all namespaces"

What's the behaviour without "Show apps in all namespaces?"

**Comment by foal** [comment]
So operator installed into `operators` NS, 
CR managed by it defined in `istio-system` NS 

Without "Show apps in all namespaces" I see only one instance in `istio-system` NS 
![image](https://user-images.githubusercontent.com/458209/136894513-8de169c6-0b7a-4b18-9379-d84c6934e333.png)
If I switch it I see multiple instances
![image](https://user-images.githubusercontent.com/458209/136894660-33bcae67-e2d8-4681-a90f-e6fa4f7b20c4.png)
If I change context (with enabled "Show apps in all namespaces") I do not see any operators at all
![image](https://user-images.githubusercontent.com/458209/136895021-2d2b9ded-a0b3-464c-8d0a-fa3e2228c54b.png)

**Comment by absoludity** [comment]
And what's the output of `kubectl get --all-namespaces clusterserviceversions`?

**Comment by absoludity** [comment]
So that's why, when you select all namespaces, you see a separate kiali-operator app for each namespace. It's been a while since I've refreshed my OLM knowledge, but I thought a ClusterServiceVersion is *either* installed in the `olm` namespace *or* a specific namespace if you don't want it to be available for all namespaces. In your case you have the `kiali-operator.v1.41.0` CSV in all namespaces (including the `olm` namespace). Is that intentional? From your issue description above (step 2), it looks like you may have intended for it to be only in the istio-system ns?

**Comment by castelblanque** [comment]
There are errors also in FE:
![image](https://user-images.githubusercontent.com/67455978/146219889-c406e955-5907-4c18-8be1-fc183df9438b.png)

**Comment by castelblanque** [comment]
The above is caused by FE placing exactly the same request as many times as amount of namespaces existing.
But all requests are placed without namespace (equals `""`). 

![image](https://user-images.githubusercontent.com/67455978/146241353-df93fc39-69b4-4104-abf1-26f0e4f20271.png)

Therefore, all responses are the same and the same tile/card appears repeated many times.

![image](https://user-images.githubusercontent.com/67455978/146242046-17d278df-96d4-48fd-82ba-4c98cbe4d8c7.png)

However, if the right namespace and right endpoint is used (e.g. `/api/clusters/default/apis/kiali.io/v1alpha1/namespaces/kubeapps/kialis`), there are no resources returned.
