### ISSUE TITLE
UI: missing basic auth information when set from the chart

### ISSUE THREAD

**Issue by dud225** [kubeapps/kubeapps#3583]
Hello

when setting up a repository requesting basic authentication from the chart:
```
  --set apprepository.initialRepos[0].basicAuth.user="${CHARTMUSEUM_USER}"
  --set apprepository.initialRepos[0].basicAuth.password="${CHARTMUSEUM_PWD}"
```
an AppRepository resource is created accordingly:
```yaml
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
[...]
spec:
  auth:
    header:
      secretKeyRef:
        key: authorizationHeader
        name: apprepo-chartmuseum-secrets
```
alongside the secret:
```yaml
kind: Secret
type: Opaque
metadata:
  annotations:
    meta.helm.sh/release-name: kubeapps
    meta.helm.sh/release-namespace: kubeapps
  creationTimestamp: "2021-10-11T15:09:50Z"
  labels:
    app.kubernetes.io/instance: kubeapps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeapps
    helm.sh/chart: kubeapps-7.5.7
  name: apprepo-chartmuseum-secrets
  namespace: kubeapps
  resourceVersion: "8485308"
  selfLink: /api/v1/namespaces/kubeapps/secrets/apprepo-chartmuseum-secrets
  uid: 25eef8dd-8c58-4a08-80fa-0ca0e77e3e0f
data:
  [...]
```

however this information doesn't show up on the UI.

When providing the credentials to the UI and comparing what it has generated, I noticed that the secret created by the UI sports an additional `ownerReferences` field:
```
kind: Secret
type: Opaque
metadata:
  creationTimestamp: "2021-10-12T08:43:08Z"
  name: apprepo-test
  namespace: kubeapps
  ownerReferences:
  - apiVersion: kubeapps.com/v1alpha1
    blockOwnerDeletion: true
    kind: AppRepository
    name: test
    uid: a558e922-7054-453d-bdae-e419433e1957
  resourceVersion: "8655947"
  selfLink: /api/v1/namespaces/kubeapps/secrets/apprepo-test
  uid: ff6adb10-338b-4120-a799-58e86d88bc5b
```

From what I read, the Kubeapps UI seems to be indeed looking for a secret referencing a given AppRepository: https://github.com/kubeapps/kubeapps/blob/84a16fbc12687778ae8e2f58d22f9816a0b0a892/dashboard/src/components/Config/AppRepoList/AppRepoList.tsx#L120-L123

I'm not sure whether the information could be computed the other way around (starting from the AppRepository spec to list the secrets it refers to) or if we could find another way that would make the Helm chart consistent with was is presented on the UI.

**Comment by absoludity** [comment]
Thanks @dud225 for the details.

> I'm not sure whether the information could be computed the other way around (starting from the AppRepository spec to list the secrets it refers to)

We've tried to use the k8s native relationship here, which is to specify owner references on resources that are owned by another. But...

> or if we could find another way that would make the Helm chart consistent with was is presented on the UI.

I think we could simply update the [chart template for the apprepositories-secret.yaml](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/apprepository/apprepositories-secret.yaml) to include the owner reference when this is specified in the chart config? Let me know if you want to have a go, otherwise we'll triage and prioritise this as normal.

Thanks!

**Comment by absoludity** [comment]
(I've pointed to the chart template for our development chart which is synced with the published bitnami one, but if someone does this change, we could do it directly against https://github.com/bitnami/charts/ to fix it in the chart straight away).

**Comment by absoludity** [comment]
Yep, you're right. I'd forgotten about the `uid` field of an ownerReference, which can only be known once the object is created. (And yes, +100 to avoid lookup at all costs :P)

The only way I can see that we could ensure this is consistent whether you specify from the UI or from the CLI via the chart is if we switch from using an ownerReference to using labels. These could be set either way and used in the UI. A secret created via the helm install would not be garbage collected if the app repo was manually deleted, but that's not a huge issue (since it will be deleted when the helm chart is deleted or updated).

So three steps:

- Update the code that saves the app repo secrets, ensuring the labels are set whenever the app repo is saved via the UX (while keeping the owner refs for garbage collection)
- Update the code that loads the related secrets so that it uses labels but still falls back to the ownerreference for backwards compatibility.

Does that make sense to you?

**Comment by dud225** [comment]
Yes perfect. I can only help for the Helm chart area (granted that's the easiest part).

**Comment by ppbaena** [comment]
To be closed as app repositories are in process to be revamped in #4764. Feel free to jump there and add any comment related to this issue.
