### ISSUE TITLE
kubeapps deploy: No matches for kind "CustomResourceDefinition"

### ISSUE THREAD

**Issue by Francesko90** [kubeapps/kubeapps#3729]
### Description:

Error during installation of kubeapps

### Steps to reproduce the issue:

`helm install kubeapps --namespace kubeapps bitnami/kubeapps`

### Describe the results you received:

```
Error: INSTALLATION FAILED: failed to install CRD crds/apprepository-crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`

```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform
:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform
:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.15) exceeds the supported minor version skew of +/-1
```

**Comment by absoludity** [comment]
Hi @Francesko90 , thanks for the report.

As per the warning output of your `kubectl version`:
```
WARNING: version difference between client (1.22) and server (1.15) exceeds the supported minor version skew of +/-1
```
you're running quite an old k8s api server there, which I assume doesn't support the `apiextensions.k8s.io/v1` API ? Can you check the output of api-versions? For example, in my dev cluster I see both the `v1beta1` and the `v1`:

```
kubectl api-versions | grep apiextensions
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
```
whereas I'm guessing, because you're running 1.15, you'll only have `v1beta1`?

We try to support older k8s api versions as long as we can, but the `v1beta1` version of that API was deprecated with 1.16 and removed with 1.22 released earlier this year.

You can try manually updating the CRD in the chart (to v1beta1) if you can't upgrade your server, but no longer support 1.15 (nor is it supported by the kubernetes project, [reaching EOL over a year ago now](https://kubernetes.io/releases/_print/#non-active-branch-history)).
