### ISSUE TITLE
After login with token that showing this error

### ISSUE THREAD

**Issue by leiw324** [kubeapps/kubeapps#3823]
Hello,

What happened ? I followed the guideline to install: https://kubeapps.com/docs/getting-started/
![image](https://user-images.githubusercontent.com/33790160/143481708-a4a1b7cc-7d3b-41df-8576-746c45d1a8bc.png)
![image](https://user-images.githubusercontent.com/33790160/143481691-8fb9def6-8303-4af3-a77c-5e2b4f7c9ba5.png)
![image](https://user-images.githubusercontent.com/33790160/143481725-665276f7-1884-4065-b7fe-bb2176ab7e9c.png)
![image](https://user-images.githubusercontent.com/33790160/143481819-e3a0d570-f62d-4ec5-ba23-5c719e76e831.png)

error:
![image](https://user-images.githubusercontent.com/33790160/143481615-53a73ff1-465a-4de0-a556-9c1036df83c3.png)

Thanks

**Comment by absoludity** [comment]
Thanks for the report @leiw324 . Is it correct that 10.96.0.1 is your k8s api server? If so, it appears that one of the kubeapps pods is unable to connect to your kubernetes API server.

I see you're using redhat/centos, is there a chance you're running openshift here rather than vanilla k8s? If not, please let me know if you're using minikube or kind or a hosted k8s.

As far as I can tell, that error is coming from the `kubeops` service, so you may be able to find more information if you check the logs of the related pod(s). If you can paste those, that would be helpful too.

Thanks!

**Comment by jav333** [comment]
Hello @absoludity ,

API servers IP is 10.0.10.131 - 10.0.10.133, this is our master node IP address.
![image](https://user-images.githubusercontent.com/79013136/143533888-b3133373-2e1a-4967-884f-ce73a00e549d.png)

Sorry, I never use openshift and kubeops service, and not using minikube, I used kubeadm  to create cluster.

Thanks

**Comment by absoludity** [comment]
> Sorry, I never use openshift and kubeops service, and not using minikube, I used kubeadm to create cluster.

The kubeops service is a part of Kubeapps. You'll see a pod for kubeops if you list the pods in the namespace in which you deployed Kubeapps. The logs of that pod at the time that you are experiencing the issue may give us more information.

Also the values.yaml with which you installed would be helpful too. It's not clear why the kubeapps backend (kubeops there)  would be calling k8s API server endpoints (`/api/v1/namespaces`) with the address 10.96.0.1.
