### ISSUE TITLE
Support Markdown in Helm installation notes

### ISSUE THREAD

**Issue by dud225** [kubeapps/kubeapps#3829]
Hello

It would be great if the [Helm installation notes](https://github.com/kubeapps/kubeapps/blob/7e30417f43801b00616d0620fbc0232140b0643a/dashboard/src/components/AppView/AppNotes/AppNotes.tsx#L12) could be rendered in Markdown as it's done for the README.md.

**Comment by absoludity** [comment]
Thanks @dud225 . As mentioned on the [slack thread](https://kubernetes.slack.com/archives/C9D3TSUG4/p1637849824011100), I'm not aware of any reason that this hasn't been done in the past. Since I joined it was always just the helm installation notes from the console, so as a guess, perhaps it was meant to look like it would on the CLI. But I'd have no issue either with us putting it through markdown

**Comment by antgamdia** [comment]
I'm working on this issue (as I was also working on generating the installation notes for a Carvel package install) and have some proposals.

The main problem is that we can't guarantee the output is always gonna be markdown, so we might parse the text when we shouldn't. I've tried to minimize the style issues though.

I'll send a PR in a while, but anyway I wanted to share some examples below:

### Text-plain output

#### Before:

![image](https://user-images.githubusercontent.com/11535726/150527092-f0697e54-f521-49fe-bb0c-ddf3e1042116.png)

#### After:

![image](https://user-images.githubusercontent.com/11535726/150527227-c3eaab05-3e1b-4050-9762-1bb7c9ac400b.png)


### Markdown output

#### Before:

![image](https://user-images.githubusercontent.com/11535726/150527343-6b0e1c22-e123-4632-86f6-b200a552353a.png)


#### After:

![image](https://user-images.githubusercontent.com/11535726/150527394-be2ae866-43d3-467e-ad18-06741e1edae2.png)
