### ISSUE TITLE
We should check for permissions before listing the available applications

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#393]
If a user cannot have access to the components of an application, it should never appear in the list of applications.

Permissions are only checked after the user clicks, which is a bit confusing:

<img width="752" alt="screen shot 2018-07-10 at 12 12 24 pm" src="https://user-images.githubusercontent.com/925437/42504002-8f30358a-843a-11e8-87e4-0d6263e76109.png">

After clicking:

<img width="1200" alt="screen shot 2018-07-10 at 12 13 00 pm" src="https://user-images.githubusercontent.com/925437/42504021-a3eae25e-843a-11e8-8101-3b86b4d6dc03.png">

**Comment by andresmgot** [comment]
Just fyi we discussed that in the PR in which the proxy was added: https://github.com/kubeapps/kubeapps/pull/379#issuecomment-401300933

Note that if there are many releases in a namespace the number of requests will be quite high and it will take some time (at least the first time, then it will be cached). Anyway it's true that it can be confusing but wouldn't be also confusing to omit an app there? If the user knows that the release exists and he is looking for it he would not know what's happening. Probably we should show the app with a warning icon. WDYT?

**Comment by arapulido** [comment]
Yes, I open this issue more as a discussion, as I don't know what should be the best UX here (and the implications on performance as well).

Another question that I had is about objects that are not the usual `view` clusterrole (for example, Secrets). Maybe a user has access to every object of an app, except its secrets. Shall we allow them to see it but hide the secret? Or do as we do now and hide the whole application (when clicking)?

**Comment by andresmgot** [comment]
> Maybe a user has access to every object of an app, except its secrets. Shall we allow them to see it but hide the secret? Or do as we do now and hide the whole application (when clicking)?

I think it would be difficult to find a use case in which a Kubeapps user wants to see only certain components of an application. If he wants to see the status of an application (e.g. wordpress) he will probably want to know the credentials (as an admin of the application). In any case, I think most users will use a role like `edit` that really allows you to use all the functionality of Kubeapps. IMO we should not overcomplicate it (unless we receive a request).

**Comment by prydonius** [comment]
So I think with Helm 2 the best we can do UX wise is show all applications in the Apps list, and then only show an error if you try to view the application (i.e. the current functionality). The reason is because I think this best matches the Helm CLI experience, if you have access to Helm you can list all apps in all namespaces, but you might only be able to view apps in a specific namespace.

I suspect that we only realistically care about limiting access with namespaces, as @andresmgot suggests the likelihood that a user has anything less than `edit` access is probably going to be low and if a user is missing permissions to say, view StatefulSets, it's probably just a permission the admin forgot to apply. The only exception to that _might_ be Secrets, but again if a user is given access to Kubeapps we can probably assume that they'll want to see credentials to access an application.

I actually did not know that the `view` role hides Secrets, @andresmgot we may need to add a role that allows `get`, `list` on everything in a namespace if a default one doesn't exist. This will give a true read-only role for Kubeapps users.

**Comment by andresmgot** [comment]
I've checked the possible implications of getting the permissions of all the component when listing applications. Only we three applications I got a processing time of:

 - First request: 602 vs 66.64ms (9 times more)
 - Second request (cached): 607 vs 23.36 ms (23 times more)

In my opinion that cost in performance would be too much comparing to the benefits it provides.

About having a different "view" role with extra permissions I am fine adding it.

**Comment by prydonius** [comment]
Thanks for looking into that, that's rather interesting. Have you looked at https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#selfsubjectrulesreview-v1-authorization? This may allow us to enumerate all of a users'  permissions in a single API call and then filter through it on the client side. Using this API could also help to make the Tiller Proxy more efficient, also.

**Comment by andresmgot** [comment]
Yes, I thought about that but we would need to reimplement K8s logic to resolve if a user is allowed to do something or not. In any case, the bottleneck is not the calls to the K8s API but the resolution of the charts. Note that every time a request is received it needs to download the chart from the given registry URL, expand it and send it to Tiller in order to retrieve the final manifest. That's the expensive part.

**Comment by andresmgot** [comment]
I am closing this issue for the moment since there are not more actionable items here. Let me know if you think otherwise so we reopen this or a different issue.

**Comment by prydonius** [comment]
> Note that every time a request is received it needs to download the chart from the given registry URL

This is referring to the Tiller proxy, correct? For the Apps List we can just fetch the rendered manifest from the ConfigMaps (via the Tiller Proxy). Agree with closing this, though.

**Comment by andresmgot** [comment]
>> Note that every time a request is received it needs to download the chart from the given registry URL

> This is referring to the Tiller proxy, correct? For the Apps List we can just fetch the rendered manifest from the ConfigMaps (via the Tiller Proxy). Agree with closing this, though.

Yes, I mean in the Tiller proxy, each time we need to resolve permissions there we need to resolve the manifest of the application. We can improve performance there adding some caching and avoiding to download charts when it's not strictly necessary but that's not needed for listing apps.
