### ISSUE TITLE
Add a "filter by plugin" in the Catalog view

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#4097]
If Kubeapps is configured with multiple plugins, a user may want to filter by the plugin type (eg, "list all the carvel packages").

Adding a new filter in the Catalog view (ie, just frontend) should be enough. Long-term, we might consider adding backed filters to the core API to query just a subset of the configured plugins.

**Comment by absoludity** [comment]
> Adding a new filter in the Catalog view (ie, just frontend) should be enough. Long-term, we might consider adding backed filters to the core API to query just a subset of the configured plugins.

Why wouldn't we do the backend filter from the start? Seems odd to add functionality to the frontend that is doing it in a way that we'd want to later remove, with no gain other than looking like it's already done (when it's not)? I usually push back on this kind of thing because it gives the impression that we're further ahead than we are which skews expectations. But if you think it's necessary, OK.

**Comment by ppbaena** [comment]
Close as it is duplicated in #3889
