### ISSUE TITLE
Step 5 of E2E tests is consistently failing

### ISSUE THREAD

**Issue by castelblanque** [kubeapps/kubeapps#4102]
### Description:

Step `05-missing-permissions.js` of the E2E tests is failing most of the time.

At first, initial investigation by @absoludity pointed to the absent "Missing permissions" sentence in the error message checked by the test.
However, it seems that there are two types of errors showing:

1. 
![image](https://user-images.githubusercontent.com/67455978/149835667-d5b40203-cf4e-41a8-8fd2-90e50d73a0b1.png)

2.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/67455978/149835704-f71b5056-9f18-4892-a238-30909b736d2e.png">

### Steps to reproduce the issue:

1. Use OIDC user (not operator)
2. Try to install a package from a global repo

### Describe the results you received:

Test not passing most of the time

### Describe the results you expected:

Test consistently passing successfully

**Comment by absoludity** [comment]
Hmm, I don't think this should be closed, unless you find that running `04-default-deployment` with the same `kubeapps-view` user passes fine - #4081 - (in which case, I then agree with closing this issue with the work-around).

I say that because before I left, I did some investigation on this issue (as mentioned above) and found that it was a *valid* failure (locally or on CI). That is, the `kubeapps-user` that is created in CI has special privileges to be able to [view (`get`, `list`, `watch`) secrets in the default namespace only](https://github.com/kubeapps/kubeapps/blob/master/script/e2e-test.sh#L414-L418).

So your first screenshot is the valid error that is expected by this test... that this user fails to install an app in the default namespace because they don't have RBAC to do so (specifically, create secrets there), it's just a much uglier error since we switched to the api server (though I see you're fixing that - great) and importantly, doesn't contain the expected text.

Your second screenshot is exactly you would expect if our code tries to get secrets for app repos in the public (kubeapps) namespace, since the kubeapps-view token doesn't have RBAC to do that. So it may also be a valid failure too.

Anyway, we'll find these if we run the 04-default-deployment with this user (as per #4081), but if we fix those issues, I expect that this 05 test will also be fixed.
