### ISSUE TITLE
Automate chart releases

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#414]
We need to automate the Kubeapps chart release to the https://github.com/bitnami/charts repo whenever a tag is created in this repo. The chart values should be modified to point to the tagged images.

**Comment by arapulido** [comment]
@prydonius we can focus on this once we have created the first release. I would focus first on documantation, migration guides, release, etc.

**Comment by prydonius** [comment]
There are two cases when we want to update the chart, when we tag a new release and when we make a change to the chart that is not tied to a particular release.

In Monocular, I setup automation to run on pushes to master that detect if the chart version changed, if it did the chart would be packaged and index.yaml regenerated. I think we should do the same thing here, but of course pushing to the `bitnami/charts` repo instead.

**This will change the release process to involve (asynchronous):**
1. Tagging a release for images to be built and pushed
2. PR-ing and merging a change to this repo to bump the chart version (appropriately with respect to semver) in the Chart.yaml

**We will need a script that runs on master branch builds that:**
1. Checks to see if the chart version has changed (we can check the diff, or maybe compare to whatever is currently in bitnami/charts if the diff is not reliable)
2. If changed, publish the chart

**To publish the chart we should:**
1. Update the values.yaml to replace latest tags with the latest tagged version
2. Update appVersion in the chart to the latest tagged version
3. Push the changes to bitnami/charts (ensuring we delete any older files to avoid https://github.com/bitnami/charts/issues/753)

**Why not automatically release a new version of the chart when tagging a release?**

Monocular is setup to do this, but it raises the challenge that we would need to bump the chart version from the CI and keep this in sync between this repo and bitnami/charts. Also, we would have to come up with a rule for what level of semver bump we automatically do, which may not always make sense and might require manual judgement. Given the release process is only 2 asynchronous steps, I don't think it will be a huge burden to manually bump the chart version after tagging a release.

**Comment by migmartri** [comment]
This sounds good to me. I am not sure about pushing instead of PR in the bitnami/charts repo.

> Given the release process is only 2 asynchronous steps, I don't think it will be a huge burden to manually bump the chart version after tagging a release.

I think this is a reasonable amount of manual work.

**Comment by prydonius** [comment]
> I am not sure about pushing instead of PR in the bitnami/charts repo.

I wanted to avoid a second PR-review step, since the chart will be reviewed and tested in this repo. We currently push directly to master for bitnami-bot updates (e.g. https://github.com/bitnami/charts/commit/1895be03b31b3c810ced3b8558417f58518b484e for upstream stable syncs, https://github.com/bitnami/charts/commit/1dc0755bb4ea700f33f513045d9a40b4b5517a29 for other charts) and I saw this in the same light. Is there a particular reason you want to send PRs to the bitnami/charts repo?

**Comment by andresmgot** [comment]
In general it looks good to me. It's implementation detail but I'd avoid using a bash script for this since it's a bit complex (and use a proper programming language, probably Go). Another couple of comments:

> Checks to see if the chart version has changed (we can check the diff, or maybe compare to whatever is currently in bitnami/charts if the diff is not reliable)

It's better to use always the chart from bitnami/charts. It's easier to compare and will fix sync issues if any. One problem with that is that possible external contributions in `bitnami/charts` should be redirected to this repo but that's not a big issue.

> I wanted to avoid a second PR-review step ... Is there a particular reason you want to send PRs to the bitnami/charts repo?

That's fine for me as far as we are confident with the sync process. A possible bug in the process may break the chart.

**Comment by prydonius** [comment]
> One problem with that is that possible external contributions in bitnami/charts should be redirected to this repo but that's not a big issue

Good point, we should make sure the maintainers of that repo and we are all aware that changes to that chart should be made in this repo.

> That's fine for me as far as we are confident with the sync process. A possible bug in the process may break the chart.

:+1: Hopefully we can reuse what we're already doing for the other charts!

**Comment by andresmgot** [comment]
> 👍 Hopefully we can reuse what we're already doing for the other charts!

I have checked with the team that manages that but we cannot reuse their logic because it's a groovy script and the purpose of this script is to sync the whole repository, it's not done per chart.

To double check the current suggested approach. The suggested steps are:

 - Tag and release like we do today (nothing to do here).
 - (Manually) Create and merge a PR bumping the chart version
 - On master builds:
    - Clone the bitnami/charts repo
    - Obtain current chart version
    - Compare with the current version
      - (if different) Delete the folder containing the kubeapps chart
      - Copy the content from this repo
      - Modify the default tag for the latest release
      - Push the changes

That approach has some small issues:
 - It adds a small overhead for all master builds. 
 - It requires to discover the current version of the bitnami repo and the latest release of kubeapps.
 - Unexpected changes may break the chart in the `bitnami` repo.

Based on what @prydonius says is the existing approach in the monocular repo we could also have a similar approach:
 - On tagged builds:
    - Clone the bitnami/charts repo
    - Delete the folder containing the kubeapps chart
    - Copy the content from this repo
    - Modify the default tag with the current tag
    - Send a PR
 - (Manually) Review the PR and modify the chart version in the PR

This second approach is a bit more simple (doesn't require to compare or discover versions) and allow us to discover fatal errors in the PR. It has the inconvenient that merging the PR is a manual step but we will need to do something similar anyway with the first approach.

Let me know what you think.

**Comment by prydonius** [comment]
> Unexpected changes may break the chart in the bitnami repo.

This should hopefully be covered by CI in this repo though, right? Since we'll run the Helm tests here (though I understand that initially this may not catch everything).

The problem I see with the second approach is it removes the ability for us to modify the chart outside of the release process. Or if we have a combination of both processes, we could run into an issue where the chart is updated whilst there is still a PR open for another update. Also, as mentioned earlier, we would need to agree on what the correct version bump should be for new releases. What do you think?

**Comment by andresmgot** [comment]
> This should hopefully be covered by CI in this repo though, right? Since we'll run the Helm tests here (though I understand that initially this may not catch everything).

Note that the tests will be run with the chart in this repository not with the one in the `bitnami/charts` repo (unless there is a CI in place for that repository). So what we test here may not be the same that we push there if we have a bug in the sync process (which is a bit unlikely).

> The problem I see with the second approach is it removes the ability for us to modify the chart outside of the release process.

You mean that we won't be able to release a new version of the chart without updating the version of the images, right? That's probably going to be a corner case but in any case we will be able to do that manually just creating a manual pull request in the `bitnami/repo`. 

> Also, as mentioned earlier, we would need to agree on what the correct version bump should be for new releases. What do you think?

My idea was to just modify the version of the chart in the PR that the CI does but it's true that that will leave the version of this repo outdated. Ideally we should bump the version before tagging the release. That way the PR that the CI does should be ready to merge without any modification. If we forget to do so we will still have the opportunity to modify it in the PR and manually sync this repo.

I still prefer to go for the second option because it's less prompt to errors but it's true that the second is more smart and require less human intervention so I am okay with both of them. What do you think?

**Comment by prydonius** [comment]
> You mean that we won't be able to release a new version of the chart without updating the version of the images, right? That's probably going to be a corner case but in any case we will be able to do that manually just creating a manual pull request in the bitnami/repo.

We should avoid having two processes (i.e. automation and also allowing a manual PR), and I don't think that it's not very likely. Consider the recent change to update the chart to work in multiple namespaces, we also had @juan131 contribute a README/NOTES change earlier. Those things shouldn't have to wait for the release. That said, if we stick to a 2 week release cycle, it's not a huge problem to wait in some circumstances, but there may sometimes be urgent issues that we need to fix in the chart.

> My idea was to just modify the version of the chart in the PR that the CI does but it's true that that will leave the version of this repo outdated. Ideally we should bump the version before tagging the release. That way the PR that the CI does should be ready to merge without any modification. If we forget to do so we will still have the opportunity to modify it in the PR and manually sync this repo.

Yeah, in Monocular the script would push to the repo to update the version of the chart, but that's a little harder here since there are two places (though still possible). I think it's pretty likely that we will forget that step during a release, and with that process we'd need to have a PR rather than push directly to master in bitnami/charts so that we can catch that.

> I think the first option is less prompt to errors but it's true that the second is more smart and require less human intervention so I am okay with both of them. What do you think?

To me, option 1 is more explicit about the version of the chart we're releasing, and gives us more flexibility to update the chart outside the release cycle through a single process. Maybe we can start with that and see how it goes? If we want to make it more automated in the future with releases, then we can change it up.

**Comment by andresmgot** [comment]
okay, find by me. Let's go with option 1
