### ISSUE TITLE
Unable to deploy application without appreposities-read role

### ISSUE THREAD

**Issue by doddatpivotal** [kubeapps/kubeapps#4205]
I have a user account with edit permissions on a namespace.  She can log into to kubeapps using her token that represents this permission.  She can browse the catalog of available apps, however when she attempts to deploy an app, she receives following error message...

An error occurred: Unable to create the installed package for the package "vac-repo/mysql" using the plugin "helm.packages": rpc error: code = Unauthenticated desc = Missing permissions rpc error: code = Internal desc = Unable to fetch app repo "vac-repo" from namespace "kubeapps": unable to get app repository kubeapps/vac-repo: apprepositories.kubeapps.com "vac-repo" is forbidden: User "sso:naomi@vsphere.local" cannot get resource "apprepositories" in API group "kubeapps.com" in the namespace "kubeapps"

<img width="1441" alt="Screen Shot 2022-02-01 at 9 38 50 AM" src="https://user-images.githubusercontent.com/37634387/151989363-52a70c79-ed02-45f4-b9b2-3a11695cfa3d.png">

If I create a role binding in the kubeapps namespace for her against the kubeapps:kubeapps:apprepositories-read role, then everything works fine.  This was not mentioned in the documentation as a requirement and seems to be a bit burdensome.

**Comment by absoludity** [comment]
> If I create a role binding in the kubeapps namespace for her against the kubeapps:kubeapps:apprepositories-read role, then everything works fine. This was not mentioned in the documentation as a requirement and seems to be a bit burdensome.

Thanks @doddatpivotal . Yes, this issue started when we moved to our new API server, where we *always* use the users RBAC rather than a service account, and was recently fixed by @castelblanque , when we added an extra RBAC to our chart that ensures [any authenticated user can read the global repositories](https://github.com/kubeapps/kubeapps/blob/main/chart/kubeapps/templates/apprepository/rbac.yaml#L220-L232). That fix will be in the next chart release.

I'll close this issue based on the above fix, but please re-open if you reproduce it with the next chart version. Thanks again for creating such clear and concise reports for us @doddatpivotal , it's incredibly helpful for us!

**Comment by doddatpivotal** [comment]
I can confirm it is now working with v7.7.4
