### ISSUE TITLE
A user with permissions to create apprepositories (but not secrets) in the namespace where Kubeapps is deployed should be able to add App Repositories that don't require authn

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#437]
While creating a repository I got the error

```
create apprepositories (kubeapps.com) in the kubeapps namespace.
```

... which was expected since my user does not have permissions to manage repositories. What is confusing to me is that it also says `create secrets in the kubeapps namespace.` and I do not see any reference to secrets rbac resolution in the API calls (below). Where does the `secret` resource requirement comes from?

![selection_616](https://user-images.githubusercontent.com/24523/43740017-e10f913a-997e-11e8-9a95-95c19475a9c4.png)

**Comment by prydonius** [comment]
Those are the set of permissions required for creating repositories (part of the kubeapps-repositories-write Role). If you don't have either the secrets permission or the apprepositories permission you will see that error, even if you do have one of them. We don't check for the actual call that failed.

In this particular case, we may want to do that, though, since we don't need to create the secret if the Auth header is empty.

**Comment by arapulido** [comment]
To clarify, the create secret one comes because if a repo requires auth the token gets created in a secret

**Comment by arapulido** [comment]
I have edited the title and moved it to the backlog, as I don't think this is that critical
