### ISSUE TITLE
Integration with vSphere with Tanzu

### ISSUE THREAD

**Issue by rfarag** [kubeapps/kubeapps#4403]
Currently, The auth is limited to TKC through Pinniped, Which is not available under vSphere with Tanzu that use ‘Kubectl vSphere’ plug-in for authentication through vCenter SSO.
https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-93B29112-4492-431F-958A-12323540C38D.html
Is there any way to make that kind of integrtion?

**Comment by absoludity** [comment]
Thanks for creating the issue @rfarag.

The kubectl vSphere plugin [appears to result in a JSON Web Token](https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-AA3CA6DC-D4EE-47C3-94D9-53D680E43B60.html#procedure-2), so theoretically, it would be possible.

I had thought that a Tanzu Kubernetes Cluster has pinniped installed? I assume there's just not support for vCenter SSO in pinniped yet? (because vCenter sso doesn't support SAML or OIDC etc.? Not sure though).

**Comment by absoludity** [comment]
Just replying to my own comment:

> I had thought that a Tanzu Kubernetes Cluster has pinniped installed? Is this not correct?

This is not correct, unless you add your cluster to TMC which adds pinniped, but it'd still not be connected to vCenter SSO

> I assume there's just not support for vCenter SSO in pinniped yet? (because vCenter sso doesn't support SAML or OIDC etc.? Not sure though).

Seems not. So, AFAICT, outside of writing a completely new authenticator for Kubeapps to work with just vCenter SSO and the corresponding webhook/json web token, I don't think this is something we can do right now.

The best bet would be to push for vCenter SSO to support standard auth protocols (like OIDC/OAuth2) and have those used in-cluster. That would mean any app (not just Kubeapps) that relies on standard auth protocols would be able to authenticate.

I'll close this issue for now as I don't think there is any more we can do. But feel free to re-open or comment if that changes or there are other possibilities or questions.
