### ISSUE TITLE
Explore Kubeapps distribution as Carvel package

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#4410]
### Description:

As first step to add Kubeapps as a package of Tanzu Community Edition, it is necessary to revisit all requirements ([here](https://github.com/vmware-tanzu/community-edition/tree/main/docs/packaging)). 

Once Kubeapps team will guarantee the compliance, a proposal will be sent to make Kubeapps available as a Tanzu package as part of Tanzu Community Edition.

### Acceptance criteria

- [x] Revisit current status for distributing Kubeapps as a Carvel package
- [x] Revisit compliance with prerequisites
- [x] Create an issue to request to make Kubeapps available as a Tanzu package as part of Tanzu Community Edition.

### Additional information

Interesting to take a look to the initial comments about Kubeapps in TCE ([here](https://github.com/vmware-tanzu/community-edition/issues/2418))

**Comment by absoludity** [comment]
I've been working on this as a background task (as it requires a few different communication points with carvel + bitnami teams).

**Comment by absoludity** [comment]
I've created https://github.com/vmware-tanzu/community-edition/issues/3732 with the details for the proposal, as well as the compliance with the prerequisites (ie. current feedback from slack is that we can use `helm-template` even though the TCE docs don't mention it). Also checked internally about current tooling for Kubeapps as carvel. Not yet sure how much we can re-use due to required input (public chart, not TAC chart) and output (git repo of source, rather than registry with package).
