### ISSUE TITLE
Kubeapps Helm Upgrade - Tokens now invalid

### ISSUE THREAD

**Issue by DanPhonovation** [kubeapps/kubeapps#4439]
Just ran an upgrade to KubeApps via helm.

Kubeappsapi refused to startup complaining about invalid flags like:

```
- '--plugin-config-path=/config/kubeapps-apis/plugins.conf'
- '--global-repos-namespace=kubeapps'
- '--kube-api-qps=50.0'
- '--kube-api-burst=100'
```

I manually removed them from deployments, restarted all pods and they all came up successfully.

But now no token works to login to the dashboard. 

I have tried recreating them using service account or cluster-admin as described here: https://github.com/kubeapps/kubeapps/blob/v2.4.3/docs/user/access-control.md

But no luck.

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION 
kubeapps        kubeapps        5               2022-03-15 15:24:40.623725866 +0000 UTC deployed        kubeapps-7.8.9  2.4.3  
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f", GitTreeState:"clean", BuildDate:"2021-02-03T17:42:23Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Should I just be redeploying from scratch at this stage?

Edit: did a helm uninstall and redeployed from scratch. Went through and deleted service accounts. Upgraded helm to latest.

For some reason, the 4 generated tokens still come back the same, even if I deploy to another namespace. But either way, I get "The current account does not have access to any namespaces" now.

Have I also lost all my previous deployment info done with kubeapps? Will a new deployment of kubeapps still be able to manage deployments the old one did?

**Comment by DanPhonovation** [comment]
`kubectl --as system:serviceaccount:default:kubeapps-operator auth can-i get namespaces`

returns "no"

**Comment by DanPhonovation** [comment]
I'll be honest. I don't know what I did, but after multiple times erasing old resources and redeploying... I got it back working. Good to know it kept a view on old releases and even operators. I'm curious what postgresql is for then?

**Comment by absoludity** [comment]
> Just ran an upgrade to KubeApps via helm.
> 
> Kubeappsapi refused to startup complaining about invalid flags like:
> 
> ```
> - '--plugin-config-path=/config/kubeapps-apis/plugins.conf'
> - '--global-repos-namespace=kubeapps'
> - '--kube-api-qps=50.0'
> - '--kube-api-burst=100'
> ```

Those flags are used in the latest release, so my guess of what happened is something like:

1. Kubernetes brought up the new pods, but they took a long time to start (ie. pass readiness checks - we've fixed this since the last release), 
2. Something caused the old images to run with the new deployment, which would result in the error complaining about invalid flags. This could happen for a number of reasons ([maxSurge value](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-surge) or manually deleting the pod so it gets recreated).

But I'm not sure - that's just a guess.

> 
> Should I just be redeploying from scratch at this stage?

It's fine to do so - assuming you've got your values that you use then it's no different to upgrading (though I'd still be keen to be able to understand what happened during the upgrade).

[snip]

> 
> Have I also lost all my previous deployment info done with kubeapps? Will a new deployment of kubeapps still be able to manage deployments the old one did?

Yes: Kubeapps does not store any state about your helm deployments - it relies on the state created by Helm itself (usually a config map or secret that the helm CLI uses to get the release info). The only permanent state Kubeapps keeps is in any `AppRepository` custom resources that you may have created when adding helm repositories via Kubeapps.


> `kubectl --as system:serviceaccount:kubeapps2:kubeapps-internal-kubeappsapis auth can-i get namespaces`
> 
> and
> 
> `kubectl --as system:serviceaccount:kubeapps2:default auth can-i get namespaces`
> 
> both return no

Yep, that is correct - those service accounts do not have elevated privileges at all. Neither should they be relevant for logging in to Kubeapps.

> 
> "kubeapps2" is a second namespace I made for a fresh redeploy.
> 
> In a kubeappsapi container log I also see:
> 
> `I0315 16:35:38.770155 1 namespaces.go:24] +resources CheckNamespaceExists (cluster: "default", namespace="default") I0315 16:35:38.785203 1 server.go:59] PermissionDenied 15.127714ms /kubeappsapis.plugins.resources.v1alpha1.ResourcesService/CheckNamespaceExists`
> 
> Caught this as well in the UI that I didn't see before:
> 
> `forbidden to get namespace kubeapps2 due to namespaces kubeapps2 is forbidden User "system:serviceaccount:kubeapps2:kubeapps-operator" cannot get resource "namespaces in API group "" in the namespace "kubeapps2"`

Kubeapps is just reporting that the token used to authenticate is associated with the service account `kubeapps-operator` in the `kubeapps2` namespace, and it apparently didn't have sufficient RBAC to get a namespace in the `default` or `kubeapps2` namespace. But...

> I'll be honest. I don't know what I did, but after multiple times erasing old resources and redeploying... I got it back working. 

Glad to know you got it working, sorry for the hassle. I'm keen to understand what might have happened, but often in these situations issues can get compounded (in my experience).

> Good to know it kept a view on old releases and even operators. I'm curious what postgresql is for then?

postgresql is used as a disk cache of the charts available for the given `AppRepositories` that you have installed.  I.e. a cronjob regularly pulls the `index.yaml` of any `AppRepositories` you have installed and parses to find all the chart and versions and other metadata like readmes, icons etc.), so that the UI can present the catalog of available charts in a timely manner. As it is a cache, you can blow it away and the only problem is that Kubeapps needs a minute or two to rebuild the cache. As mentioned above, Kubeapps is a UI that uses the data from Helm or operators (or flux or carvel :) ), so that state is not removed when you uninstall Kubeapps.

Let me know if there's anything else we can investigate here. Glad you were able to push through and getting your deployment working again!

**Comment by DanPhonovation** [comment]
Thank you
