### ISSUE TITLE
Kubeapps v1.0.0-alpha.5 release

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#445]
Road to v1.0.0-alpha.5:

- [x] Migration guide (#397)
- [ ] Tag v1.0.0-alpha.5 release (will trigger image builds)
- [ ] PR to bitnami/charts repo for Kubeapps chart
- [ ] Update installation and other docs for Kubeapps Helm chart

**Comment by prydonius** [comment]
I think we should tag the v1.0.0-alpha.5 release prior to updating documentation and having the chart available. Doing so will ensure we have built tagged images to use in the chart PR to bitnami/charts. In the short time between the release being tagged and the chart being merged, the `kubeapps` CLI instructions currently documented will continue to work. After the chart has been merged, we can merge the PR to update the relevant documentation.

Does that make sense?

**Comment by andresmgot** [comment]
I think that the transition will be smoother if we add the documentation first even if it tells that to install the chart you need to use a local directory. If publishing the chart in `bitnami/charts` take longer, we will already have the documentation so it won't be a problem. Also the changes after the chart is published will be minimal.

> the kubeapps CLI instructions currently documented will continue to work

That won't be the case if the user is updating Kubeapps instead of installing it for the first time.

**Comment by prydonius** [comment]
@andresmgot the issue with using the chart in the repo is that it will point to latest so we need to set all the tags, and it requires cloning the repo so is more steps. I plan to merge the chart in `bitnami/charts` quickly since it's already been merged (and we can follow up any other changes in future PRs).

**Comment by prydonius** [comment]
@andresmgot np, thanks for the suggestion
