### ISSUE TITLE
Routes inconsistency

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#452]
it seems that the namespace is mapped in the route in different ways, For example, for Helm releases we map it at the beginning of the route

![selection_627](https://user-images.githubusercontent.com/24523/43875131-3f37a5ba-9b44-11e8-9f38-f68fae6cba6b.png)

 but for service catalog it's seems to be at the back 

![selection_626](https://user-images.githubusercontent.com/24523/43875141-4245fdba-9b44-11e8-9143-15cb82ab8f58.png)

We should aim for consistency of possible. I personally prefer the prefix mode but I'll also move even further up level before the main resource (app or service), so instead of `apps/ns/default` do `ns/default/apps`

**Comment by prydonius** [comment]
The reason for this is that we're only namespacing the namespaced routes. The Service Brokers are cluster-scoped and that's why the namespace only comes in at the Service Instances scope. This follows from the Kubernetes API. I personally likely this model, as it maps well to being an ID for the resource (e.g. default/miguel-test).

The alternative could be, as you suggested, ensuring the namespace is always in the URL at the beginning of the route. This might serve as a helpful identifier of what the current namespace is, even when you're in a cluster-scoped route, but it loses the resource ID we get in the current routing.

**Comment by migmartri** [comment]
Thanks @prydonius for the explanation. Although I do not fully agree with the k8s like mapping being the best option in this case, I think that it is a valid reason and hence the "inconsistency" I saw it is not such a thing.

I am going to close the issue for now.

Thanks!
