### ISSUE TITLE
Explain difference between Monocular and Kubeapps in README

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#507]
I don't understand what is the main project or difference between monocular and kubeapps.
Could you explain what is the difference between this two projects ?

**Comment by prydonius** [comment]
Hey @obeyler,

I know things are a in a bit of a confusing state right now, so apologies about that. We originally designed Monocular with a public website in mind (e.g. https://hub.kubeapps.com) and not with the in-cluster usecase. After talking to people though, they really wanted a UI to manage Helm releases so we extended Monocular to do that and put that behind a feature flag. The problem was that it was becoming difficult to maintain the two different user experiences (public site and in-cluster), and at the same time we wanted to add support for the Service Catalog and other extensions, so we ultimately decided to split them and start Kubeapps.

At this point Kubeapps has diverged quite a bit from Monocular and doesn't use the original codebase anymore. The plan for the Monocular project going forth is to focus on enabling the CNCF distributed Charts search site (see proposal: https://github.com/helm/community/blob/master/proposals/distributed-search.md and repo: https://github.com/helm/hub), and so the in-cluster features won't be extended (and may possibly be removed in future releases).

As far as what you should use, if you're looking for a UI to aggregate chart repos and browse available charts, Monocular is great for that. If you're looking for a way to deploy, manage, upgrade Helm charts in your cluster, Kubeapps is the better fit for that.

**Comment by obeyler** [comment]
I've install both monocular and kube apps on same Kubecluster ;-) Thanks for your clear answer.
Note that the name of kubeapps it a little bit confusing in regards of kubeapps.com web site.
may kubeapp project or kubeapp web site should be renamed

**Comment by prydonius** [comment]
@obeyler agree about the naming confusion, we have considered renaming this project - we'll see! Thanks for the feedback!

I'm going to keep this open as we want to add this explanation in the README
