### ISSUE TITLE
Tagged and latest image builds should be pushed after the integration tests

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#537]
Currently CircleCI pushes images before running integration tests or before other images are successfully built. This could have potential side effects where we release images that are in a broken state.

We should make sure we only push the latest and versioned image tags at the end of the pipeline (e.g. the release job). To do so, we may need to see if we can share the docker context in CircleCI, or we may need to push an intermediary tag (e.g. the commit sha), and the re-tag with latest (and the version for tag builds) at the end of the pipeline.

**Comment by migmartri** [comment]
Yes, I agree that this is needed. This could potentially release only some images creating a mismatch of `latest` images that we have not tested.

The way I've seen this kind of pipeline before is that during build we push the image with a tag associated to the build-id. Then, this tag is passed to the test stage in case that we run the tests inside that container and to the release stage (if needed), where the image gets re-tagged to `latest` or `v.tag` and pushed.

To me, it is ok if during release we need to pull all the images since release is a asynchronous thing that should not block us.

**Comment by prydonius** [comment]
Is the CircleCI build ID different for each job, can we get the workflow ID? Would it be better to use the short git ref as a tag instead?

**Comment by andresmgot** [comment]
yes, I meant the workflow ID. Anyway, it's true that using the git ref can be an improvement because if you retry only the failed steps of a workflow, the workflow ID will change so it won't find the image tags.

In the other hand using the git ref we won't have immutable tags since retrying a build can produce a different image. I don't think that's a problem though.
