### ISSUE TITLE
Add support for SCSS compilation

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#549]
We should add support for SCSS preprocessing for CSS in the dashboard. This will allow us to have more flexibility with variables and also support theming.

Hex theming: https://design.bitnami.com/category/Theming/

We should also add SCSS linting to the build pipeline.

**Comment by prydonius** [comment]
I'm checking with another team at Bitnami on how they enabled SASS support in another React project. create-react-app suggests setting up a separate task to watch and compile CSS and run both tasks together when running the dev server: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc.

There is also this fork https://github.com/jpavon/react-scripts-ts which seems to add support for SASS pre-processing directly, but this might cause issues when integrating, it might be more up-to-date and require us to update more things.

With either option, the SCSS files will live next to the compiled CSS files which looks a bit weird, and adds a bit of noise in code reviews, but I don't think there's a good way around that.

**Comment by Angelmmiguel** [comment]
> With either option, the SCSS files will live next to the compiled CSS files which looks a bit weird, and adds a bit of noise in code reviews, but I don't think there's a good way around that.

Once you add the SASS preprocessing as described in the [create-react-app guide]( https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc), the compiled CSS files must be ignored (`.gitignore`). Since React TypeScript starter is based on create-react-app, I think that following the given guide is the best solution to avoid ejecting the project.

**Comment by prydonius** [comment]
Thanks @Angelmmiguel, I think you're right - I will go ahead and enable that. Also, thanks for the pointer for putting compiled CSS in `.gitignore`.
