### ISSUE TITLE
[Feature Request] Add refresh all repositories to the repositories page....

### ISSUE THREAD

**Issue by natiki** [kubeapps/kubeapps#582]
Hi,

Ultimately it would just do a `helm repo update` under the skin.

**Comment by prydonius** [comment]
Agree this could be a cool feature!

**Comment by jessehu** [comment]
@andresmgot @prydonius  Are we expecting something like this ?

![image](https://user-images.githubusercontent.com/10006/61447543-b8568a80-a983-11e9-8e0e-06f24e6dea1a.png)

**Comment by andresmgot** [comment]
Yes, something like that is what we were looking for

**Comment by jessehu** [comment]
OK, I can try to add this. One proposal: after clicking on 'Refreshing All Repositories' or 'Refresh' button, how about disable the button for 2 or 3 seconds in case the users click it twice?  Because currently there is no message shown on the UI that saying the 'Refresh' request is sent to backend server successfully and there is no column showning the last updated time of each repository.

**Comment by andresmgot** [comment]
Yes, that's a good point, that would improve the user experience :)
