### ISSUE TITLE
Support for S3 and other non-http based helm chart repos

### ISSUE THREAD

**Issue by danbeaulieu** [kubeapps/kubeapps#591]
Helm supports non-http based chart repos through its plugin system. One example is this S3 plugin: https://github.com/hypnoglow/helm-s3

It may be possible to support this via auth headers with no changes needed to kubeapps: https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader

However native support may be ideal especially for other non-http storage systems that don't support auth headers.

**Comment by migmartri** [comment]
Thank you @danbeaulieu for the report!

I have created another document generic issue that it can be potentially related to this issue https://github.com/kubeapps/kubeapps/issues/600#issue-358170701

**Comment by andresmgot** [comment]
Hi, 

I have been testing the [Helm S3 Plugin](https://github.com/hypnoglow/helm-s3). As a summary, it's not possible to access a S3 file just using an `Authorization` header that is the only method supported right now by Kubeapps. For accessing a private S3 object you either need:
 - The AWS access and secret keys and use the S3 SDK to access the file. This would require major changes in `tiller-proxy`. It may be possible to reuse the code in the `helm-s3` plugin.
 - A pre-signed URLs. That makes an object "publicly" available if you have the link. I don't think we can develop a solution using this approach since each file would have a different pre-signed (and non-predictable) URL. We would also need a periodic process to recreate those URLs.

**Comment by andresmgot** [comment]
Yes, to access a S3 object you need to use the Authorization header. The difference is that in our case, we use the same Authorization header for accessing all the elements of the repository (the `index.yaml` and the charts) while in the case of S3 you need to calculate the header per requested file. The signature depends on the path of the file you want to access. That's why it would require changes in our side if we want to use it.

**Comment by prydonius** [comment]
@andresmgot thanks for the explanation! We could think about a way to make the download method from chart repositories more pluggable, though that's a very rough thought so I'm not entirely sure what that would look like. Let's keep this open in the meantime, and come back to it.

**Comment by absoludity** [comment]
Closing as Helm3 is moving away from static repositories (in favour of hubs and OCI reps)
