### ISSUE TITLE
Feature request : Add version number of Kubeapps footer of  page

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#608]
Give the opportunity to  the end user to say what version of Kubeapps they are using when they think they have a problem.
![image](https://user-images.githubusercontent.com/23224162/45325486-44707800-b551-11e8-91f7-4f448618b963.png)

**Comment by migmartri** [comment]
Hi @obeyler 

I agree and I think that's a great idea. 

The trick here is that currently we have two kind of versions: one for the kubeapps release itself and another one for the Helm chart.

These are for example the two current versions represented in the charts' `Chart.yaml` file:

https://github.com/bitnami/charts/blob/964eabbcd83c88accd7dd005452870acfc83f51e/bitnami/kubeapps/Chart.yaml#L3-L4

I personally think that it would be more useful to show in the footer the version of the application itself (Kubeapps release) than the Chart version (which I believe it's what's shown in the screenshot). Mainly because the chart version might get updated with some deployment fixes that might not affect the application itself. Also because the chart version does not have release notes associated.

I'd start with that and then if we think it is useful, iterate on the idea showing the chart version as well? I just want to avoid making it confusing by adding two versions. One thing that I'd add though is to show the commit sha or `devel` in case that you are running the `latest` image from master and not a release.

What do you think?  

cc/ @andresmgot @prydonius

**Comment by prydonius** [comment]
@migmartri agreed, although how do you reckon we can show the commit sha, given we won't really have that in the Helm chart? Maybe it's something we can build into the nginx container at build time?

**Comment by migmartri** [comment]
Yes, when we build the static frontend container we "bake" the version using webpack. I did something similar here https://github.com/migmartri/slacktronic/commit/5ec90258c83daf59373be29f3c414a1ba3b2e048#diff-83ceb7ee91c30c5e749be525f75adf92L47

The main issue I can see is that because we do not have create-react-app ejected we might have some trouble extending the webpack config. That might have changed though.

**Comment by prydonius** [comment]
Cool, we may be able to do this with the environment variables: https://stackoverflow.com/questions/42458434/how-to-set-build-env-variables-when-running-create-react-app-build-script

**Comment by obeyler** [comment]
I agree with you the number version should be the app version and not the chart as may the app will be deploy by another way than the chart.

**Comment by andresmgot** [comment]
My +1. In any case note that the versions info would be available as well when checking the Kubeapps app view (by default in `/apps/ns/kubeapps/kubeapps`)

**Comment by migmartri** [comment]
@andresmgot that's a good point, I forgot about it. The main issue with that approach is that apart of the version not being that prominent (which might be ok) an user might not be able to see the namespace where kubeapps is installed, which also might be ok.

**Comment by prydonius** [comment]
Good points, I think we'd want to try to build the version into the app as that way we can also get the commit sha (e.g. for latest tags).
