### ISSUE TITLE
OIDC login with Keycloak: Error refreshing access token after 5 minutes

### ISSUE THREAD

**Issue by ghost** [kubeapps/kubeapps#6106]
I noticed that my kubeapps session times out after just 5 minutes, which is bad when I'm in the process of editing an application.
I exactly followed [official setup instructions](https://kubeapps.dev/docs/latest/howto/oidc/oauth2oidc-keycloak/). 
The logs say
```
[stored_session.go:94] Error loading cookied session: error refreshing access token for session (Session... id_token:true): session is expired, removing session
```
Sometimes in the browser I get a red message saying
```
An error occurred: n['grpc-message'] is undefined
```
Sometimes in the logs I see (while having a login redirect loop)
```
[stored_session.go:94] Error loading cookied session: error copying lz4 stream to buffer: lz4: bad magic number, removing session
```

Possibly related:
https://keycloak.discourse.group/t/access-tokens-expiring-after-5-minutes-regardless-of-lifetime-set-when-ajax-calls-are-involved/20661

**Comment by absoludity** [comment]
Hi @kllp . Kubeapps itself doesn't know anything about auth, other than whether it is able to talk to the k8s api server (redirecting to login if not). We use oauth2-proxy, which looks after setting the cookie for us (and it's http-only, so we cannot even see that - it is simply sent with every request, including ajax ones).  oauth2-proxy also handles the interaction with the identity provider (including refreshing tokens etc.).

So you'll need to look at the interaction between oauth2-proxy and your upstream, which is I assume what you're doing... that initial log for `stored_session.go:94` is I assume from the auth-proxy container?

Things to note:
- there can be issues with the size of the id token being sent not being stored/refreshed correctly when using the cookie storage of oauth2-proxy. You can verify whether this is the case by switching to use the redis storage for oauth2-proxy and seeing if that helps.
- The cookie storage can also suffer from concurrency issues, as [noted in their docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/session_storage/#cookie-storage). Again, trying with Redis might help.
- The refresh policy depends on configuration in both your keycloak setup and oauth2-proxy, so there may be other settings to try there (such as the oauth2-proxy `--cookie-refresh` option.

The original error message is stating that it was unable to refresh the access token because the session itself had already expired, so I'd start by checking keycloak settings related to session expiry or refresh token expiry, which should be longer... if you keep your access token expiry at 5m but the refresh token is valid for 1hr, oauth2-proxy would be able to use it to refresh the access token whenever it was no longer valid, I think?

Let us know what you find.

**Comment by absoludity** [comment]
I'd certainly not ignore the warning - it's oauth-proxy trying to tell you that things may stop working. As you mentioned, there are two possible ways forward:

1. Update your ingress (outside Kubeapps) and your Kubeapps frontend (can do this from the chart) to accept larger cookies. This solution is not great, and more of a temporary fix, as the cookie size could increase again depending on what Keycloak does.
2. Use Redis for session storage: this is by far the better option.


Regarding the additional arguments you mention for the chart, note that the Kubeapps chart allows you specifying any extra flags you need for oauthProxy, such as the redis-connection-url and session-store-type:

https://github.com/vmware-tanzu/kubeapps/blob/2083bd73a31b42972da24fa6928163c17174470f/chart/kubeapps/values.yaml#L1200-L1208

The values for the redis connection url will depend on your setup. I'd suggest installing the Bitnami redis chart on the same cluster, before installing Kubeapps, then setting the redis connection url with your kubeapps installation after having tested it manually from your redis install.

**Comment by absoludity** [comment]
This redis instance isn't related to Kubeapps (ie. not the configuration in our chart which can be used by the flux plugin). You just need a redis instance accessible by oauth2proxy, so I'd just deploy the bitnami chart and follow the instructions on the oauth2 proxy website. I've not tried it as a sidecar container, but no reason why it shouldn't work.
