### ISSUE TITLE
chart-repo: support case insensitive readme file in charts

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#617]
Do you know why some chart hasn't got any description when click on cartrige ? I suppose it's due to the chart himself but could you point what they don't have to be able to provide it ?

**Comment by prydonius** [comment]
@obeyler do you have a screenshot? I'm guessing it's because the chart doesn't have a README.md

**Comment by obeyler** [comment]
In fact I found several charts who don't respect the name "README.md" they use "readme.md" 
so may it's for this reason that the description isn't present
Thanks for your answers

**Comment by prydonius** [comment]
@obeyler hmm interesting, it should be README.md as described in the Helm docs, I'm not sure if we'd want to support lowercase readme.md though.

**Comment by obeyler** [comment]
here is an example it's for Eclipse Che : "A cloud eclipse IDE "
https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che

**Comment by obeyler** [comment]
so I put an issue on che ;-)

https://github.com/eclipse/che/issues/11193

**Comment by migmartri** [comment]
> so I put an issue on che ;-)
> 
> [eclipse/che#11193](https://github.com/eclipse/che/issues/11193)

Thanks @obeyler 

It might make sense as well to check the README.md as part of the helm linter even as INFO https://github.com/helm/helm/tree/master/pkg/lint/rules

**Comment by obeyler** [comment]
Eclipse Che has fixed the issue in their side ;-)

**Comment by prydonius** [comment]
woot, thanks for the update @obeyler :)

**Comment by arapulido** [comment]
So, what are we going to do on the Kubeapps side? Are we going to close this as Won't fix, or are we going to accept lowercase as well?

**Comment by jessehu** [comment]
@andresmgot Could you assign this issue to me please? I'd like to help. Thanks.

**Comment by andresmgot** [comment]
sure @jessehu, feel free to tackle this.

Let me give you a bit of context first. There are a couple of microservices that are shared between kubeapps and [monocular](https://github.com/helm/monocular). These are `chart-repo` and `chartsvc`. `chart-repo` is a CLI that is used to download the code from a Helm registry and populates the database. The `chartsvc` exposes the information of the database as a REST API. The code for these two microservices can be found [here](https://github.com/helm/monocular/tree/master/cmd).

For this issue you need to modify the `chart-repo` tool since it's the one that checks if this file exists and populates the database. In particular, this is the method you need to modify:

https://github.com/helm/monocular/blob/master/cmd/chart-repo/utils.go#L344

As you can see there, we are just checking if `README.md` exists, we can also check if `readme.md` is present otherwise.

There should be documentation enough for you to build and test that image but let me know if you need any help with that!

**Comment by jessehu** [comment]
Thanks a lot @andresmgot. Your guide is quite clear to me. I see the code for reading README.md. I'd suggest checking for README.md/readme.md/Readme.md for more coverage.
BTW, I find the Developer Documentation on the homepage:
- The [Kubeapps Build Guide](docs/developer/build.md) for instructions on setting up the build environment and building Kubeapps from source.
- The [Kubeapps Developer Documentation](docs/developer/README.md) for instructions on setting up the developer environment for developing on Kubeapps and its components.

**Comment by jessehu** [comment]
@andresmgot @prydonius I submitted https://github.com/helm/monocular/pull/639 to fix this issue. Please take a look. Thanks.
BTW, how to tell kubeapps to use the new chart-repo container?

**Comment by andresmgot** [comment]
> how to tell kubeapps to use the new chart-repo container?

What we do is release a new version of monocular and use the new tag here (for example https://github.com/kubeapps/kubeapps/pull/1086/files). I can do that part.

**Comment by jessehu** [comment]
This fix will be included in v1.4.2 (to be released)
