### ISSUE TITLE
Relax yaml parsing in releases/view page

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#636]
@stormmore [reported](https://github.com/kubeapps/kubeapps/issues/632) that Kubeapps was failing to show the resources part of his chart. 

The [research showed](https://github.com/kubeapps/kubeapps/issues/632#issuecomment-421111993) that the root cause was a parsing error on our client.

Our yaml parser complained about a duplicated tag vs Helm does not. We should look into if there is any way to make our parser less restrictive. More taking into account that a duplicated label is not per-se forbidden or discouraged by the helm linter so it might happen again.

**Comment by prydonius** [comment]
We use the safeLoad function from https://github.com/nodeca/js-yaml#safeload-string---options-, and it looks like there is an option to be compatible with the JSON.parse behaviour which explicitly says "If true, then duplicate keys in a mapping will override values rather than throwing an error." So setting this to true should fix the reported issue, but we may want to also consider the non-safe `load` function as we know that Helm & Kubernetes have pre-validated the YAML we're reading.

**Comment by prydonius** [comment]
For some reason, likely due to a bug in the upstream package, yaml.safeLoadAll does not seem to correctly support the `json` option, though yaml.safeLoad and yaml.loadAll do. Once again, given that we are only going to be parsing YAML that has already been parsed by Helm and Kubernetes, I think it is okay to switch to `yaml.loadAll` here, which seems to support some special JS-related YAML tags: https://github.com/nodeca/js-yaml#load-string---options-.

Filed https://github.com/nodeca/js-yaml/issues/456 for the upstream issue.
