### ISSUE TITLE
Improve access URL loading feedback

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#748]
It seems that the section at the top of the application that shows URLs for LoadBalancers and ingresses take some time to appear. We might want to add a loading icon in that section or some kind of message saying that we are retrieving that info. 

Also, if no public access URL is provided, we can add a message saying that this can be changed by setting services as LB or adding ingress rules.

![selection_727](https://user-images.githubusercontent.com/24523/47205607-b45ef300-d386-11e8-9c02-522ce5d0f630.png)

**Comment by andresmgot** [comment]
@migmartri a couple of questions/comments here:

What do you think about the rest of components? Should we wait until everything is loaded before showing the App view or only for services/ingress?

> Also, if no public access URL is provided, we can add a message saying that this can be changed by setting services as LB or adding ingress rules.

What if the application doesn't have any Ingress/LoadBalancer by design? I think an info message there could be confusing?

**Comment by prydonius** [comment]
> Should we wait until everything is loaded before showing the App view or only for services/ingress?

I'm not sure, I think it's not worth hiding what we can already show to the user, otherwise things will just seem really slow. I think a loading indicator if there are Services/Ingresses to load will be the best way to indicate that something is still happening.

> What if the application doesn't have any Ingress/LoadBalancer by design? I think an info message there could be confusing?

I agree this could be a little misleading, I would leave this for now.
