### ISSUE TITLE
Allow adding an optional description for app repositories

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#759]
We can add a `description` property or annotation to the AppRepository spec.

cc @arapulido

**Comment by absoludity** [comment]
Since we've pulled this out as a good first task that might give exposure to a lot of Kubeapps, as it is currently, I'll just provide a bit more information:

Currently when a user creates an AppRepository, it is really just a name (regex-restricted to lower alpha and hyphens) and a URL, together with some other optional info (credentials, templates for pod specs etc.) that aren't relevant here.

It'd be great to add an additional description field so that a little more information can be presented in various contexts to other users that use the repository later.

I expect this will require updating the CRD, modifying the api calls used to create and edit AppRepositories, as well as updating the UX to include this field during create and edit interactions. Optionally we could also use the description when a user filters by repository or when displaying the repository used for an app etc.

**Comment by gfichtenholt** [comment]
The enhancement has been implemented and code was merged
