### ISSUE TITLE
Configure chart repo HTTP requests with Kubeapps-specific user-agent and version

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#767]
We currently interact with chart repositories over HTTP in two components:

1. chart-repo
Regularly syncs chart repositories (requesting the index.yaml files). Currently uses a user-agent for the `chart-repo` tool, but this will be shared with deployments of Monocular, so we should make this configurable in `chart-repo` to set a Kubeapps specific user-agent (e.g. `chart-repo/v1.0.0 (Kubeapps v1.0.0)`.
1. tiller-proxy
On chart installs, fetches the index.yaml and tarball for the chart. Currently this doesn't set any specific user-agent (as far as I can see in https://github.com/kubeapps/kubeapps/blob/master/pkg/chart/chart.go, @andresmgot let me know if I'm missing something), so we should set the user-agent here to something specific (e.g. `tiller-proxy/v1.0.0 (Kubeapps v1.0.0)`

This will improve logging and debugging interactions with chart repositories so we can clearly see what components might be having issues with chart repos. These logs with also give chart repository owners a better indication of how many people are using Kubeapps and installing charts through it with their chart repositories.

**Comment by migmartri** [comment]
@prydonius in your example

> chart-repo/v1.0.0 (Kubeapps v1.0.0).

Is any of those the chart version? How important do you consider that it is to have the chart-repo version for example?

Looking at the "standard" way of defining user agents `User-Agent: <product> / <product-version> <comment>`

Would it make sense make the product kubeapps or monocular while in the comment mentioning the source (i.e tiller-proxy?)

**Comment by prydonius** [comment]
@migmartri Sorry for the confusion, also I think this was written before chart-repo was moved to the Monocular repo. The v1.0.0 after the chart-repo is the chart-repo version (currently v1.0.1), and then the version after the Kubeapps would be the Kubeapps version (currently v1.0.0-beta.4).

> Would it make sense make the product kubeapps or monocular while in the comment mentioning the source (i.e tiller-proxy?)

I think this could make sense, but there should be a default case where you run the tool standalone (e.g. it is sometimes useful to run chart-repo standalone to debug).

**Comment by migmartri** [comment]
Thanks @prydonius 

In my head we have a couple of options if we follow this pattern `User-Agent: <product> / <product-version> <comment>`

|desc|option 1|option 2|option 3|
|----|----|----|---|
|tiller proxy running in kubeapps|kubeapps/1.0-beta4 (tiller-proxy) | tiller-proxy (kubeapps v1.0-beta4)|tiller-proxy/v.1.0 (kubeapps v1.0-beta4)|
|chart repo in monocular|monocular/1.0-beta4 (chart-repo) | chart-repo (monocular v1.0-beta4)|chart-repo/v.1.0 (monocular v1.0-beta4)|
|chart repo running by itself|unknown/unknown (chart-repo) | chart-repo|chart-repo/v.1.0
### option 1

* product: kubeapps or monocular
* product-version: appVersion from the chart
* comment: tiller-proxy or chart-repo

Pros:

* Component version does not need to be baked into the binaries but instead rely only in the appVersion of the chart.

Cons:

* We need to setup default placeholders for the case in which it is deployed standalone.

### option 2

* product: tiller-proxy or chart-repo
* product-version: none
* comment: kubeapps or monocular + appVersion from the chart


Pros:

* Component version does not need to be baked into the binaries but instead rely only in the appVersion of the chart.
* Since Kubeapps or Monocular are optional and stored in the comment, the scenario in which component is run standalone seems to fit.

Cons:

* We are not actually following this pattern `<product> / <product-version> <comment>`

### option 3

Like option 2 but including the component version

* product: tiller-proxy or chart-repo
* product-version: tiller-proxy or chart-repo version
* comment: kubeapps or monocular + appVersion from the chart

Pros:

* We have the version of both the component (chart-repo version from Monocular release) and Monocular or Kubeapps appVersion  

Cons:

* This will require us to bake the version in the binaries
* Handles well the case in which the component is run standalone

What's your take @prydonius @andresmgot ?

**Comment by andresmgot** [comment]
I'd go for the option that identifies the agent as detailed as possible (in this case option 3). 

Regarding if we should bake the version in the binaries: I think that is something useful to have regardless of this use. If the version of the binaries is printed for example in the logs that will help possible support error reports to see what version is running.

**Comment by prydonius** [comment]
I agree we should aim for option 3, although we can perhaps start with option 2 if we're not ready to bake versions in binaries yet.

**Comment by migmartri** [comment]
Sounds good, thanks!

**Comment by migmartri** [comment]
I have released the Monocular and verified that the user agent is properly sent cc/ @prydonius @andresmgot 

![selection_750](https://user-images.githubusercontent.com/24523/48291837-b61f5200-e42c-11e8-95d5-923bed316006.png)

**Comment by migmartri** [comment]
I can confirm that the user-agent is being added now.

> 100.100.0.49 - - [15/Nov/2018:03:43:17 +0000] "GET /index.yaml HTTP/1.1" 200 1555 "-" "chart-repo/v1.0.2 (kubeapps/v1.0.0)"

> 100.108.0.35 - - [15/Nov/2018:03:44:34 +0000] "GET /index.yaml HTTP/1.1" 200 1555 "-" "tiller-proxy/a87cf225bfa6f2b7c90b9c7751634d9a2b98d693 (kubeapps/v1.0.0)"

but tiller proxy does not seem to have baked the version properly

**Comment by migmartri** [comment]
Nevermind, it was a configuration error on my side. By using the proper values file tiller-proxy shows the proper version.

> 100.105.0.28 - - [15/Nov/2018:04:05:44 +0000] "GET /index.yaml HTTP/1.1" 200 1555 "-" "tiller-proxy/v1.0.0 (kubeapps/v1.0.0)"
