### ISSUE TITLE
Add the possibility of showing Secrets in the AppView

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#795]
For getting for example the password of "Wordpress" without needing to open a terminal and execute the command showed in the NOTES, we could add a button to show secrets included in the Chart:

![screenshot 2018-11-08 at 16 05 34](https://user-images.githubusercontent.com/4025665/48207187-6da25e80-e370-11e8-8e7c-2514ba60c1e0.png)

That way users can get the application password without leaving Kubeapps (the same approach we do with Service Instances).

**Comment by beltran-rubo** [comment]
This is pretty useful for users that do not have access to the shell for running the kubectl commands. I would consider to raise the priority of this.

**Comment by prydonius** [comment]
@arapulido lets consider this on Monday

**Comment by andresmgot** [comment]
@prydonius what do you think of having a section under "Services" to show secrets?  Something like:

<img width="909" alt="screenshot 2018-11-20 at 17 43 58" src="https://user-images.githubusercontent.com/4025665/48790111-e8fbfc80-ecee-11e8-9cf5-f973340acb83.png">

Then to make it nicer we can substitute the `show` link with an icon that displays/hides the secret content, something like what the K8s dashboard does:

<img width="316" alt="screenshot 2018-11-20 at 17 59 39" src="https://user-images.githubusercontent.com/4025665/48790174-10eb6000-ecef-11e8-8ed8-b19cd00c6643.png">

**Comment by prydonius** [comment]
@andresmgot the table looks great, but I was thinking that we might want to bring this out above the "Details" section to where either below or above the NOTES so that it is more prominent. What do you think?

**Comment by prydonius** [comment]
Discussed a little bit in Slack: https://kubernetes.slack.com/archives/C9D3TSUG4/p1542733780100100.

The concern with the details view is that it can be hidden on smaller screens or if there are large numbers of Deployments and Services. Also, in the future we may want to remove this section or collapse it as it is too much detail.

The issue with having it below Access URLs is that it might be a bit too prominent, especially if it contains irrelevant secrets like TLS certs (we could filter here by type, i.e. skip `kubernetes.io/tls` types, or only show opaque types).

We could have it after the NOTES.txt but before the details section, but that also might make it have too little prominence, or might cause people to copy and paste commands to run instead of viewing the secret in the UI.

One thing to look into is how the GKE console lays out application info with their GKE marketplace apps.

**Comment by andresmgot** [comment]
Just checked the GKE marketplace, basically it's the same approach:

![screenshot 2018-11-20 at 19 05 55](https://user-images.githubusercontent.com/4025665/48793570-adb1fb80-ecf7-11e8-9914-715aa9b8ff1d.png)

From the screenshot you can see that you can follow the notes on the right to get the credentials (similar to the NOTES.txt) but you can also select the secret from the list in the bottom if you know that the secret will contain the credentials.

My take right now is to do something similar: Add a secret section like in my first screenshot to avoid polluting the section at the top. People can either follow the NOTES to get the password or click in the secret at the bottom (even if it's a bit hidden).

Ideally I would do a different section in the top for "Credentials". We could set an annotation in the secret to identify it as credential so we can parse it differently from the rest of secrets. That's something we may want to propose to the chart maintainers but it's a bit out of the scope for this. WDYT?

**Comment by prydonius** [comment]
I like that the GKE console has the NOTES to the side, it makes the other components listing more noticeable. That said, it won't really fit our layout since we aren't using the full width.

It would be good to see what it looks like when above and below the NOTES.txt, to understand better how much it will pollute the top part.

> Ideally I would do a different section in the top for "Credentials". We could set an annotation in the secret to identify it as credential so we can parse it differently from the rest of secrets. 

I really like the idea of having a Credentials section. FWIW I don't think we need a specific annotation here, I think we can get away with filtering by Opaque Secret types. We won't show the secrets until you actually click on "show" so I don't think the row of Secret objects will pollute things too much.

**Comment by prydonius** [comment]
I agree with the position of the Secrets under the NOTES, @andresmgot - good point about the username.

As far as Opaque vs secret type, good point (honestly I think the service catalog and OSBA are wrong there, and should be using the tls type), but also Opaque does not always equal credentials. Regardless, I don't think we should implement support for an arbitrary annotation that will only be implemented by our own charts. Rather, I think we can wait for something else to solve this (e.g. the App CRD).
