### ISSUE TITLE
Add some documentation in dockerHUB

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#839]
Currently, the description of our images in dockerhub show no description. It might make sense to add a link to the getting started guide or something there.

https://hub.docker.com/r/kubeapps/dashboard/

**Comment by prydonius** [comment]
Added an explanation of Kubeapps, Helm install command and link to the getting started in each of these Docker Hub pages:

- https://hub.docker.com/r/kubeapps/dashboard/
- https://hub.docker.com/r/kubeapps/chart-repo/
- https://hub.docker.com/r/kubeapps/chartsvc/
- https://hub.docker.com/r/kubeapps/apprepository-controller/
- https://hub.docker.com/r/kubeapps/tiller-proxy/

**Comment by andresmgot** [comment]
I see that you are using the same description for all the images. Shouldn't we at least include some specific information? Like the information in `docs/architecture/overview.md`

**Comment by prydonius** [comment]
As discussed in the call, we want to actually specify less information here for the following reasoning:

a) We expect that the users browsing Docker Hub are more likely to be users and not contributors, so it doesn't make sense to go into detail about each component
b) We want to be brief and guide people to the getting started docs so that we can avoid having another place we need to keep documentation up-to-date


As such, I have updated the descriptions of each page to simply:

> For instructions on how to install and use Kubeapps follow the [Getting Started Guide](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md).
