### ISSUE TITLE
Improve debug experience

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#860]
If the user needs to investigate any error message, Kubeapps does not show the main info where the user can see what is happening. Be able to see the “describe” command or the “logs” from the pods would empower users to debug any deployment error on their side.

If there is any error with containers, Kubeapps keeps the state as “deploying” for a long time (not sure if there is a timeout in those cases). Showing the info of the status of the pods would help the user to identify issues. E.g.;

```
test-drupal-5f67965cdd-qrwwr              0/1       ImagePullBackOff   0          6m
test-mariadb-0                            0/1       ImagePullBackOff   0          6m
```

cc/ @beltran-rubo @juan131

**Comment by prydonius** [comment]
I think this is useful, but we want to be careful how we design the UX around this, because we don't want to get into complicated Kubernetes Dashboard territory and ensure we focus on a simple experience.

One potential idea is to display a warning in the DeploymentStatus component, that when clicked on, goes to a more detailed view where logs and other information can be viewed.

I think we should be careful about when we show a warning about state, because the nature of Kubernetes means things can be expected to fail and eventually become healthy. Often, you'll see the Kubernetes dashboard report early warnings about, for example, a PVC not yet being fulfilled and so cannot be mounted in a Pod. Therefore, I think we should have a timeout of when we consider things unhealthy, or better yet, look for specific issues (ImagePullBackOff, CrashLoopBackOff).
