### ISSUE TITLE
One click/command to install Kubeapps

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#861]
The current installation guide requires the following steps:

```bash
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
$ kubectl create serviceaccount kubeapps-operator
$ kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
$ kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode
$ export POD_NAME=$(kubectl get pods -n kubeapps -l "app=kubeapps,release=kubeapps" -o jsonpath="{.items[0].metadata.name}")
$ echo "Visit http://127.0.0.1:8080 in your browser to access the Kubeapps Dashboard"
$ kubectl port-forward -n kubeapps $POD_NAME 8080:8080
```

It is good to see all the actions for users that want to have full control over they are doing on their cluster, but it could be tedious or a slow process for users that want just try Kubeapps.

Alternative 1

Would be possible to install via single command line for getting started faster (that can be also inspectable for users)? E.g. 

```bash
$ curl http://.../install-kubeapps && ./install-kubeapps
```

The output can show the token and the URL the user should use to start using to login in the dashboard. 
The script could use a namespace such as `kubeapps-testing` where RBAC rules are configured for the user user to create/delete charts.

Alternative 2

Allow installing Kubeapps in an “insecure” mode where Tiller Proxy does not check any RBAC rule.

cc/ @beltran-rubo @juan131

**Comment by prydonius** [comment]
Let's break those commands up a bit, installing Kubeapps requires:

```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
$ kubectl create serviceaccount kubeapps-operator
$ kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
```

Accessing Kubeapps requires:
```
$ kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{.secrets[].name}') -o jsonpath='{.data.token}' | base64 --decode
$ export POD_NAME=$(kubectl get pods -n kubeapps -l "app=kubeapps,release=kubeapps" -o jsonpath="{.items[0].metadata.name}")
$ echo "Visit http://127.0.0.1:8080 in your browser to access the Kubeapps Dashboard"
$ kubectl port-forward -n kubeapps $POD_NAME 8080:8080
```

One idea, is to have the Helm chart (optionally) create the `kubeapps-operator` ServiceAccount for you, and print out the command to get the token in the NOTES.txt. That would save two steps.

I'm not sure about the idea of having an install script, also I think the install script should not also be the script that accesses Kubeapps, because once Kubeapps is installed, you don't want to run the script again to access it. We could have a script `launch-kubeapps.sh`, but I'm not convinced that provides much value if all it is doing is `kubectl port-forward` and printing out a token for you.

The insecure mode is potentially worth doing, additionally to putting Tiller Proxy in auth disabled mode, it would require setting up a ServiceAccount to access the Kubernetes API with the token pre-configured for every request to the API.

**Comment by arapulido** [comment]
@beltran-rubo How important is this for your team?

**Comment by arapulido** [comment]
@beltran-rubo We are closing this issue. Let us know if you want us to reconsider. Thanks!
