### ISSUE TITLE
kubeapps dashboard 401

### ISSUE THREAD

**Issue by shangjunimo** [kubeapps/kubeapps#937]
![image](https://user-images.githubusercontent.com/16662815/51588513-6b877f00-1f1f-11e9-8589-868af4d40d7e.png)

**Comment by andresmgot** [comment]
Hi @shangjunimo,

We are in the process of fixing this issue. See #882 for more details. In the meantime you can extend the permissions of your service account in order to be able to `watch` resources in a namespace. Please read this documentation to know how to properly configure access control in Kubeapps:
https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md

**Comment by prydonius** [comment]
@shangjunimo could you give some more information about what permissions your login has? I assume you have list/get but not watch? Just wondering because if you don't have get, you should have gotten a permissions error.
