### ISSUE TITLE
Test OIDC support against different providers

### ISSUE THREAD

**Issue by prydonius** [kubeapps/kubeapps#948]
Related to #385, #931 and dependent on #945. We should test a set of popular Kubernetes OIDC provider configurations and document what we know to work. For example, we should test:

- Dex
- Keycloak
- ActiveDirectory with AKS

I've only listed ones that are specific to people setting up against their Kubernetes clusters, feel free to add any others that make sense.

**Comment by andresmgot** [comment]
As far as I understood Rancher is not an OIDC provider but relies in other OIDC providers, am I right?

**Comment by prydonius** [comment]
@andresmgot Dex acts in a similar way, but actually Rancher does also have a "local" auth method which could be it's own OIDC provider: https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/local/

**Comment by andresmgot** [comment]
It seems that Dex is not an identity provider either?

From its [Github](https://github.com/dexidp/dex) page:

> Dex is an identity service that uses OpenID Connect to drive authentication for other apps.
>
> Dex acts as a portal to other identity providers through "connectors."

**Comment by prydonius** [comment]
@andresmgot from my understanding, it is an OIDC provider that allows you to connect to other non-OIDC things. For example, if your company uses LDAP, that won't work with Kubernetes because it only supports OIDC. So you'd put Dex in front of it, which will work with Kubernetes, and Dex then delegates to LDAP and translates LDAP auth to OIDC auth. @migmartri does this understanding match yours?

**Comment by andresmgot** [comment]
yes, it's more like an ambassador. I tried to follow their guide to use [Dex with GitHub](https://github.com/dexidp/dex/blob/master/Documentation/kubernetes.md) but didn't work. At the end I was not able to logging into the cluster.

**Comment by arapulido** [comment]
@andresmgot it would be good if you could add here notes to your progress (what you tried, what you achieved, where did it fail, etc) for the different providers you are trying. Thanks!

**Comment by andresmgot** [comment]
So far I have several different setups:

 - Keycloak + keycloak-gatekeeper: This setup works as expected. The Keycloak server sets a cookie `kc-access` that is read by keycloak-gatekeeper to obtain the bearer token of the connection. It requires to use the client-id set in Keycloak, the secret and use as discovery URL: `https://keycloak.devlocal/auth/realms/<realm_name>`.
 - Azure Active Directory + oauth2_proxy: The server sets the cookie `_oauth2_proxy`, this contains information about the email of the user and other info but it does not contain the bearer token. This causes that oauth2_proxy instead of setting the bearer token as Authorization header it sets it as "Basic` and uses the user of the email but not password (i.e. `andres:`). That Authorization header is wrong so we cannot use it to authenticate requests against the cluster. Flags used for oauth2_proxy: 
```
        - --email-domain=*
        - --cookie-secure=false
        - --cookie-secret=AhW93OvPPMOF+3xS
        - --client-id=<ServerAAD App ID>
        - --client-secret=<ServerAAD Key>
        - --azure-tenant=<Tenant ID>
        - --provider=azure
        - --http-address=0.0.0.0:4180
        - --upstream=http://kubeapps/
        - --pass-authorization-header
```
- Azure Active Directory + Keycloak gatekeeper: In this case I can add the credentials just like the case before but once the credentials have been introduced the proxy sets the proper cookie (`kc-access`) and it's able to set the Bearer token in the authorization header. Flags used in this case:
```
        - --client-id=<ServerAAD App ID>
        - --client-secret=<ServerAAD App ID>
        - --secure-cookie=false
        - --discovery-url=https://sts.windows.net/<tenantID>/
        - --upstream-url=http://kubeapps/
```
- Dex + keycloak gatekeeper + GitHub OIDC: In this case, I am able to introduce my Github credentials but after that it's returning an error: "unable to exchange code for access token","error":"invalid_client: Invalid client credentials." I need to keep investigating this scenario. Flags used:
```
        - --client-id=kubeapps
        - --client-secret=<app secret ID>
        - --discovery-url=https://dex.example.com:32000
        - --skip-openid-provider-tls-verify
        - --secure-cookie=false
        - --upstream-url=http://kubeapps/
        - --resources=uri=/api/kube/*|white-listed=true
        - --listen=0.0.0.0:3000
```

**Comment by prydonius** [comment]
> * Azure Active Directory + Keycloak gatekeeper: In this case I can add the credentials just like the case before but once the credentials have been introduced the proxy sets the proper cookie (`kc-access`) and it's able to set the Bearer token in the authorization header. Flags used in this case:

Does this mean this scenario is working then?

**Comment by prydonius** [comment]
@migmartri any ideas about the Dex issue? You could also try a different connector in Dex (e.g. Google) to check if it's a GitHub issue.

**Comment by andresmgot** [comment]
> Does this mean this scenario is working then?

Yes, I finally got it working :)

**Comment by andresmgot** [comment]
> You could also try a different connector in Dex (e.g. Google) to check if it's a GitHub issue.

I have tried with google and the issue is the same: `unable to exchange code for access token	{"error": "invalid_client: Invalid client credentials."}`. I have also tried with oauth2_proxy to see if this is an issue with the proxy but the result is the same.

**Comment by andresmgot** [comment]
I have tried the scenario Google Oauth + keycloak gatekeeper and that works as expected as well.

**Comment by davidkarlsen** [comment]
Maybe worthwhile adding ICP to the list? https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.1/user_management/auth_onboard.html

I can do some testing if some preliminary docs are in place (and support for configuring through the chart)

**Comment by andresmgot** [comment]
Thanks @davidkarlsen! I am working on a first version for the docs in this PR: https://github.com/kubeapps/kubeapps/pull/967

Once that is ready it would be great if you can try it with IBM and add any documentation if needed, as far as it has support for OIDC it should work as any of the other providers. I know there are other people also interested in the solution by Rancher so they can contribute with that as well.
