### ISSUE TITLE
[Feature Request] Ability for Kubeapps to auto-upgrade itself

### ISSUE THREAD

**Issue by stormmore** [kubeapps/kubeapps#958]
It would be super awesome if Kubeapps took care of itself when it comes to patch and minor upgrades, i.e. non-breaking, potentially security related, etc. with an automated notification for breaking updates (stretch of sending notification to a preferred communication channel, i.e. Slack channel, email, etc.)

**Comment by arapulido** [comment]
@stormmore what do you mean? auto-upgrade Kubeapps itself, or the apps managed by Kubeapps?

**Comment by andresmgot** [comment]
From a [Slack conversation](https://kubernetes.slack.com/archives/C9D3TSUG4/p1549484300078400) he means Kubeapps itself.

**Comment by arapulido** [comment]
Thanks, I have updated the title to make it more clear

**Comment by absoludity** [comment]
Currently Kubeapps, by design, does all install/upgrade/deletion events using the currently logged-in users token. We'd need to move in a different direction and have an agent with privileges to upgrade in all namespaces, which is pretty dangerous. I'd prefer to have the ability to see all apps installed on a cluster so a logged in user (with appropriate RBAC) can choose what to do (notify people or upgrade them if people have opted for upgrades).
