### ISSUE TITLE
Allow for deployment within a namespace that does not require cluster admin access

### ISSUE THREAD

**Issue by liangjacky** [kubeapps/kubeapps#992]
In the pre-requisites [here](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/README.md), it states: `Administrative access to the cluster to create and update RBAC ClusterRoles`

At our org, the k8s cluster is owned by one team (they are the only ones with admin access) that manages it, and creates namespaces for other teams to used the managed cluster. 

We have our own tiller deployment and use helm to deploy apps within the namespace, but we cannot deploy an instance of kubeapps as we just do not have those permissions. 

Could we have a setting where kubeapps can only access and change things within a single namespace and not cluster wide?

**Comment by andresmgot** [comment]
hi @liangjacky,

That pre-requisite is no longer valid (sorry, we forgot to remove that). It's not necessary to create ClusterRoles to use Kubeapps. 

In any case it's true that Kubeapps requires a Custom Resource Definition (CRD) in order to setup [AppRepositories](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/apprepository-crd.yaml). This definition is cluster-wide so it's necessary to have admin privileges to install it the first time. Once that's present you can install a Kubeapps instance per namespace with limited access to the cluster.

My recommendation is to request your admin team to manually install that CRD and then you can self-serve since the chart will omit that CRD if it already exists.

**Comment by arapulido** [comment]
@liangjacky We are closing the issue now. Let us know if you have any other question. Thanks!
