### ISSUE TITLE
install on vps

### ISSUE THREAD

**Issue by mr-aam** [kubeapps/kubeapps#993]
hi , i want install my vps , my vps is 1 core , 2 ram ubuntu 18.4 , i can install on it? how do it?

**Comment by andresmgot** [comment]
Hi @mr-aam,

In order to run Kubeapps you need a Kubernetes cluster. In order to create a Kubernetes cluster you can use any of the offerings of the different cloud provides like [GKE](https://cloud.google.com/kubernetes-engine/), [EKS](https://aws.amazon.com/eks/) or [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/). Once you have a working cluster, you need to install [Helm](https://helm.sh/). With that you have all the components required to install Kubeapps. To do so you can follow the steps in the [getting started guide](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md).

Hope that helps,

**Comment by prydonius** [comment]
@mr-aam it may be possible to run Kubernetes on your VPS by configuring a single master (see https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/), and then installing Helm and Kubeapps. I'm not sure how performant that will be on a 1 core, 2 GB ram VM, though.

**Comment by arapulido** [comment]
@mr-aam we are closing this now. Let us know if you have any other question. Thanks!
